import 'meal_component.dart';

/// Curated library of ~40 single-ingredient [MealComponent]s surfaced in the
/// "Common" section of the build-a-meal sheet ([kQuickAssemblies] covers
/// multi-ingredient combos; this covers the individual building blocks).
///
/// A USDA-backed searchable ingredient table is the long-term plan (deferred —
/// see the build-a-meal redesign notes); this static list is the interim
/// dataset so users can assemble a meal from real single ingredients today.
///
/// Macros are per-serving estimates (USDA-representative values, rounded).
/// All calorie values satisfy: calories ≈ carbG*4 + proteinG*4 + fatG*9.
const List<MealComponent> kCommonIngredients = [
  // ── Protein ────────────────────────────────────────────────────────────
  MealComponent(
    name: 'Chicken breast',
    portion: '4 oz cooked',
    calories: 187,
    carbG: 0,
    proteinG: 35,
    fatG: 4,
    sodiumMg: 84,
  ),
  MealComponent(
    name: 'Ground turkey (93/7)',
    portion: '4 oz cooked',
    calories: 193,
    carbG: 0,
    proteinG: 22,
    fatG: 11,
    sodiumMg: 88,
  ),
  MealComponent(
    name: 'Salmon',
    portion: '4 oz cooked',
    calories: 233,
    carbG: 0,
    proteinG: 25,
    fatG: 14,
    sodiumMg: 63,
  ),
  MealComponent(
    name: 'Egg',
    portion: '1 large',
    calories: 72,
    carbG: 0.4,
    proteinG: 6.3,
    fatG: 5.0,
    sodiumMg: 71,
  ),
  MealComponent(
    name: 'Egg whites',
    portion: '1/2 cup',
    calories: 63,
    carbG: 0.9,
    proteinG: 13,
    fatG: 0.2,
    sodiumMg: 200,
  ),
  MealComponent(
    name: 'Greek yogurt (plain)',
    portion: '3/4 cup',
    calories: 100,
    carbG: 6,
    proteinG: 17,
    fatG: 0.7,
    sodiumMg: 55,
  ),
  MealComponent(
    name: 'Cottage cheese',
    portion: '1/2 cup',
    calories: 110,
    carbG: 6,
    proteinG: 14,
    fatG: 2.5,
    sodiumMg: 350,
  ),
  MealComponent(
    name: 'Tuna (canned in water)',
    portion: '3 oz drained',
    calories: 73,
    carbG: 0,
    proteinG: 16,
    fatG: 0.8,
    sodiumMg: 230,
  ),
  MealComponent(
    name: 'Turkey deli slices',
    portion: '3 oz',
    calories: 90,
    carbG: 2,
    proteinG: 16,
    fatG: 1.5,
    sodiumMg: 700,
  ),
  MealComponent(
    name: 'Tofu (firm)',
    portion: '4 oz',
    calories: 90,
    carbG: 2,
    proteinG: 10,
    fatG: 5,
    sodiumMg: 9,
  ),
  MealComponent(
    name: 'Whey protein powder',
    portion: '1 scoop',
    calories: 120,
    carbG: 3,
    proteinG: 24,
    fatG: 1.5,
    sodiumMg: 60,
  ),

  // ── Grains & starches ────────────────────────────────────────────────────
  MealComponent(
    name: 'Rolled oats',
    portion: '1/2 cup dry',
    calories: 150,
    carbG: 27,
    proteinG: 5,
    fatG: 2.5,
    sodiumMg: 0,
  ),
  MealComponent(
    name: 'White rice (cooked)',
    portion: '1 cup',
    calories: 205,
    carbG: 45,
    proteinG: 4.3,
    fatG: 0.4,
    sodiumMg: 2,
  ),
  MealComponent(
    name: 'Brown rice (cooked)',
    portion: '1 cup',
    calories: 216,
    carbG: 45,
    proteinG: 5,
    fatG: 1.8,
    sodiumMg: 10,
  ),
  MealComponent(
    name: 'Quinoa (cooked)',
    portion: '1 cup',
    calories: 222,
    carbG: 39,
    proteinG: 8,
    fatG: 3.6,
    sodiumMg: 13,
  ),
  MealComponent(
    name: 'Sweet potato',
    portion: '1 medium, baked',
    calories: 112,
    carbG: 26,
    proteinG: 2,
    fatG: 0.1,
    sodiumMg: 41,
  ),
  MealComponent(
    name: 'Potato',
    portion: '1 medium, baked',
    calories: 161,
    carbG: 37,
    proteinG: 4.3,
    fatG: 0.2,
    sodiumMg: 17,
  ),
  MealComponent(
    name: 'Whole wheat bread',
    portion: '1 slice',
    calories: 81,
    carbG: 14,
    proteinG: 4,
    fatG: 1.1,
    sodiumMg: 144,
  ),
  MealComponent(
    name: 'Pasta (cooked)',
    portion: '1 cup',
    calories: 220,
    carbG: 43,
    proteinG: 8,
    fatG: 1.3,
    sodiumMg: 1,
  ),
  MealComponent(
    name: 'Flour tortilla',
    portion: '1 medium (8")',
    calories: 146,
    carbG: 24,
    proteinG: 4,
    fatG: 3.7,
    sodiumMg: 364,
  ),

  // ── Fruit ────────────────────────────────────────────────────────────────
  MealComponent(
    name: 'Banana',
    portion: '1 medium',
    calories: 105,
    carbG: 27,
    proteinG: 1.3,
    fatG: 0.4,
    sodiumMg: 1,
  ),
  MealComponent(
    name: 'Apple',
    portion: '1 medium',
    calories: 95,
    carbG: 25,
    proteinG: 0.5,
    fatG: 0.3,
    sodiumMg: 2,
  ),
  MealComponent(
    name: 'Blueberries',
    portion: '1 cup',
    calories: 84,
    carbG: 21,
    proteinG: 1.1,
    fatG: 0.5,
    sodiumMg: 1,
  ),
  MealComponent(
    name: 'Strawberries',
    portion: '1 cup, sliced',
    calories: 49,
    carbG: 12,
    proteinG: 1,
    fatG: 0.5,
    sodiumMg: 2,
  ),
  MealComponent(
    name: 'Orange',
    portion: '1 medium',
    calories: 62,
    carbG: 15,
    proteinG: 1.2,
    fatG: 0.2,
    sodiumMg: 0,
  ),

  // ── Vegetables ───────────────────────────────────────────────────────────
  MealComponent(
    name: 'Broccoli',
    portion: '1 cup, cooked',
    calories: 55,
    carbG: 11,
    proteinG: 3.7,
    fatG: 0.6,
    sodiumMg: 64,
  ),
  MealComponent(
    name: 'Spinach',
    portion: '2 cups raw',
    calories: 14,
    carbG: 2.2,
    proteinG: 1.8,
    fatG: 0.2,
    sodiumMg: 48,
  ),
  MealComponent(
    name: 'Mixed greens salad',
    portion: '2 cups',
    calories: 20,
    carbG: 4,
    proteinG: 1.5,
    fatG: 0.2,
    sodiumMg: 20,
  ),
  MealComponent(
    name: 'Avocado',
    portion: '1/2 medium',
    calories: 120,
    carbG: 6,
    proteinG: 1.5,
    fatG: 11,
    sodiumMg: 5,
  ),

  // ── Legumes ──────────────────────────────────────────────────────────────
  MealComponent(
    name: 'Black beans (cooked)',
    portion: '1/2 cup',
    calories: 114,
    carbG: 20,
    proteinG: 8,
    fatG: 0.5,
    sodiumMg: 1,
  ),
  MealComponent(
    name: 'Chickpeas (cooked)',
    portion: '1/2 cup',
    calories: 134,
    carbG: 22,
    proteinG: 7,
    fatG: 2.1,
    sodiumMg: 6,
  ),
  MealComponent(
    name: 'Lentils (cooked)',
    portion: '1/2 cup',
    calories: 115,
    carbG: 20,
    proteinG: 9,
    fatG: 0.4,
    sodiumMg: 2,
  ),
  MealComponent(
    name: 'Hummus',
    portion: '2 tbsp',
    calories: 70,
    carbG: 6,
    proteinG: 2,
    fatG: 5,
    sodiumMg: 130,
  ),

  // ── Dairy & fats ─────────────────────────────────────────────────────────
  MealComponent(
    name: 'Milk (2%)',
    portion: '1 cup',
    calories: 122,
    carbG: 12,
    proteinG: 8,
    fatG: 4.8,
    sodiumMg: 100,
  ),
  MealComponent(
    name: 'Almond milk (unsweetened)',
    portion: '1 cup',
    calories: 39,
    carbG: 1.4,
    proteinG: 1.5,
    fatG: 2.9,
    sodiumMg: 189,
  ),
  MealComponent(
    name: 'Cheddar cheese',
    portion: '1 oz',
    calories: 113,
    carbG: 0.4,
    proteinG: 7,
    fatG: 9,
    sodiumMg: 174,
  ),
  MealComponent(
    name: 'Mozzarella cheese',
    portion: '1 oz',
    calories: 85,
    carbG: 0.6,
    proteinG: 6,
    fatG: 6.3,
    sodiumMg: 176,
  ),
  MealComponent(
    name: 'Almonds',
    portion: '1 oz (~23)',
    calories: 164,
    carbG: 6,
    proteinG: 6,
    fatG: 14,
    sodiumMg: 0,
  ),
  MealComponent(
    name: 'Peanut butter',
    portion: '1 tbsp',
    calories: 94,
    carbG: 3.2,
    proteinG: 4,
    fatG: 8,
    sodiumMg: 75,
  ),
  MealComponent(
    name: 'Almond butter',
    portion: '1 tbsp',
    calories: 98,
    carbG: 3,
    proteinG: 3.4,
    fatG: 9,
    sodiumMg: 2,
  ),
  MealComponent(
    name: 'Olive oil',
    portion: '1 tbsp',
    calories: 119,
    carbG: 0,
    proteinG: 0,
    fatG: 13.5,
    sodiumMg: 0,
  ),
  MealComponent(
    name: 'Butter',
    portion: '1 tbsp',
    calories: 102,
    carbG: 0,
    proteinG: 0.1,
    fatG: 11.5,
    sodiumMg: 82,
  ),

  // ── Sweeteners ───────────────────────────────────────────────────────────
  MealComponent(
    name: 'Honey',
    portion: '1 tbsp',
    calories: 64,
    carbG: 17,
    proteinG: 0.1,
    fatG: 0,
    sodiumMg: 1,
  ),
  MealComponent(
    name: 'Maple syrup',
    portion: '1 tbsp',
    calories: 52,
    carbG: 13,
    proteinG: 0,
    fatG: 0,
    sodiumMg: 2,
  ),
];
