import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:go_router/go_router.dart';
import '../../features/nutrition_plan/domain/food.dart';
import '../../features/nutrition_plan/domain/food_item.dart';
import '../widgets/kyle_design/kyle_design.dart';
import '../widgets/custom_app_bar_back_button.dart';
import '../widgets/food_detail/nutrition_input_fields.dart';
import '../widgets/food_detail/category_selector.dart';
import '../widgets/food_detail/product_type_selector.dart';

/// Mode for the FoodDetailScreen - determines behavior and visible fields
enum FoodDetailMode {
  /// Adding a new food from barcode scan - shows image, all fields editable
  addFromScan,

  /// Adding a new food from search - all fields editable
  addFromSearch,

  /// Editing an existing user food - shows delete button
  editExisting,

  /// Creating a new custom food from scratch - all fields empty/editable
  createNew,
}

/// Context for where the FoodDetailScreen was opened from
/// Used to customize button text and behavior
enum FoodDetailContext {
  onboarding,
  swapFood,
  addFood,
  foodPreferences,
  carbLoading,
}

/// Data class for initializing FoodDetailScreen
/// Consolidates data from Food, FoodItem, and UserFoodData
class FoodDetailData {
  FoodDetailData({
    required this.id,
    required this.name,
    this.imageUrl,
    this.servingSize,
    this.servingAmount,
    this.servingUnit,
    this.carbsPerServing,
    this.proteinPerServing,
    this.fatPerServing,
    this.sodiumMg,
    this.caloriesPerServing,
    this.fluidMlPerServing,
    this.productType,
    this.categoryIds = const [],
  });

  final String id;
  final String name;
  final String? imageUrl;
  final String? servingSize;
  final double? servingAmount;
  final String? servingUnit;
  final double? carbsPerServing;
  final double? proteinPerServing;
  final double? fatPerServing;
  final int? sodiumMg;
  final int? caloriesPerServing;
  final double? fluidMlPerServing;
  final String? productType;
  final List<int> categoryIds;

  /// Create empty data for a new custom food
  factory FoodDetailData.empty() {
    return FoodDetailData(
      id: '', // Will be generated by caller
      name: '',
      categoryIds: [1, 2, 3], // Default: all categories
    );
  }

  /// Create from Food domain object
  factory FoodDetailData.fromFood(Food food) {
    return FoodDetailData(
      id: food.id,
      name: food.name,
      imageUrl: food.imageUrl,
      servingSize: food.servingSize,
      servingAmount: food.servingAmount,
      servingUnit: food.servingUnit,
      carbsPerServing: food.carbsPerServing,
      proteinPerServing: food.proteinPerServing,
      fatPerServing: food.fatPerServing,
      sodiumMg: food.sodiumMg,
      caloriesPerServing: food.caloriesPerServing,
      fluidMlPerServing: food.fluidMlPerServing,
      productType: food.productTypeId,
      categoryIds: food.categories.map((name) {
        switch (name) {
          case 'before_run':
            return 1;
          case 'during_run':
            return 2;
          case 'after_run':
            return 3;
          default:
            return 1;
        }
      }).toList(),
    );
  }

  /// Create from FoodItem domain object
  factory FoodDetailData.fromFoodItem(FoodItem foodItem) {
    return FoodDetailData(
      id: foodItem.id,
      name: foodItem.name,
      imageUrl: foodItem.imageUrl,
      servingSize: foodItem.servingSize,
      servingAmount: foodItem.servingAmount,
      servingUnit: foodItem.servingUnit,
      carbsPerServing: foodItem.carbsPerServing,
      proteinPerServing: foodItem.proteinPerServing,
      fatPerServing: foodItem.fatPerServing,
      sodiumMg: foodItem.sodiumMg,
      caloriesPerServing: foodItem.caloriesPerServing,
      fluidMlPerServing: foodItem.fluidMlPerServing,
      productType: foodItem.productTypeId,
      categoryIds: foodItem.categories.map((cat) {
        switch (cat) {
          case FoodCategory.beforeRun:
            return 1;
          case FoodCategory.duringRun:
            return 2;
          case FoodCategory.afterRun:
            return 3;
        }
      }).toList(),
    );
  }
}

/// Result returned when saving from FoodDetailScreen
class FoodDetailResult {
  FoodDetailResult({
    required this.foodId,
    required this.name,
    this.servingSize,
    this.servingAmount,
    this.servingUnit,
    required this.carbsPerServing,
    required this.proteinPerServing,
    required this.fatPerServing,
    required this.sodiumMg,
    required this.caloriesPerServing,
    this.fluidMlPerServing,
    required this.productType,
    required this.categoryIds,
  });

  final String foodId;
  final String name;
  final String? servingSize;
  final double? servingAmount;
  final String? servingUnit;
  final double carbsPerServing;
  final double proteinPerServing;
  final double fatPerServing;
  final int sodiumMg;
  final int caloriesPerServing;
  final double? fluidMlPerServing;
  final String productType;
  final List<int> categoryIds;
}

/// Unified full-screen page for adding and editing foods
/// Replaces: NutritionVerificationDialog, ScannedFoodCategorySheet, UserFoodEditSheet
///
/// Returns a [FoodDetailResult] when saved, or null when cancelled/deleted.
/// Use with `context.push<FoodDetailResult>('/food-detail', extra: {...})` and await result.
class FoodDetailScreen extends ConsumerStatefulWidget {
  const FoodDetailScreen({
    super.key,
    required this.foodData,
    required this.mode,
    this.screenContext = FoodDetailContext.addFood,
    this.preSelectedCategories,
    this.showCategories = true,
    this.showProductType = true,
    this.allowDelete = false,
  });

  final FoodDetailData foodData;
  final FoodDetailMode mode;
  final FoodDetailContext screenContext;

  /// Optional pre-selected categories (1=before_run, 2=during_run, 3=after_run)
  /// If null, uses categories from foodData or defaults to all selected
  final List<int>? preSelectedCategories;

  /// Whether to show category checkboxes (false for carb loading context)
  final bool showCategories;

  /// Whether to show product type dropdown
  final bool showProductType;

  /// Whether to show delete button (only for editExisting mode)
  final bool allowDelete;

  @override
  ConsumerState<FoodDetailScreen> createState() => _FoodDetailScreenState();
}

class _FoodDetailScreenState extends ConsumerState<FoodDetailScreen> {
  // Category selections
  late Map<int, bool> _selectedCategories;

  // Product type selection
  late String _selectedProductType;

  // Text controllers
  late TextEditingController _nameController;
  late TextEditingController _servingSizeController;
  late TextEditingController _servingAmountController;
  late TextEditingController _servingUnitController;
  late TextEditingController _caloriesController;
  late TextEditingController _carbsController;
  late TextEditingController _proteinController;
  late TextEditingController _fatController;
  late TextEditingController _sodiumController;
  late TextEditingController _fluidController;

  bool _hasChanges = false;

  // Prevent double-tap navigation crashes
  bool _isNavigating = false;

  // Prevent double-save
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();

    // Initialize category selections
    if (widget.preSelectedCategories != null) {
      _selectedCategories = {
        1: widget.preSelectedCategories!.contains(1),
        2: widget.preSelectedCategories!.contains(2),
        3: widget.preSelectedCategories!.contains(3),
      };
    } else if (widget.foodData.categoryIds.isNotEmpty) {
      _selectedCategories = {
        1: widget.foodData.categoryIds.contains(1),
        2: widget.foodData.categoryIds.contains(2),
        3: widget.foodData.categoryIds.contains(3),
      };
    } else {
      // Default: all checked for new foods
      _selectedCategories = {1: true, 2: true, 3: true};
    }

    // Initialize product type (normalize to valid dropdown values)
    _selectedProductType = normalizeProductTypeForDisplay(widget.foodData.productType);

    // Initialize text controllers
    // For createNew mode, leave nutrition fields empty instead of showing "0"
    final isCreateNew = widget.mode == FoodDetailMode.createNew;
    _nameController = TextEditingController(text: widget.foodData.name);
    _servingSizeController = TextEditingController(
      text: widget.foodData.servingSize ?? '',
    );
    _servingAmountController = TextEditingController(
      text: isCreateNew
          ? '1'
          : (widget.foodData.servingAmount?.toStringAsFixed(0) ?? '1'),
    );
    _servingUnitController = TextEditingController(
      text: widget.foodData.servingUnit ?? 'serving',
    );
    _caloriesController = TextEditingController(
      text: isCreateNew
          ? ''
          : (widget.foodData.caloriesPerServing ?? 0).toString(),
    );
    _carbsController = TextEditingController(
      text: isCreateNew
          ? ''
          : (widget.foodData.carbsPerServing ?? 0).toStringAsFixed(1),
    );
    _proteinController = TextEditingController(
      text: isCreateNew
          ? ''
          : (widget.foodData.proteinPerServing ?? 0).toStringAsFixed(1),
    );
    _fatController = TextEditingController(
      text: isCreateNew
          ? ''
          : (widget.foodData.fatPerServing ?? 0).toStringAsFixed(1),
    );
    _sodiumController = TextEditingController(
      text: isCreateNew ? '' : (widget.foodData.sodiumMg ?? 0).toString(),
    );
    _fluidController = TextEditingController(
      text: isCreateNew
          ? ''
          : (widget.foodData.fluidMlPerServing ?? 0).toStringAsFixed(0),
    );

    // Add listeners to track changes
    _nameController.addListener(_onFieldChanged);
    _servingSizeController.addListener(_onFieldChanged);
    _servingAmountController.addListener(_onFieldChanged);
    _servingUnitController.addListener(_onFieldChanged);
    _caloriesController.addListener(_onFieldChanged);
    _carbsController.addListener(_onFieldChanged);
    _proteinController.addListener(_onFieldChanged);
    _fatController.addListener(_onFieldChanged);
    _sodiumController.addListener(_onFieldChanged);
    _fluidController.addListener(_onFieldChanged);
  }

  void _onFieldChanged() {
    if (!_hasChanges) {
      setState(() {
        _hasChanges = true;
      });
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _servingSizeController.dispose();
    _servingAmountController.dispose();
    _servingUnitController.dispose();
    _caloriesController.dispose();
    _carbsController.dispose();
    _proteinController.dispose();
    _fatController.dispose();
    _sodiumController.dispose();
    _fluidController.dispose();
    super.dispose();
  }

  bool get _hasValidCategorySelection =>
      !widget.showCategories ||
      _selectedCategories.values.any((selected) => selected);

  bool get _hasValidName => _nameController.text.trim().isNotEmpty;

  bool get _isValid => _hasValidName && _hasValidCategorySelection;

  bool get _shouldShowFluidField {
    // Show if already has fluid value > 0
    if ((widget.foodData.fluidMlPerServing ?? 0) > 0) return true;
    // Show if product type is beverage-related
    return beverageProductTypes.contains(_selectedProductType);
  }

  String get _screenTitle {
    switch (widget.mode) {
      case FoodDetailMode.addFromScan:
        return 'Add Scanned Food';
      case FoodDetailMode.addFromSearch:
        return 'Add Food';
      case FoodDetailMode.editExisting:
        return 'Edit Food';
      case FoodDetailMode.createNew:
        return 'Create Custom Food';
    }
  }

  String get _primaryButtonText {
    if (widget.mode == FoodDetailMode.editExisting) {
      return 'Save Changes';
    }
    if (widget.mode == FoodDetailMode.createNew) {
      return 'Create Food';
    }
    switch (widget.screenContext) {
      case FoodDetailContext.onboarding:
        return 'Add to My Foods';
      case FoodDetailContext.swapFood:
        return 'Swap Food';
      case FoodDetailContext.carbLoading:
        return 'Add Food';
      case FoodDetailContext.foodPreferences:
      case FoodDetailContext.addFood:
        return 'Add Food';
    }
  }

  void _handleSave() {
    // Prevent double-save
    if (_isSaving) {
      debugPrint('⚠️ Double-save prevented!');
      return;
    }

    if (!_hasValidName) {
      MealvanaSnackbar.showError(context, 'Please enter a food name');
      return;
    }

    if (widget.showCategories && !_hasValidCategorySelection) {
      MealvanaSnackbar.showError(
        context,
        'Please select at least one category',
      );
      return;
    }

    _isSaving = true;

    // Get selected category IDs
    final selectedCategoryIds = widget.showCategories
        ? _selectedCategories.entries
              .where((entry) => entry.value)
              .map((entry) => entry.key)
              .toList()
        : <int>[];

    // Parse values
    final carbsValue = double.tryParse(_carbsController.text) ?? 0.0;

    final result = FoodDetailResult(
      foodId: widget.foodData.id,
      name: _nameController.text.trim(),
      servingSize: _servingSizeController.text.trim().isNotEmpty
          ? _servingSizeController.text.trim()
          : null,
      servingAmount: double.tryParse(_servingAmountController.text),
      servingUnit: _servingUnitController.text.trim().isNotEmpty
          ? _servingUnitController.text.trim()
          : null,
      caloriesPerServing: int.tryParse(_caloriesController.text) ?? 0,
      carbsPerServing: carbsValue,
      proteinPerServing: double.tryParse(_proteinController.text) ?? 0.0,
      fatPerServing: double.tryParse(_fatController.text) ?? 0.0,
      sodiumMg: int.tryParse(_sodiumController.text) ?? 0,
      fluidMlPerServing: _shouldShowFluidField
          ? double.tryParse(_fluidController.text)
          : null,
      productType: _selectedProductType,
      categoryIds: selectedCategoryIds,
    );

    debugPrint('💾 FoodDetailScreen saving with ${carbsValue}g carbs for food: ${widget.foodData.id}');

    // Pop with the result - the calling screen handles the result
    context.pop(result);
  }

  void _handleDelete() {
    if (!widget.allowDelete) return;

    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('Delete Food'),
        content: Text(
          'Are you sure you want to delete "${_nameController.text.trim()}"?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(dialogContext).pop(); // Close dialog
              // Pop with a special delete marker - using foodId prefixed with 'DELETE:'
              context.pop('DELETE:${widget.foodData.id}');
            },
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: Text(_screenTitle),
        leading: CustomAppBarBackButton(
          onPressed: () {
            if (_isNavigating) return;
            _isNavigating = true;
            context.pop();
          },
        ),
        actions: [
          if (widget.mode == FoodDetailMode.editExisting && widget.allowDelete)
            IconButton(
              onPressed: _handleDelete,
              icon: Icon(
                FontAwesomeIcons.trash,
                color: Colors.red.shade400,
                size: AppIconSizes.md,
              ),
              tooltip: 'Delete food',
            ),
        ],
      ),
      body: Column(
        children: [
          // Content
          Expanded(
            child: SingleChildScrollView(
              padding: AppSpacing.screenPadding,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Product image (for scanned foods)
                  if (widget.foodData.imageUrl != null &&
                      widget.mode == FoodDetailMode.addFromScan) ...[
                    Center(
                      child: ClipRRect(
                        borderRadius: AppRadius.cardRadius,
                        child: Image.network(
                          widget.foodData.imageUrl!,
                          height: 120,
                          width: 120,
                          fit: BoxFit.cover,
                          errorBuilder: (context, error, stackTrace) {
                            return Container(
                              height: 120,
                              width: 120,
                              decoration: BoxDecoration(
                                color: isDark
                                    ? AppColors.blackberry.withValues(
                                        alpha: 0.3,
                                      )
                                    : Colors.grey[200],
                                borderRadius: AppRadius.cardRadius,
                              ),
                              child: Icon(
                                FontAwesomeIcons.utensils,
                                size: 40,
                                color: Theme.of(
                                  context,
                                ).colorScheme.onSurfaceVariant,
                              ),
                            );
                          },
                        ),
                      ),
                    ),
                    const SizedBox(height: AppSpacing.lg),
                  ],

                  // Food name
                  _buildSectionTitle('Food Name'),
                  const SizedBox(height: AppSpacing.sm),
                  _buildTextField(
                    controller: _nameController,
                    hint: 'Enter food name',
                    isDark: isDark,
                  ),

                  const SizedBox(height: AppSpacing.lg),

                  // Serving info
                  _buildSectionTitle('Serving Size'),
                  const SizedBox(height: AppSpacing.sm),

                  // Serving size text (from barcode scan)
                  if (widget.mode == FoodDetailMode.addFromScan) ...[
                    _buildTextField(
                      controller: _servingSizeController,
                      hint: 'e.g., 1 packet (32g)',
                      isDark: isDark,
                    ),
                    const SizedBox(height: AppSpacing.sm),
                  ],

                  // Serving amount and unit
                  Row(
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Amount',
                              style: AppTextStyles.smallLabel.copyWith(
                                color: Theme.of(
                                  context,
                                ).colorScheme.onSurfaceVariant,
                              ),
                            ),
                            const SizedBox(height: AppSpacing.xs),
                            TextField(
                              controller: _servingAmountController,
                              keyboardType:
                                  const TextInputType.numberWithOptions(
                                    decimal: true,
                                  ),
                              inputFormatters: [
                                FilteringTextInputFormatter.allow(
                                  RegExp(r'^\d*\.?\d*'),
                                ),
                              ],
                              onChanged: (_) => _onFieldChanged(),
                              decoration: InputDecoration(
                                border: OutlineInputBorder(
                                  borderRadius: AppRadius.inputRadius,
                                  borderSide: BorderSide(
                                    color: isDark
                                        ? AppColors.cream.withValues(alpha: 0.3)
                                        : AppColors.blackberry.withValues(
                                            alpha: 0.3,
                                          ),
                                  ),
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderRadius: AppRadius.inputRadius,
                                  borderSide: BorderSide(
                                    color: isDark
                                        ? AppColors.cream.withValues(alpha: 0.3)
                                        : AppColors.blackberry.withValues(
                                            alpha: 0.3,
                                          ),
                                  ),
                                ),
                                focusedBorder: OutlineInputBorder(
                                  borderRadius: AppRadius.inputRadius,
                                  borderSide: const BorderSide(
                                    color: AppColors.electrolyte,
                                    width: 2,
                                  ),
                                ),
                                contentPadding: const EdgeInsets.symmetric(
                                  horizontal: AppSpacing.sm,
                                  vertical: AppSpacing.sm,
                                ),
                                isDense: true,
                                filled: true,
                                fillColor: Theme.of(
                                  context,
                                ).colorScheme.surface,
                              ),
                              style: AppTextStyles.bodyMedium.copyWith(
                                color: Theme.of(context).colorScheme.onSurface,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: AppSpacing.sm),
                      Expanded(
                        flex: 2,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Unit',
                              style: AppTextStyles.smallLabel.copyWith(
                                color: Theme.of(
                                  context,
                                ).colorScheme.onSurfaceVariant,
                              ),
                            ),
                            const SizedBox(height: AppSpacing.xs),
                            _buildTextField(
                              controller: _servingUnitController,
                              hint: 'e.g., serving, cup',
                              isDark: isDark,
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: AppSpacing.lg),

                  // Nutrition section
                  NutritionInputFields(
                    caloriesController: _caloriesController,
                    carbsController: _carbsController,
                    proteinController: _proteinController,
                    fatController: _fatController,
                    sodiumController: _sodiumController,
                    fluidController: _fluidController,
                    showFluidField: _shouldShowFluidField,
                    onFieldChanged: _onFieldChanged,
                  ),

                  // Category section
                  if (widget.showCategories) ...[
                    const SizedBox(height: AppSpacing.lg),
                    CategorySelector(
                      selectedCategories: _selectedCategories,
                      onCategoriesChanged: (updatedCategories) {
                        setState(() {
                          _selectedCategories = updatedCategories;
                          _hasChanges = true;
                        });
                      },
                    ),
                  ],

                  // Product type section
                  if (widget.showProductType) ...[
                    const SizedBox(height: AppSpacing.lg),
                    ProductTypeSelector(
                      selectedProductType: _selectedProductType,
                      onProductTypeChanged: (value) {
                        setState(() {
                          _selectedProductType = value;
                          _hasChanges = true;
                        });
                      },
                    ),
                  ],

                  const SizedBox(height: AppSpacing.xl),
                ],
              ),
            ),
          ),

          // Bottom action area
          Container(
            padding: const EdgeInsets.fromLTRB(
              AppSpacing.md,
              AppSpacing.md,
              AppSpacing.md,
              AppSpacing.xl,
            ),
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.surface,
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.1),
                  blurRadius: 8,
                  offset: const Offset(0, -2),
                ),
              ],
            ),
            child: KylePrimaryButton(
              onPressed: _isValid ? _handleSave : null,
              text: _primaryButtonText,
              isFullWidth: true,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: AppTextStyles.subtitle.copyWith(
        color: Theme.of(context).colorScheme.onSurface,
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    required bool isDark,
  }) {
    return TextField(
      controller: controller,
      decoration: InputDecoration(
        hintText: hint,
        border: OutlineInputBorder(
          borderRadius: AppRadius.inputRadius,
          borderSide: BorderSide(
            color: isDark
                ? AppColors.cream.withValues(alpha: 0.3)
                : AppColors.blackberry.withValues(alpha: 0.3),
          ),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: AppRadius.inputRadius,
          borderSide: BorderSide(
            color: isDark
                ? AppColors.cream.withValues(alpha: 0.3)
                : AppColors.blackberry.withValues(alpha: 0.3),
          ),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: AppRadius.inputRadius,
          borderSide: const BorderSide(color: AppColors.electrolyte, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.sm,
          vertical: AppSpacing.sm,
        ),
        isDense: true,
        filled: true,
        fillColor: Theme.of(context).colorScheme.surface,
      ),
      style: AppTextStyles.bodyMedium.copyWith(
        color: Theme.of(context).colorScheme.onSurface,
      ),
    );
  }
}
