import '../../../shared/domain/activity_type.dart';

/// Formats and normalizes auto-generated activity titles.
class ActivityTitleFormatter {
  static const double _epsilon = 1e-6;

  static String formatRunningTitle(double distanceMiles) {
    return '${formatMiles(distanceMiles)} mi Run';
  }

  static String formatCyclingTitle(double distanceMiles) {
    return '${formatMiles(distanceMiles)} mi Ride';
  }

  static String formatSwimmingTitle(int distanceMeters) {
    return '$distanceMeters m Swim';
  }

  /// Format miles with one decimal place, trimming trailing `.0`.
  ///
  /// Handles floating-point artifacts like `15.999999847191406` -> `16`.
  static String formatMiles(double miles) {
    if (!miles.isFinite) return miles.toString();

    final roundedFixed = double.parse(miles.toStringAsFixed(1));
    final asInt = roundedFixed.roundToDouble();
    if ((roundedFixed - asInt).abs() < _epsilon) {
      return asInt.toInt().toString();
    }
    return roundedFixed.toStringAsFixed(1);
  }

  /// Normalize known auto-generated title formats to stable display strings.
  ///
  /// Examples:
  /// - `15.999999847191406 mi Run` -> `16 mi Run`
  /// - `16.0 mi Ride` -> `16 mi Ride`
  static String normalizeAutoGeneratedTitle({
    required String title,
    required ActivityType activityType,
  }) {
    switch (activityType) {
      case ActivityType.running:
        final match = _runTitlePattern.firstMatch(title);
        if (match == null) return title;
        final distance = double.tryParse(match.group(1)!);
        if (distance == null) return title;
        return formatRunningTitle(distance);
      case ActivityType.cycling:
        final match = _rideTitlePattern.firstMatch(title);
        if (match == null) return title;
        final distance = double.tryParse(match.group(1)!);
        if (distance == null) return title;
        return formatCyclingTitle(distance);
      case ActivityType.swimming:
        final intMatch = _swimIntTitlePattern.firstMatch(title);
        if (intMatch != null) {
          final meters = int.tryParse(intMatch.group(1)!);
          if (meters != null) return formatSwimmingTitle(meters);
        }
        final decimalMatch = _swimDecimalTitlePattern.firstMatch(title);
        if (decimalMatch == null) return title;
        final meters = double.tryParse(decimalMatch.group(1)!);
        if (meters == null) return title;
        return formatSwimmingTitle(meters.round());
      default:
        return title;
    }
  }

  static final RegExp _runTitlePattern = RegExp(
    r'^\s*([+-]?\d+(?:\.\d+)?)\s*mi\s+run\s*$',
    caseSensitive: false,
  );
  static final RegExp _rideTitlePattern = RegExp(
    r'^\s*([+-]?\d+(?:\.\d+)?)\s*mi\s+ride\s*$',
    caseSensitive: false,
  );
  static final RegExp _swimIntTitlePattern = RegExp(
    r'^\s*(\d+)\s*m\s+swim\s*$',
    caseSensitive: false,
  );
  static final RegExp _swimDecimalTitlePattern = RegExp(
    r'^\s*([+-]?\d+(?:\.\d+)?)\s*m\s+swim\s*$',
    caseSensitive: false,
  );
}
