// GENERATED by split of macro_explanation_service.dart — DO NOT hand-edit
// Sodium transparency data builders

part of 'macro_explanation_service.dart';

extension _$SodiumExt on MacroExplanationService {
  Map<Scenario, NutrientTransparencyData> _singleSportSodiumMap({
    required MacroTargets macroTargets,
  }) {
    final during = macroTargets.duringRun;
    final durationMin = macroTargets.metrics.durationMin.round();
    final isTested = during.isTested;
    final shortWorkoutGate = durationMin < 60 &&
        (during.tempC == null || (during.tempC ?? 25) < 30);

    final map = <Scenario, NutrientTransparencyData>{};

    map[Scenario.singleSport] =
        _duringSingleSportSodiumTransparency(macroTargets: macroTargets);

    if (shortWorkoutGate) {
      map[Scenario.shortWorkout] =
          _shortWorkoutSodiumTransparency(macroTargets: macroTargets);
    }

    if (isTested) {
      map[Scenario.knownRate] =
          _knownRateSodiumTransparency(macroTargets: macroTargets);
    }

    return map;
  }

  Map<Scenario, NutrientTransparencyData> _brickSegmentSodiumMap({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
  }) {
    final isTested = segment.isTested;
    final hasRedistribution = [
      ...macroTargets.duringRun.safetyFlags,
      ...segment.safetyFlags,
    ].any((f) => f.toLowerCase().contains('redistri'));

    final map = <Scenario, NutrientTransparencyData>{};

    map[Scenario.multiSegment] = _brickSegmentSodiumTransparency(
      macroTargets: macroTargets,
      segment: segment,
    );

    if (hasRedistribution) {
      map[Scenario.redistribution] = _redistributionSodiumTransparency(
        macroTargets: macroTargets,
        segment: segment,
      );
    }

    if (isTested) {
      map[Scenario.knownRate] = _knownRateSodiumTransparency(
        macroTargets: macroTargets,
        forBrickSegment: segment,
      );
    }

    return map;
  }

  // ---------------------------------------------------------------------------
  // SODIUM — known-rate variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _knownRateSodiumTransparency({
    required MacroTargets macroTargets,
    BrickSegmentMacroTarget? forBrickSegment,
  }) {
    final during = macroTargets.duringRun;
    final durationH = forBrickSegment != null
        ? forBrickSegment.durationMinutes / 60.0
        : macroTargets.metrics.durationH;
    final sodiumTotalMg = forBrickSegment != null
        ? forBrickSegment.sodiumMg.round()
        : during.sodiumTotalMg.round();
    final waterMl = forBrickSegment != null
        ? forBrickSegment.waterMl.round()
        : during.fluidTotalMl.round();
    final sodiumConc =
        forBrickSegment?.sodiumConcMgPerL ?? during.sodiumConcMgPerL;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final sodiumRateMgH =
        durationH > 0 ? (sodiumTotalMg / durationH).round() : 0;
    final sodiumLow = forBrickSegment?.sodiumLowMg ?? during.sodiumLowMg;
    final sodiumHigh = forBrickSegment?.sodiumHighMg ?? during.sodiumHighMg;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fAccent('fluid rate '),
          fDim('$fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('TESTED conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumTotalMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('TESTED $sodiumRateMgH mg/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumTotalMg}mg'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: true,
      tldrBody: 'Your sodium target uses your **personal tested concentration** '
          '\u2014 the most accurate input available. This number was entered from '
          'your sweat test and overrides the Low/Average/High category lookup.',
      tldrLines: tldrLines,
      storySections: [
        const StorySection(
          question: 'How was the known concentration applied?',
          answer:
              'Instead of the Low (650 mg/L) / Average (825 mg/L) / High (1000 mg/L) '
              'lookup, your actual tested concentration was used directly in the '
              'formula: sodium = (fluid_ml_hr / 1000) \u00d7 tested_conc.',
          citation: 'Baker (2016) \u2014 Sports Medicine, n=506',
          dataChips: ['TESTED \u2713 \u00b7 personal concentration'],
        ),
        const StorySection(
          question: 'How do I update my tested concentration?',
          answer:
              'Go to Settings \u2192 Sweat Profile to enter or update your known '
              'sodium concentration. Re-test or re-enter after heat acclimatisation '
              'or major dietary changes. Individual sodium concentration is largely '
              'genetic and stable long-term.',
          inlineEditType: InlineEditType.knownSodiumConcentration,
          dataChips: ['TESTED \u2713 \u00b7 overrides category'],
        ),
      ],
      videoTitle: 'Watch: Sodium & Electrolytes',
      targetGrams: sodiumTotalMg.toDouble(),
      rangeLow: sodiumLow,
      rangeHigh: sodiumHigh,
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // SODIUM — short workout gate variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _shortWorkoutSodiumTransparency({
    required MacroTargets macroTargets,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final sodiumRateMgH = during.sodiumRateMgPerH.round();
    final sodiumTotalMg = during.sodiumTotalMg.round();

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: during.isTested,
      tldrBody: 'This workout is short and mild \u2014 no structured sodium plan '
          'needed. A sports drink or salted snack is plenty. The number shown '
          'is a conservative maximum, not a target.',
      tldrLines: [
        FormulaLine([
          fAccent('short gate '),
          fOp('\u2192 '),
          fDim('no structured sodium plan'),
        ]),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumTotalMg}mg'),
            fDim(' (conservative max)'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ],
      storySections: [
        const StorySection(
          question: 'Do I need sodium for a short workout?',
          answer:
              'For workouts under 60 minutes in mild conditions, sodium replacement '
              'is generally not critical. Your body\'s sodium reserves are sufficient '
              'to cover a short effort without structured supplementation. Drink a '
              'sports drink or eat something salty post-workout.',
          citation: 'Noakes (2012) \u2014 Hyponatremia in endurance sports',
          dataChips: ['Short gate \u00b7 < 60 min + temp < 30\u00b0C'],
        ),
      ],
      videoTitle: 'Watch: Sodium & Electrolytes',
      targetGrams: sodiumTotalMg.toDouble(),
      rangeLow: during.sodiumLowMg,
      rangeHigh: during.sodiumHighMg,
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // SODIUM — redistribution variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _redistributionSodiumTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
  }) {
    final durationH = segment.durationMinutes / 60.0;
    final sodiumMg = segment.sodiumMg.round();
    final waterMl = segment.waterMl.round();
    final sodiumConc = segment.sodiumConcMgPerL;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final sodiumRateMgH = durationH > 0 ? (sodiumMg / durationH).round() : 0;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fOp('# '),
          fAccent('redistributed fluid '),
          fDim('$fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fOp('# '),
          fAccent('$sodiumRateMgH mg/hr (redistributed) '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: segment.isTested,
      tldrBody:
          'Your sodium target is a simple multiplication of your fluid intake '
          'rate by your sweat sodium concentration. Dial in your test results '
          'if you have one.',
      tldrLines: tldrLines,
      storySections: _duringSodiumStorySections(
        sodiumConc: sodiumConc,
        isTested: segment.isTested,
      ),
      videoTitle: 'Watch: Sodium & Electrolytes',
      targetGrams: sodiumMg.toDouble(),
      rangeLow: segment.sodiumLowMg,
      rangeHigh: segment.sodiumHighMg,
      sportLabel: segment.sport,
    );
  }

  // ---------------------------------------------------------------------------
  // PRE-WORKOUT SODIUM
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _preWorkoutSodiumTransparency({
    required MacroTargets macroTargets,
  }) {
    final pre = macroTargets.preRun;
    final sodiumMg = pre.sodiumMg.round();
    final rangeLowMg = pre.sodiumLowMg?.round() ?? (sodiumMg * 0.8).round();
    final rangeHighMg =
        pre.sodiumHighMg?.round() ?? (sodiumMg * 1.2).round();

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42), // orange
      primaryUnit: 'mg',
      phase: 'before',
      tldrBody:
          'Pre-workout sodium keeps the fluid you drink in your body rather '
          'than sending it straight to your bladder. Without sodium, much of '
          'what you consume before exercise is excreted before you even start.',
      tldrLines: [
        FormulaLine([
          fAccent('tier target '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ]),
      ],
      calculationSections: _buildPreWorkoutSodiumCalculationSections(
        sodiumMg: sodiumMg,
        sodiumLowMg: rangeLowMg,
        sodiumHighMg: rangeHighMg,
      ),
      storySections: const [
        StorySection(
          question: 'Why sodium before a workout?',
          answer:
              'Sodium is the primary solute in the fluid compartments outside your '
              'cells. When you consume sodium before exercise, it draws fluid into '
              'your blood vessels and extracellular space \u2014 expanding plasma volume '
              'and improving your cardiovascular efficiency from the first minute.',
          citation:
              'Maughan & Shirreffs (2008) \u2014 European Journal of Sport Science',
          dataChips: ['Tier 1 (\u2265120 min) \u00b7 450 mg', 'Tier 2 (10\u2013120 min) \u00b7 150 mg', 'Tier 3 (<10 min) \u00b7 0 mg'],
        ),
        StorySection(
          question: 'Why doesn\'t it vary with sweat sodium level?',
          answer:
              'Pre-workout sodium targets are fixed by timing tier, not sweat '
              'profile. The goal is fluid retention, and the research gives clean '
              'targets: **300\u2013600 mg** for 2+ hours out (ACSM), and a '
              'top-up amount for closer windows.',
          citation:
              'Sawka et al. (2007) \u2014 ACSM Position Stand on Fluid Replacement; '
              'NATA 10\u2013120 min guidance',
        ),
      ],
      targetGrams: sodiumMg.toDouble(),
      rangeLow: rangeLowMg.toDouble(),
      rangeHigh: rangeHighMg.toDouble(),
      sportLabel: 'Pre-Workout',
    );
  }

  // ---------------------------------------------------------------------------
  // DURING SINGLE SPORT SODIUM
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _duringSingleSportSodiumTransparency({
    required MacroTargets macroTargets,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final sodiumRateMgH = during.sodiumRateMgPerH.round();
    final sodiumTotalMg = during.sodiumTotalMg.round();
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final sodiumConc = during.sodiumConcMgPerL;
    final isTested = during.isTested;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      // New derivation: sodium = (fluid / 1000) × conc
      tldrLines = [
        FormulaLine([
          fAccent('fluid rate '),
          fDim('$fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumTotalMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      // Legacy fallback
      tldrLines = [
        FormulaLine([
          fAccent('$sodiumRateMgH mg/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumTotalMg}mg'),
        ], isResultLine: true),
      ];
    }

    final sodiumCalcSections = _buildDuringSodiumCalculationSections(
      during: during,
      durationH: durationH,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody:
          'Your sodium target is a simple multiplication of your fluid intake '
          'rate by your sweat sodium concentration. Dial in your test results '
          'if you have one.',
      tldrLines: tldrLines,
      calculationSections: sodiumCalcSections,
      storySections: _duringSodiumStorySections(
        sodiumConc: sodiumConc,
        isTested: isTested,
      ),
      videoTitle: 'Watch: Sodium & Electrolytes',
      targetGrams: sodiumTotalMg.toDouble(),
      rangeLow: during.sodiumLowMg,
      rangeHigh: during.sodiumHighMg,
      sportLabel: null,
    );
  }

  List<StorySection> _duringSodiumStorySections({
    int? sodiumConc,
    required bool isTested,
  }) {
    return [
      const StorySection(
        question: 'Why is sodium tied to fluid intake?',
        answer:
            'Sweat contains both water and dissolved sodium. To maintain blood '
            'sodium concentration, you need to replace sodium in proportion to '
            'the fluid you drink. If you drink without sodium, your blood sodium '
            'drops \u2014 a risk factor for **hyponatremia** in longer events.',
        citation: 'Baker (2017) \u2014 JISSN; Hew-Butler et al. (2015) \u2014 Clinical Journal of Sport Medicine',
      ),
      StorySection(
        question: 'What\'s my sweat sodium concentration?',
        answer: isTested
            ? 'Your sodium target uses your **personal tested concentration** '
                '\u2014 the most accurate input. Individual sodium concentration '
                'varies widely (200\u20132000 mg/L). White salt stains on clothing '
                'and salty-tasting sweat are qualitative signals of higher losses.'
            : 'Sodium concentration is estimated from your sweat sodium category. '
                'For a precise number, consider a lab patch test (Gatorade Gx, LEVELEN, '
                'or PF&H sweat test). You can enter your result below.',
        citation: 'Baker (2016) \u2014 Sports Medicine, n=506; mean 826 \u00b1 239 mg/L',
        inlineEditType: InlineEditType.knownSodiumConcentration,
        dataChips: isTested
            ? ['TESTED \u2713 \u00b7 personal concentration']
            : [
                'Low \u00b7 650 mg/L',
                'Average \u00b7 825 mg/L',
                'High \u00b7 1000 mg/L',
              ],
      ),
      const StorySection(
        question: 'Why not replace 100% of sodium losses?',
        answer:
            'The body has significant sodium reserves and regulatory mechanisms '
            'that don\'t require precise replacement during exercise. The goal is '
            'to maintain blood sodium in a safe range, not to perfectly match '
            'sweat losses. 100% replacement also risks hypertonic intake '
            'in some athletes.',
        citation: 'Shirreffs & Sawka (2011) \u2014 Journal of Sports Sciences',
        dataChips: ['Typical replacement \u00b7 derived from fluid \u00d7 conc'],
      ),
    ];
  }

  // ---------------------------------------------------------------------------
  // BRICK SEGMENT SODIUM
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickSegmentSodiumTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
  }) {
    final durationH = segment.durationMinutes / 60.0;
    final sodiumMg = segment.sodiumMg.round();
    final waterMl = segment.waterMl.round();
    final sodiumConc = segment.sodiumConcMgPerL;
    final isTested = segment.isTested;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final sodiumRateMgH = durationH > 0 ? (sodiumMg / durationH).round() : 0;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fAccent('fluid rate '),
          fDim('$fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('$sodiumRateMgH mg/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody:
          'Your sodium target is a simple multiplication of your fluid intake '
          'rate by your sweat sodium concentration. Dial in your test results '
          'if you have one.',
      tldrLines: tldrLines,
      calculationSections: sodiumConc != null
          ? _buildBrickSegmentSodiumCalculationSections(
              segment: segment,
              concMgPerL: sodiumConc,
            )
          : const [],
      storySections: _duringSodiumStorySections(
        sodiumConc: sodiumConc,
        isTested: isTested,
      ),
      videoTitle: 'Watch: Sodium & Electrolytes',
      targetGrams: sodiumMg.toDouble(),
      rangeLow: segment.sodiumLowMg,
      rangeHigh: segment.sodiumHighMg,
      sportLabel: segment.sport,
    );
  }

  // ---------------------------------------------------------------------------
  // SWIM SODIUM — zero state
  // ---------------------------------------------------------------------------

  /// Public accessor so the sheet can request the swim zero-state directly.
  NutrientTransparencyData _swimSodiumTransparency() {
    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      tldrBody:
          'No sodium intake during swim \u2014 T1 covers the transition need. '
          'Sodium losses during swimming are lower than land sports due to the '
          '0.4\u00d7 sweat modifier applied to the swim segment.',
      tldrLines: const [],
      storySections: const [
        StorySection(
          question: 'Why no sodium during swim?',
          answer:
              'You cannot drink during an open-water or pool swim. Sodium losses '
              'during swimming are also approximately 40% of equivalent land-sport '
              'losses due to passive water cooling reducing the sweat drive. '
              'The T1 transition provides the sodium bolus to bridge the gap '
              'before the bike leg.',
          dataChips: ['Swim sodium modifier \u00b7 0.4\u00d7 land sports'],
        ),
      ],
      isSwimZero: true,
      swimCallout: 'Sodium covered by: T1 transition \u00b7 Bike segment',
      targetGrams: 0,
      rangeLow: 0,
      rangeHigh: 0,
      sportLabel: 'Swim',
    );
  }

  // ---------------------------------------------------------------------------
  // TRANSITION SODIUM
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _transitionSodiumTransparency({
    required ExplanationPhase phase,
    required MacroTargets macroTargets,
  }) {
    final isT1 = phase == ExplanationPhase.transition1;
    final transitionName = isT1 ? 'T1' : 'T2';

    final transitions = macroTargets.brickPhaseTargets?.transitions;
    final tIdx = isT1 ? 0 : 1;
    final transition = (transitions != null && tIdx < transitions.length)
        ? transitions[tIdx]
        : null;
    final sodiumMg = transition?.sodiumMg.round() ?? 90;
    final sodiumConc = transition?.sodiumConcMgPerL;
    final isTested = transition?.isTested ?? false;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fAccent('300 mL '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('\u00f7 '),
          fAccent('1000 '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ]),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('$transitionName fixed '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ]),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg',
      phase: 'transition',
      isTested: isTested,
      tldrBody:
          'Transition sodium rides on the fixed 300 mL fluid bolus at your '
          'sweat sodium concentration. It matches the sweat [Na+] in whatever '
          'you drink during the brief stop \u2014 no extra factor applied.',
      tldrLines: tldrLines,
      calculationSections: sodiumConc != null
          ? _buildTransitionSodiumCalculationSections(
              waterMl: transition?.waterMl.round() ?? 300,
              concMgPerL: sodiumConc,
            )
          : const [],
      storySections: [
        StorySection(
          question: 'How is T1/T2 sodium calculated?',
          answer:
              'It\'s the fixed 300 mL transition bolus multiplied by your sweat '
              'sodium concentration (e.g. 300 mL \u00d7 825 mg/L = 248 mg at AVERAGE). '
              'Sodium rides on fluid \u2014 the bike and run legs carry the per-hour '
              'replacement across their full durations.',
          dataChips: ['T1/T2 sodium \u00b7 (300 / 1000) \u00d7 conc'],
        ),
      ],
      targetGrams: sodiumMg.toDouble(),
      rangeLow: transition?.sodiumLowMg,
      rangeHigh: transition?.sodiumHighMg,
      sportLabel: transitionName,
    );
  }

  // ===========================================================================
  // CARB TRANSPARENCY
  // ===========================================================================

  /// Build structured transparency data for the carbs card.
  ///
  /// Handles: pre-workout, during single-sport, during brick segment, swim.
}
