// GENERATED by split of macro_explanation_service.dart — DO NOT hand-edit
// Sodium transparency data builders

part of 'macro_explanation_service.dart';

extension _$SodiumExt on MacroExplanationService {
  Map<Scenario, NutrientTransparencyData> _singleSportSodiumMap({
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationMin = macroTargets.metrics.durationMin.round();
    final isTested = during.isTested;
    final shortWorkoutGate =
        durationMin < 60 && (during.tempC == null || (during.tempC ?? 25) < 30);

    final map = <Scenario, NutrientTransparencyData>{};

    map[Scenario.singleSport] = _duringSingleSportSodiumTransparency(
      macroTargets: macroTargets,
      useImperial: useImperial,
    );

    if (shortWorkoutGate) {
      map[Scenario.shortWorkout] = _shortWorkoutSodiumTransparency(
        macroTargets: macroTargets,
      );
    }

    if (isTested) {
      map[Scenario.knownRate] = _knownRateSodiumTransparency(
        macroTargets: macroTargets,
        useImperial: useImperial,
      );
    }

    return map;
  }

  Map<Scenario, NutrientTransparencyData> _brickSegmentSodiumMap({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    bool useImperial = false,
  }) {
    final isTested = segment.isTested;
    final hasRedistribution = [
      ...macroTargets.duringRun.safetyFlags,
      ...segment.safetyFlags,
    ].any((f) => f.toLowerCase().contains('redistri'));

    final map = <Scenario, NutrientTransparencyData>{};

    map[Scenario.multiSegment] = _brickSegmentSodiumTransparency(
      macroTargets: macroTargets,
      segment: segment,
      useImperial: useImperial,
    );

    if (hasRedistribution) {
      map[Scenario.redistribution] = _redistributionSodiumTransparency(
        macroTargets: macroTargets,
        segment: segment,
        useImperial: useImperial,
      );
    }

    if (isTested) {
      map[Scenario.knownRate] = _knownRateSodiumTransparency(
        macroTargets: macroTargets,
        forBrickSegment: segment,
        useImperial: useImperial,
      );
    }

    return map;
  }

  // ---------------------------------------------------------------------------
  // SODIUM — known-rate variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _knownRateSodiumTransparency({
    required MacroTargets macroTargets,
    BrickSegmentMacroTarget? forBrickSegment,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationH = forBrickSegment != null
        ? forBrickSegment.durationMinutes / 60.0
        : macroTargets.metrics.durationH;
    final sodiumTotalMg = forBrickSegment != null
        ? forBrickSegment.sodiumMg.round()
        : during.sodiumTotalMg.round();
    final waterMl = forBrickSegment != null
        ? forBrickSegment.waterMl.round()
        : during.fluidTotalMl.round();
    final sodiumConc =
        forBrickSegment?.sodiumConcMgPerL ?? during.sodiumConcMgPerL;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final sodiumRateMgH = durationH > 0
        ? (sodiumTotalMg / durationH).round()
        : 0;
    final sodiumLow = forBrickSegment?.sodiumLowMg ?? during.sodiumLowMg;
    final sodiumHigh = forBrickSegment?.sodiumHighMg ?? during.sodiumHighMg;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fAccent('fluid rate '),
          fDim('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent('TESTED conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumTotalMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('TESTED $sodiumRateMgH mg/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumTotalMg}mg'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: true,
      tldrBody:
          'Your sodium target uses your **personal tested concentration** '
          '\u2014 the most accurate input available. This number was entered from '
          'your sweat test and overrides the Low/Average/High category lookup.',
      tldrLines: tldrLines,
      storySections: [
        const StorySection(
          question: 'How was the known concentration applied?',
          answer:
              'Instead of the Low (650 mg/L) / Average (825 mg/L) / High (1000 mg/L) '
              'lookup, your actual tested concentration was used directly in the '
              'formula: sodium = (fluid_ml_hr / 1000) \u00d7 tested_conc.',
          citation: 'Baker (2016) \u2014 Sports Medicine, n=506',
          dataChips: ['TESTED \u2713 \u00b7 personal concentration'],
        ),
        const StorySection(
          question: 'How do I update my tested concentration?',
          answer:
              'Go to Settings \u2192 Sweat Profile to enter or update your known '
              'sodium concentration. Re-test or re-enter after heat acclimatisation '
              'or major dietary changes. Individual sodium concentration is largely '
              'genetic and stable long-term.',
          inlineEditType: InlineEditType.knownSodiumConcentration,
          dataChips: ['TESTED \u2713 \u00b7 overrides category'],
        ),
      ],
      videoTitle: 'Watch: Sodium & Endurance',
      targetGrams: sodiumTotalMg.toDouble(),
      rangeLow: sodiumLow,
      rangeHigh: sodiumHigh,
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // SODIUM — short workout gate variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _shortWorkoutSodiumTransparency({
    required MacroTargets macroTargets,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final sodiumRateMgH = during.sodiumRateMgPerH.round();
    final sodiumTotalMg = during.sodiumTotalMg.round();

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: during.isTested,
      tldrBody:
          'This workout is short and mild \u2014 no structured sodium plan '
          'needed. A sports drink or salted snack is plenty. The number shown '
          'is a conservative maximum, not a target.',
      tldrLines: [
        FormulaLine([
          fAccent('short gate '),
          fOp('\u2192 '),
          fDim('no structured sodium plan'),
        ]),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumTotalMg}mg'),
            fDim(' (conservative max)'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ],
      storySections: [
        const StorySection(
          question: 'Do I need sodium for a short workout?',
          answer:
              'For workouts under 60 minutes in mild conditions, sodium replacement '
              'is generally not critical. Your body\'s sodium reserves are sufficient '
              'to cover a short effort without structured supplementation. Drink a '
              'sports drink or eat something salty post-workout.',
          citation: 'Noakes (2012) \u2014 Hyponatremia in endurance sports',
          dataChips: ['Short gate \u00b7 < 60 min + temp < 30\u00b0C'],
        ),
      ],
      videoTitle: 'Watch: Sodium & Endurance',
      targetGrams: sodiumTotalMg.toDouble(),
      rangeLow: during.sodiumLowMg,
      rangeHigh: during.sodiumHighMg,
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // SODIUM — redistribution variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _redistributionSodiumTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    bool useImperial = false,
  }) {
    final durationH = segment.durationMinutes / 60.0;
    final sodiumMg = segment.sodiumMg.round();
    final waterMl = segment.waterMl.round();
    final sodiumConc = segment.sodiumConcMgPerL;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final sodiumRateMgH = durationH > 0 ? (sodiumMg / durationH).round() : 0;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fOp('# '),
          fAccent('redistributed fluid '),
          fDim('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fOp('# '),
          fAccent('$sodiumRateMgH mg/hr (redistributed) '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: segment.isTested,
      tldrBody:
          'Your sodium target is a simple multiplication of your fluid intake '
          'rate by your sweat sodium concentration. Dial in your test results '
          'if you have one.',
      tldrLines: tldrLines,
      storySections: _duringSodiumStorySections(
        sodiumConc: sodiumConc,
        isTested: segment.isTested,
      ),
      videoTitle: 'Watch: Sodium & Endurance',
      targetGrams: sodiumMg.toDouble(),
      rangeLow: segment.sodiumLowMg,
      rangeHigh: segment.sodiumHighMg,
      sportLabel: segment.sport,
    );
  }

  // ---------------------------------------------------------------------------
  // PRE-WORKOUT SODIUM
  // ---------------------------------------------------------------------------

  /// Pre-workout sodium — **sodium v3**.
  ///
  /// Mealvana sets no pre-workout sodium target. This is a deliberate
  /// decision, not an omission: the retired v1 target (450 mg [300–600])
  /// rested solely on ACSM's 20–50 mEq/L, which at that dose only held for
  /// athletes between roughly 65 kg and 163 kg — it silently
  /// over-concentrated every athlete under ~65 kg. Real pre-workout food
  /// overshoots any plausible band anyway (a bagel with peanut butter is
  /// ~737 mg), so the band flagged ordinary food as defective.
  ///
  /// What survives is the **delivered** figure — an observation, not a
  /// target — and the qualitative copy, which must **not** be quantified: the
  /// retention studies used 77 mmol/L, three to seven times a sports drink.
  ///
  /// So: no `targetGrams`, no `rangeLow`/`rangeHigh`, no formula lines.
  /// See `docs/ssot/PRE-WORKOUT-BUNDLE-DIGEST.md` §3.
  NutrientTransparencyData _preWorkoutSodiumTransparency({
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final pre = macroTargets.preRun;

    // Three states that must never read alike (digest §5): the hydration gate
    // fired (short + mild session — we set nothing), the athlete is fasted (no
    // recommendation is being made at all), or the ordinary case where sodium
    // simply isn't something we set a number for.
    final String tldrBody;
    if (pre.isHydrationGated) {
      tldrBody =
          'This session is short and mild, so there\'s no pre-workout '
          'hydration plan — and no sodium plan either. Eat and drink normally '
          'beforehand.';
    } else if (pre.isCarbRecommendationAbsent) {
      tldrBody =
          'You\'ve chosen to train fasted, so we\'re not recommending anything '
          'before this session — including sodium.';
    } else {
      tldrBody =
          'We don\'t set a pre-workout sodium target. A salty snack or an '
          'electrolyte drink alongside your pre-workout fluid helps that fluid '
          'stay in, but there isn\'t good evidence for a specific number '
          'beforehand — and everyday pre-workout food already carries plenty. '
          'Whatever figure you see here is what your food delivers, not '
          'something to hit.';
    }

    // No formula: there is no calculation. Sodium v3 is the absence of one.
    const List<FormulaLine> tldrLines = [];

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42), // orange
      primaryUnit: 'mg',
      phase: 'before',
      tldrBody: tldrBody,
      tldrLines: tldrLines,
      // No calculation sections: there is no pre-workout sodium calculation.
      calculationSections: const [],
      storySections: const [
        StorySection(
          question: 'Why is there no pre-workout sodium target?',
          answer:
              'We used to set one — 450 mg, with a 300–600 mg range — and we '
              'removed it rather than re-derive it. It rested on a single '
              'concentration guideline, and at that dose the guideline only '
              'actually held for athletes between about 65 kg and 163 kg; '
              'everyone lighter was being told to drink a more concentrated '
              'mix than the source supports. Ordinary pre-workout food also '
              'clears any plausible band on its own — a bagel with peanut '
              'butter is roughly 737 mg — so the band mostly served to flag '
              'normal food as a mistake. Sodium individualisation now lives '
              'entirely in the during-workout plan, where it is fitted to your '
              'own sweat.',
          citation:
              'Sawka et al. (2007) — ACSM Position Stand; Baker et al. (2016)',
          confidence: ConfidenceLevel.high,
        ),
        StorySection(
          question: 'Does sodium still help before a workout?',
          answer:
              'Yes — sodium alongside your pre-workout fluid helps that fluid '
              'stay in your body rather than being excreted before you start. '
              'A salty snack or an electrolyte drink with your pre-workout '
              'fluid is a sound habit. What we won\'t do is put a number on '
              'it: the studies showing the retention effect used '
              'concentrations several times stronger than any sports drink, so '
              'they don\'t translate into a target you could aim at.',
          citation:
              'Maughan & Shirreffs (2016); Sawka et al. (2007) — ACSM Position Stand',
          confidence: ConfidenceLevel.medium,
        ),
        StorySection(
          question: 'Then what is the sodium number on this screen?',
          answer:
              'It\'s an observation, not a goal — simply the sodium contained '
              'in the food and drink chosen for this phase. There\'s no range, '
              'no marker and no "in range" state, because there\'s nothing to '
              'be in range of. It\'s there so nothing is hidden from you, not '
              'so you can hit it.',
          confidence: ConfidenceLevel.high,
        ),
      ],
      // Sodium v3: no target and no band. Leaving all three null is what stops
      // the transparency sheet rendering a target badge or a range chip.
      targetGrams: null,
      rangeLow: null,
      rangeHigh: null,
      sportLabel: 'Pre-Workout',
    );
  }

  // ---------------------------------------------------------------------------
  // DURING SINGLE SPORT SODIUM
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _duringSingleSportSodiumTransparency({
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final sodiumRateMgH = during.sodiumRateMgPerH.round();
    final sodiumTotalMg = during.sodiumTotalMg.round();
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final sodiumConc = during.sodiumConcMgPerL;
    final isTested = during.isTested;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      // New derivation: sodium = (fluid / 1000) × conc
      tldrLines = [
        FormulaLine([
          fAccent('fluid rate '),
          fDim('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumTotalMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      // Legacy fallback
      tldrLines = [
        FormulaLine([
          fAccent('$sodiumRateMgH mg/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumTotalMg}mg'),
        ], isResultLine: true),
      ];
    }

    final sodiumCalcSections = _buildDuringSodiumCalculationSections(
      during: during,
      durationH: durationH,
      useImperial: useImperial,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody:
          'Your sodium target is a simple multiplication of your fluid intake '
          'rate by your sweat sodium concentration. Dial in your test results '
          'if you have one.',
      tldrLines: tldrLines,
      calculationSections: sodiumCalcSections,
      storySections: _duringSodiumStorySections(
        sodiumConc: sodiumConc,
        isTested: isTested,
      ),
      videoTitle: 'Watch: Sodium & Endurance',
      targetGrams: sodiumTotalMg.toDouble(),
      rangeLow: during.sodiumLowMg,
      rangeHigh: during.sodiumHighMg,
      sportLabel: null,
    );
  }

  List<StorySection> _duringSodiumStorySections({
    int? sodiumConc,
    required bool isTested,
  }) {
    return [
      const StorySection(
        question: 'Why does sweat sodium concentration matter?',
        answer:
            'Sweat sodium concentration varies roughly 10\u00d7 across athletes '
            '(200\u20132000 mg/L), largely driven by genetics and heat adaptation. '
            'Replacing sodium in proportion to your actual losses is the core of '
            'preventing both hyponatremia and cramping.',
        citation:
            'Baker (2016) \u2014 Sports Medicine, n=506; mean 826 \u00b1 239 mg/L',
        dataChips: [
          'Low \u00b7 650 mg/L \u00b7 25th pct',
          'Average \u00b7 825 mg/L \u00b7 50th pct',
          'High \u00b7 1000 mg/L \u00b7 75th pct',
        ],
        confidence: ConfidenceLevel.high,
      ),
      // C24 \u2014 salt-type self-classification indicators
      const StorySection(
        question: 'How do I know which type I am?',
        answer:
            'Without a lab test, look for these qualitative indicators:\n\n'
            '\u2022 **White salt residue** on your skin or clothes after exercise\n'
            '\u2022 **Eyes sting** from sweat running into them\n'
            '\u2022 **Strong craving for salty food** after long efforts\n'
            '\u2022 **Sweat tastes noticeably salty**\n\n'
            'None of the above \u2192 you\'re likely Low or Average. Multiple '
            'indicators \u2192 likely High. A lab patch test (PF&H, Gatorade Gx, '
            'LEVELEN) gives a precise number.',
        citation: 'Baker (2017) \u2014 JISSN qualitative indicators',
        confidence: ConfidenceLevel.medium,
      ),
      StorySection(
        question: 'What\'s my sweat sodium concentration?',
        answer: isTested
            ? 'Your sodium target uses your **personal tested concentration** '
                  '\u2014 the most accurate input. Individual sodium concentration '
                  'varies widely (200\u20132000 mg/L). White salt stains on '
                  'clothing and salty-tasting sweat are qualitative signals of '
                  'higher losses.'
            : 'Sodium concentration is estimated from your sweat sodium category. '
                  'For a precise number, consider a lab patch test (Gatorade Gx, '
                  'LEVELEN, or PF&H sweat test). You can enter your result below.',
        citation:
            'Baker (2016) \u2014 Sports Medicine, n=506; mean 826 \u00b1 239 mg/L',
        inlineEditType: InlineEditType.knownSodiumConcentration,
        dataChips: isTested
            ? ['TESTED \u2713 \u00b7 personal concentration']
            : [
                'Low \u00b7 650 mg/L \u00b7 25th pct',
                'Average \u00b7 825 mg/L \u00b7 50th pct',
                'High \u00b7 1000 mg/L \u00b7 75th pct',
              ],
        confidence: ConfidenceLevel.high,
      ),
      // C25 \u2014 standard sports drink comparison (spec's most actionable Q)
      const StorySection(
        question: 'Why isn\'t a standard sports drink enough?',
        answer:
            'A standard sports drink delivers roughly 450 mg/L sodium \u2014 '
            'about half the 825 mg/L average sweat concentration. At a '
            'typical during-workout rate of 645 mL/hr, that\'s only ~290 mg/hr '
            'of sodium, covering roughly **54% of the target** for an '
            'average-salt athlete. High-sodium drink mixes (\u2248825 mg/L) or '
            'supplementing with an electrolyte tablet or salt capsule closes '
            'the gap.',
        citation: 'Commercial product comparison at 645 mL/hr reference rate',
        dataChips: [
          'Standard drink \u00b7 ~450 mg/L \u00b7 ~54% target',
          'High-sodium mix \u00b7 ~825 mg/L \u00b7 100% target',
          'Electrolyte tablet \u00b7 +300\u2013400 mg',
          'Salt capsule \u00b7 +215 mg each',
        ],
      ),
      // C26 \u2014 range-derivation Q with MEDIUM transparency note
      const StorySection(
        question: 'Where does the mg/hr range come from?',
        answer:
            'Your sodium range is inherited from the Fluids section. The floor '
            'comes from the 2% BW floor \u00d7 your sodium concentration; the '
            'ceiling comes from the GI cap \u00d7 your sodium concentration. '
            'Sodium automatically follows whatever fluid rate the plan uses.',
        citation:
            'Tiller et al. (2019) \u2014 ISSN ultra guidelines; Mosler (2020) \u2014 DGE',
        dataChips: [
          'Floor \u00b7 fluid floor \u00d7 Na conc',
          'Ceiling \u00b7 fluid ceiling \u00d7 Na conc',
        ],
        transparencyNote:
            'The principle of replacing 100% of sodium in consumed fluid is '
            'supported by ISSN ultra guidelines (Tiller 2019) and DGE position '
            'stand (Mosler 2020), but rated Medium confidence \u2014 the '
            'evidence is stronger for the direction than for the exact '
            'percentage.',
        confidence: ConfidenceLevel.medium,
      ),
    ];
  }

  // ---------------------------------------------------------------------------
  // BRICK SEGMENT SODIUM
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickSegmentSodiumTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    bool useImperial = false,
  }) {
    final durationH = segment.durationMinutes / 60.0;
    final sodiumMg = segment.sodiumMg.round();
    final waterMl = segment.waterMl.round();
    final sodiumConc = segment.sodiumConcMgPerL;
    final isTested = segment.isTested;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final sodiumRateMgH = durationH > 0 ? (sodiumMg / durationH).round() : 0;

    final List<FormulaLine> tldrLines;
    if (sodiumConc != null) {
      tldrLines = [
        FormulaLine([
          fAccent('fluid rate '),
          fDim('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent('conc '),
          fDim('$sodiumConc mg/L '),
          fOp('= '),
          fResult('$sodiumRateMgH mg/hr'),
        ], stepNumber: '\u2460'),
        FormulaLine(
          [
            fAccent('$sodiumRateMgH mg/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${sodiumMg}mg'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('$sodiumRateMgH mg/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${sodiumMg}mg'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody:
          'Your sodium target is a simple multiplication of your fluid intake '
          'rate by your sweat sodium concentration. Dial in your test results '
          'if you have one.',
      tldrLines: tldrLines,
      calculationSections: sodiumConc != null
          ? _buildBrickSegmentSodiumCalculationSections(
              segment: segment,
              concMgPerL: sodiumConc,
              useImperial: useImperial,
            )
          : const [],
      storySections: _duringSodiumStorySections(
        sodiumConc: sodiumConc,
        isTested: isTested,
      ),
      videoTitle: 'Watch: Sodium & Endurance',
      targetGrams: sodiumMg.toDouble(),
      rangeLow: segment.sodiumLowMg,
      rangeHigh: segment.sodiumHighMg,
      sportLabel: segment.sport,
    );
  }

  // ---------------------------------------------------------------------------
  // SWIM SODIUM — zero state
  // ---------------------------------------------------------------------------

  /// Public accessor so the sheet can request the swim zero-state directly.
  NutrientTransparencyData _swimSodiumTransparency() {
    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg/hr',
      phase: 'during',
      tldrBody:
          'No sodium intake during swim \u2014 T1 covers the transition need. '
          'Sodium losses during swimming are lower than land sports due to the '
          '0.4\u00d7 sweat modifier applied to the swim segment.',
      tldrLines: const [],
      storySections: const [
        StorySection(
          question: 'Why no sodium during swim?',
          answer:
              'You cannot drink during an open-water or pool swim. Sodium losses '
              'during swimming are also approximately 40% of equivalent land-sport '
              'losses due to passive water cooling reducing the sweat drive. '
              'The T1 transition provides the sodium bolus to bridge the gap '
              'before the bike leg.',
          dataChips: ['Swim sodium modifier \u00b7 0.4\u00d7 land sports'],
          confidence: ConfidenceLevel.medium,
        ),
      ],
      isSwimZero: true,
      swimCallout: 'Sodium covered by: T1 transition \u00b7 Bike segment',
      targetGrams: 0,
      rangeLow: 0,
      rangeHigh: 0,
      sportLabel: 'Swim',
    );
  }

  // ---------------------------------------------------------------------------
  // TRANSITION SODIUM
  // ---------------------------------------------------------------------------

  // SSOT: transition-card.md TC-4 + transition-nutrition.md T-5 (RATIFIED
  // Xuan 2026-09-01): sodium is a TALLY, never a target \u2014 the as-built
  // 265/248 pair dropped its target half, and the drawer must not render a
  // formula implying one. The continuous during schedule owns sodium; salt
  // taken here rides whatever is drunk, at sweat concentration.
  NutrientTransparencyData _transitionSodiumTransparency({
    required ExplanationPhase phase,
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final isT1 = phase == ExplanationPhase.transition1;
    final transitionName = isT1 ? 'T1' : 'T2';
    final tIdx = isT1 ? 0 : 1;

    final transitions = macroTargets.brickPhaseTargets?.transitions;
    final transition = (transitions != null && tIdx < transitions.length)
        ? transitions[tIdx]
        : null;
    final isTested = transition?.isTested ?? false;

    return NutrientTransparencyData(
      nutrientLabel: 'Sodium',
      nutrientColor: const Color(0xFFFF8C42),
      primaryUnit: 'mg',
      phase: 'transition',
      isTested: isTested,
      tldrBody:
          'There is no transition-specific sodium target \u2014 the figure on '
          'the card is a tally of what your planned foods deliver here. '
          'Sodium replacement lives on the continuous during schedule: the '
          'legs carry the per-hour replacement across their full durations, '
          'and anything taken in $transitionName simply counts toward it.',
      tldrLines: const [],
      calculationSections: const [],
      storySections: [
        StorySection(
          question: 'Why is there no transition sodium target?',
          answer:
              'No position stand or practitioner source suggests a fixed '
              'transition sodium amount. Sodium rides on fluid at your sweat '
              'concentration \u2014 the per-leg schedule already replaces it '
              'across the event, so a transition drink is placement of that '
              'schedule, not an extra requirement.',
          dataChips: const ['No target \u00b7 tally only (T-5)'],
        ),
      ],
      targetGrams: null,
      rangeLow: null,
      rangeHigh: null,
      sportLabel: transitionName,
    );
  }

  // ===========================================================================
  // CARB TRANSPARENCY
  // ===========================================================================

  /// Build structured transparency data for the carbs card.
  ///
  /// Handles: pre-workout, during single-sport, during brick segment, swim.
}
