// GENERATED by split of macro_explanation_service.dart — DO NOT hand-edit
// Carb transparency data builders

part of 'macro_explanation_service.dart';

const String _preWorkoutVideoUrl =
    'https://milkman-dev.s3.us-east-2.amazonaws.com/me_videos/me101_1.1.mp4';

extension _$CarbExt on MacroExplanationService {
  NutrientTransparencyData _preWorkoutTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
  }) {
    final pre = macroTargets.preRun;
    final targetG = pre.carbsG.round();
    final rangeLow = pre.carbsLowG?.round() ?? (targetG * 0.875).round();
    final rangeHigh = pre.carbsHighG?.round() ?? (targetG * 1.125).round();
    final hoursBefore = bodyWeightKg > 0
        ? (pre.carbsG / bodyWeightKg).clamp(0.5, 4.0)
        : 1.0;
    final hoursBeforeRounded = (hoursBefore * 10).round() / 10;
    final weightRounded = bodyWeightKg.round();

    // Matches pre-workout-carb.html formula-block exactly
    final tldrLines = <FormulaLine>[
      FormulaLine([
        fAccent('body weight '),
        fOp('\u00d7 '),
        fAccent('hours before workout'),
      ]),
      FormulaLine([
        fAccent('${weightRounded}kg '),
        fOp('\u00d7 '),
        fAccent('$hoursBeforeRounded hr '),
        fOp('= '),
        fResult('${targetG}g'),
      ], isResultLine: true),
    ];

    final storySections = <StorySection>[
      const StorySection(
        question: 'Why carbs before a workout?',
        answer:
            'Your muscles run on glycogen \u2014 stored from the carbs you eat. '
            'During exercise your body burns through it continuously. Fuller stores mean '
            '**better performance, focus, and a lower chance of hitting the wall.**',
      ),
      const StorySection(
        question: 'Why does timing change how much you need?',
        answer:
            'Your digestive system needs time to convert food into fuel. Researchers found '
            'athletes benefit from **1\u20134g per kg, consumed 1\u20134 hours before exercise** '
            '\u2014 roughly 1g per hour of lead time.',
        citation:
            'Kerksick et al., 2017 \u2014 ISSN Position Stand: Nutrient Timing',
      ),
      StorySection(
        question: 'Why a range and not one exact number?',
        answer:
            'Real food doesn\'t come in precise grams \u2014 a banana might be 25g or 28g. '
            'The underlying research is also a range because digestion rates and glycogen stores '
            'vary individually. **$rangeLow\u2013${rangeHigh}g reflects that honestly.**',
      ),
      const StorySection(
        question: 'Shouldn\'t a harder workout mean more carbs?',
        answer:
            'Not in the pre-workout calculation. Intensity influences **when** you should eat '
            '\u2014 harder workouts need a longer lead time. The gram target stays at '
            '1g/kg/hr regardless of intensity.',
        citation: 'Kerksick et al., 2017',
      ),
      const StorySection(
        question: '',
        answer: '',
        transparencyNote:
            'The **\u00b112.5% range** is Mealvana\'s design choice to bridge precise math '
            'and real food portioning \u2014 not from research. Everything else here is.',
      ),
    ];

    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g/h',
      phase: 'before',
      tldrBody:
          'The earlier you eat, the more carbs your body can use. We give you '
          '**1g of carbs per kg of body weight** for every hour before your '
          'workout. Simply put, the amount of carbs is determined by your body '
          'weight and the hours before workout.',
      tldrLines: tldrLines,
      tldrTip:
          '**${targetG}g \u00b1 12.5% = $rangeLow\u2013${rangeHigh}g** '
          '\u2014 a practical window for real food portions.',
      storySections: storySections,
      videoUrl: _preWorkoutVideoUrl,
      videoTitle: 'Watch: Pre-Workout Fueling',
      targetGrams: targetG.toDouble(),
      rangeLow: rangeLow.toDouble(),
      rangeHigh: rangeHigh.toDouble(),
      sportLabel: 'Pre-Workout',
    );
  }

  // ---------------------------------------------------------------------------
  // DURING — SINGLE SPORT
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _duringSingleSportTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    required String sportLabel,
    required String gutTrainingLabel,
    required double gutMultiplier,
    double? personalCarbTargetGPerH,
    String? personalTargetSport,
    ResolvedDuringTarget? resolvedDuringTarget,
  }) {
    final during = macroTargets.duringRun;
    final metrics = macroTargets.metrics;
    final durationMin = metrics.durationMin.round();
    final durationH = metrics.durationH;

    // Raw band from edge function (pre-gut)
    final rawBandLow = during.rawBandLowGPerH ?? during.absClampRangeGPerH[0];
    final rawBandHigh =
        during.rawBandHighGPerH ??
        (during.absClampRangeGPerH.length > 1
            ? during.absClampRangeGPerH[1]
            : during.absClampRangeGPerH[0]);

    // Scaled band (after gut)
    final scaledLow = during.absClampRangeGPerH[0];
    final scaledHigh = during.absClampRangeGPerH.length > 1
        ? during.absClampRangeGPerH[1]
        : during.absClampRangeGPerH[0];

    final midpoint = ((scaledLow + scaledHigh) / 2).round();
    final sportCeiling =
        during.sportCeilingGPerH?.round() ?? _defaultSportCeiling(sportLabel);
    final isCapped = midpoint > sportCeiling;
    final afterCeiling = isCapped ? sportCeiling : midpoint;
    final overrideRate =
        resolvedDuringTarget?.settingsOverrideRateGPerH ??
        personalCarbTargetGPerH;
    final isOverrideApplied = resolvedDuringTarget?.isOverrideApplied ?? false;
    final hasEligiblePersonalTarget = overrideRate != null && durationMin >= 90;
    final shouldApplyOverride =
        isOverrideApplied ||
        (resolvedDuringTarget == null && hasEligiblePersonalTarget);
    final finalRate =
        resolvedDuringTarget?.rateGPerH ??
        (shouldApplyOverride
            ? (overrideRate ?? afterCeiling.toDouble())
            : afterCeiling.toDouble());
    final totalG =
        resolvedDuringTarget?.totalG.round() ?? (finalRate * durationH).round();
    final displayRangeLow = resolvedDuringTarget?.rangeLowG ?? during.carbsLowG;
    final displayRangeHigh =
        resolvedDuringTarget?.rangeHighG ?? during.carbsHighG;

    // Matches during-workout HTML formula-block exactly
    final sl = sportLabel.toLowerCase();
    final rbl = rawBandLow.round();
    final rbh = rawBandHigh.round();
    final scl = scaledLow.round();
    final sch = scaledHigh.round();
    final pt = overrideRate?.round();

    final tldrLines = <FormulaLine>[
      // ① duration → band
      FormulaLine([
        fAccent('$durationMin min $sl '),
        fOp('\u2192 '),
        fAccent('band '),
        fDim('$rbl\u2013$rbh g/hr'),
      ], stepNumber: '\u2460'),
      // ② gut multiplier
      FormulaLine([
        fDim('$rbl\u2013$rbh '),
        fOp('\u00d7 '),
        fAccent('$gutMultiplier gut '),
        fOp('= '),
        fDim('$scl\u2013$sch g/hr'),
      ], stepNumber: '\u2461'),
      // ③ midpoint
      FormulaLine([
        fAccent('midpoint '),
        fOp('= '),
        fDim('$midpoint g/hr'),
      ], stepNumber: '\u2462'),
      // ④ sport ceiling
      FormulaLine([
        fAccent('sport ceiling '),
        fOp('= '),
        fDim('$sportCeiling g/hr '),
        fOp('\u00b7 '),
        fAccent('$midpoint '),
        fOp(isCapped ? '> ' : '< '),
        fAccent('$sportCeiling '),
        fOp('\u2192 '),
        fAccent(isCapped ? 'capped at $sportCeiling' : 'no cap'),
      ], stepNumber: '\u2463'),
      // ⑤ personal target (always shown — shows "no override" when not applicable)
      FormulaLine([
        fAccent('personal target '),
        fOp('= '),
        fDim('${pt ?? "\u2014"} g/hr '),
        fOp('\u00b7 '),
        fAccent('effort '),
        fOp(durationMin >= 90 ? '\u2265 ' : '< '),
        fAccent('90 min '),
        fOp('\u2192 '),
        shouldApplyOverride ? fResult('override') : fAccent('no override'),
      ], stepNumber: '\u2464'),
    ];

    // Result line
    tldrLines.add(
      FormulaLine(
        [
          fAccent('${finalRate.round()} g/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${totalG}g'),
        ],
        isResultLine: true,
        showDividerBefore: true,
      ),
    );

    // Full Story Q&A
    final storySections = _duringStorySections(
      hasOverride: shouldApplyOverride,
      personalCarbTargetGPerH: personalCarbTargetGPerH,
      personalTargetSport: personalTargetSport ?? sportLabel.toLowerCase(),
      isBrick: false,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g/h',
      phase: 'during',
      tldrBody:
          'The longer the workout, the higher the risk your body will burn out '
          'its glycogen storage \u2014 commonly known as \u201chitting the wall\u201d '
          '\u2014 therefore the higher the per-hour carb target we recommend. '
          'However, there is an absorption limit determined by your gut training '
          'status, and it is sport-specific. For athletes who have set a personal '
          'carb target for their races, that target will override our recommendation '
          'for longer workouts.',
      tldrLines: tldrLines,
      storySections: storySections,
      videoTitle: 'Watch: During-Workout Fueling',
      targetGrams: totalG.toDouble(),
      rangeLow: displayRangeLow,
      rangeHigh: displayRangeHigh,
      sportLabel: sportLabel,
      currentGutTrainingLabel: gutTrainingLabel,
      currentPersonalTargetGPerH: overrideRate,
      personalTargetSport: personalTargetSport ?? sportLabel.toLowerCase(),
      isOverrideApplied: shouldApplyOverride,
    );
  }

  // ---------------------------------------------------------------------------
  // DURING — BRICK SEGMENT
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickSegmentTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required String gutTrainingLabel,
    required double gutMultiplier,
    double? personalCarbTargetGPerH,
    String? personalTargetSport,
    ResolvedDuringTarget? resolvedDuringTarget,
  }) {
    final sport = segment.sport;
    final sportCap = sport[0].toUpperCase() + sport.substring(1);
    final durationMin = segment.durationMinutes;
    final durationH = durationMin / 60;
    final cumulativeMin = segment.cumulativeDurationMin?.round() ?? durationMin;
    // The edge function uses TOTAL event time for band lookup, not cumulative
    final totalEventMin = macroTargets.metrics.durationMin.round();

    final rawBandLow = segment.rawBandLowGPerH ?? 0;
    final rawBandHigh = segment.rawBandHighGPerH ?? 0;
    final scaledLow = segment.scaledBandLowGPerH ?? 0;
    final scaledHigh = segment.scaledBandHighGPerH ?? 0;
    final midpoint = ((scaledLow + scaledHigh) / 2).round();
    final sportCeiling =
        segment.sportCeilingGPerH?.round() ?? _defaultSportCeiling(sportCap);
    final isCapped = midpoint > sportCeiling;
    final afterCeiling = isCapped ? sportCeiling : midpoint;
    final brickPenalty = segment.brickPenalty ?? 1.0;
    final hasBrickPenalty = brickPenalty < 1.0;
    final afterPenalty = hasBrickPenalty
        ? (afterCeiling * brickPenalty).round()
        : afterCeiling;
    final overrideRate =
        resolvedDuringTarget?.settingsOverrideRateGPerH ??
        personalCarbTargetGPerH;
    final isOverrideApplied = resolvedDuringTarget?.isOverrideApplied ?? false;
    final hasEligiblePersonalTarget =
        overrideRate != null && totalEventMin >= 90;
    final shouldApplyOverride =
        isOverrideApplied ||
        (resolvedDuringTarget == null && hasEligiblePersonalTarget);
    final finalRate =
        resolvedDuringTarget?.rateGPerH ??
        (shouldApplyOverride
            ? (overrideRate ?? afterPenalty.toDouble())
            : afterPenalty.toDouble());
    final totalG =
        resolvedDuringTarget?.totalG.round() ?? (finalRate * durationH).round();
    final displayRangeLow =
        resolvedDuringTarget?.rangeLowG ?? segment.carbsLowG;
    final displayRangeHigh =
        resolvedDuringTarget?.rangeHighG ?? segment.carbsHighG;

    // Matches brick variant formula-block in HTML exactly
    final rbl = rawBandLow.round();
    final rbh = rawBandHigh.round();
    final scl = scaledLow.round();
    final sch = scaledHigh.round();
    final pt = overrideRate?.round();
    var step = 0;
    const sn = [
      '\u2460',
      '\u2461',
      '\u2462',
      '\u2463',
      '\u2464',
      '\u2465',
      '\u2466',
    ];

    final tldrLines = <FormulaLine>[
      // ① total event time → band
      FormulaLine([
        fAccent('total event time '),
        fOp('= '),
        fDim('$totalEventMin min '),
        fOp('\u2192 '),
        fAccent('band '),
        fDim('$rbl\u2013$rbh g/hr'),
      ], stepNumber: sn[step++]),
      // ② gut multiplier
      FormulaLine([
        fDim('$rbl\u2013$rbh '),
        fOp('\u00d7 '),
        fAccent('$gutMultiplier gut '),
        fOp('= '),
        fDim('$scl\u2013$sch g/hr'),
      ], stepNumber: sn[step++]),
      // ③ midpoint
      FormulaLine([
        fAccent('midpoint '),
        fOp('= '),
        fDim('$midpoint g/hr'),
      ], stepNumber: sn[step++]),
      // ④ sport ceiling
      FormulaLine([
        fAccent('sport ceiling '),
        fOp('= '),
        fDim('$sportCeiling g/hr '),
        fOp('\u00b7 '),
        fAccent('$midpoint '),
        fOp(isCapped ? '> ' : '< '),
        fAccent('$sportCeiling '),
        fOp('\u2192 '),
        fAccent(isCapped ? 'capped at $sportCeiling' : 'no cap'),
      ], stepNumber: sn[step++]),
    ];

    // ⑤ brick penalty (only for run-after-bike)
    if (hasBrickPenalty) {
      tldrLines.add(
        FormulaLine([
          fAccent('brick penalty '),
          fOp('\u00b7 '),
          fAccent('run after bike '),
          fOp('\u2192 '),
          fAccent('$afterCeiling '),
          fOp('\u00d7 '),
          fAccent('$brickPenalty '),
          fOp('= '),
          fDim('$afterPenalty g/hr'),
        ], stepNumber: sn[step++]),
      );
    }

    // ⑤/⑥ personal target
    if (hasEligiblePersonalTarget) {
      tldrLines.add(
        FormulaLine([
          fAccent('personal target '),
          fOp('= '),
          fDim('${pt ?? "\u2014"} g/hr '),
          fOp('\u00b7 '),
          fAccent('effort '),
          fOp('\u2265 '),
          fAccent('90 min '),
          fOp('\u2192 '),
          shouldApplyOverride ? fResult('override') : fAccent('no override'),
        ], stepNumber: sn[step++]),
      );
    }

    // Result
    tldrLines.add(
      FormulaLine(
        [
          fAccent('${finalRate.round()} g/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${totalG}g'),
        ],
        isResultLine: true,
        showDividerBefore: true,
      ),
    );

    final storySections = _brickStorySections(
      cumulativeMin: cumulativeMin,
      segmentMin: durationMin,
      hasBrickPenalty: hasBrickPenalty,
      hasOverride: shouldApplyOverride,
      personalCarbTargetGPerH: personalCarbTargetGPerH,
      personalTargetSport: personalTargetSport ?? sport,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g/h',
      phase: 'during',
      tldrBody:
          'In a multi-sport event, your carb target is based on '
          '**total elapsed time** across the entire event \u2014 not just this '
          'segment. The longer your body has been working, the higher the risk '
          'of glycogen depletion, so the algorithm looks at your cumulative race '
          'time to set the right band.',
      tldrLines: tldrLines,
      storySections: storySections,
      videoTitle: 'Watch: During-Workout Fueling',
      targetGrams: totalG.toDouble(),
      rangeLow: displayRangeLow,
      rangeHigh: displayRangeHigh,
      sportLabel: sportCap,
      currentGutTrainingLabel: gutTrainingLabel,
      currentPersonalTargetGPerH: overrideRate,
      personalTargetSport: personalTargetSport ?? sport,
      isOverrideApplied: shouldApplyOverride,
    );
  }

  // ---------------------------------------------------------------------------
  // BRICK TRANSITION (T1 / T2)
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickTransitionTransparency({
    required ExplanationPhase phase,
    required MacroTargets macroTargets,
  }) {
    final isT1 = phase == ExplanationPhase.transition1;
    final transitionName = isT1 ? 'T1' : 'T2';
    final fromSport = isT1 ? 'swim' : 'bike';
    final toSport = isT1 ? 'bike' : 'run';

    // Look up transition targets if available
    final transitions = macroTargets.brickPhaseTargets?.transitions;
    final tIdx = isT1 ? 0 : 1;
    final transition = (transitions != null && tIdx < transitions.length)
        ? transitions[tIdx]
        : null;
    final targetG = transition?.carbsG.round();

    final tldrBody =
        'Transition $transitionName is a short window between the $fromSport '
        'and $toSport segments. Use this time to take in quick-digesting carbs '
        'and fluids before the next leg begins.';

    final tldrLines = <FormulaLine>[];
    if (targetG != null) {
      tldrLines.add(
        FormulaLine([
          fAccent('$transitionName target '),
          fOp('= '),
          fResult('${targetG}g'),
        ]),
      );
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g/h',
      phase: 'transition',
      tldrBody: tldrBody,
      tldrLines: tldrLines,
      storySections: [
        StorySection(
          question: 'Why eat during a transition?',
          answer:
              'Transitions are your only chance to refuel between segments. Even '
              'though they are short, consuming **quick-digesting carbs** here helps '
              'maintain blood glucose for the next leg \u2014 especially important before '
              'the $toSport where intensity often increases.',
        ),
        StorySection(
          question: 'What kinds of food work best?',
          answer:
              'Choose foods that digest fast and require minimal chewing: '
              '**gels, chews, or liquid carbs.** Avoid high-fibre or high-fat '
              'options that could cause GI distress once you start moving again.',
        ),
      ],
      targetGrams: transition?.carbsG,
      rangeLow: transition?.carbsLowG,
      rangeHigh: transition?.carbsHighG,
      sportLabel: transitionName,
    );
  }

  // ---------------------------------------------------------------------------
  // BRICK — GENERIC (no detailed segment data available)
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickGenericTransparency({
    required MacroTargets macroTargets,
    required String sportLabel,
    required String gutTrainingLabel,
    required double gutMultiplier,
    double? personalCarbTargetGPerH,
    String? personalTargetSport,
  }) {
    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g/h',
      phase: 'during',
      tldrBody:
          'In a multi-sport event, your carb target is based on '
          '**total elapsed time** across the entire event \u2014 not just this '
          'segment. The longer your body has been working, the higher the risk '
          'of glycogen depletion, so the algorithm looks at your cumulative race '
          'time to set the right band.',
      tldrLines: const [],
      storySections: _brickStorySections(
        cumulativeMin: 0,
        segmentMin: 0,
        hasBrickPenalty: false,
        hasOverride: false,
        personalCarbTargetGPerH: personalCarbTargetGPerH,
        personalTargetSport: personalTargetSport ?? sportLabel,
      ),
      videoTitle: 'Watch: During-Workout Fueling',
      sportLabel: sportLabel,
      currentGutTrainingLabel: gutTrainingLabel,
      currentPersonalTargetGPerH: personalCarbTargetGPerH,
      personalTargetSport: personalTargetSport ?? sportLabel,
    );
  }

  // ---------------------------------------------------------------------------
  // DURING — SWIM (zero state)
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _swimTransparency({
    BrickSegmentMacroTarget? brickSegment,
  }) {
    final tldrLines = <FormulaLine>[];

    final storySections = <StorySection>[
      const StorySection(
        question: 'Why is the target zero during swimming?',
        answer:
            'Swimming is the only endurance sport where fueling during the activity is '
            'physically impossible. You cannot eat or drink while in open water or a pool '
            'without stopping. All carbohydrate intake is therefore shifted to the pre-swim '
            'meal, and to T1 where you have a brief window to consume calories before the '
            'bike leg begins.',
      ),
      const StorySection(
        question: 'Does the swim time still count toward total event time?',
        answer:
            'Yes \u2014 and this is important. Even though you consume 0g during the swim, '
            'your body is still burning glycogen for the entire duration. The swim time is '
            'fully included in the cumulative elapsed time used to determine your carb band '
            'on the bike and run segments.',
      ),
      const StorySection(
        question: 'What should I eat before the swim?',
        answer:
            'Your pre-workout carb targets account for the full race duration. See the '
            '**Before Workout** section for your pre-swim meal targets. T1 transition nutrition '
            'is shown separately in the race fueling plan.',
      ),
    ];

    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g/h',
      phase: 'during',
      tldrBody:
          'No carbohydrates can be consumed during swimming \u2014 it is physically '
          'impossible to eat or drink while in the water. All fueling for this segment '
          'shifts to the **before-workout phase** and to **T1 transition nutrition**.',
      tldrLines: tldrLines,
      storySections: storySections,
      isSwimZero: true,
      swimCallout: 'Fueling shifts to: Before workout \u00b7 T1 transition',
      targetGrams: 0,
      rangeLow: 0,
      rangeHigh: 0,
      sportLabel: 'Swim',
    );
  }

  // ---------------------------------------------------------------------------
  // FULL STORY SECTIONS — DURING SINGLE SPORT
  // ---------------------------------------------------------------------------

  List<StorySection> _duringStorySections({
    required bool hasOverride,
    double? personalCarbTargetGPerH,
    required String personalTargetSport,
    required bool isBrick,
  }) {
    final sections = <StorySection>[
      const StorySection(
        question: 'Why does duration set the starting range?',
        answer:
            'Your body can\'t replenish muscle glycogen while exercising \u2014 consumed '
            'carbs maintain blood glucose and slow depletion instead. The longer you go, '
            'the more you need. Research gives us reliable absorption ranges by duration.',
        citation:
            'Jeukendrup (2014) \u2014 Sports Medicine; Kerksick et al. (2017) \u2014 ISSN Position Stand',
        transparencyNote:
            'No single study gives these exact bands with these specific minute cutoffs. '
            'The research anchors two points: minimal intake under 60 min (Carter et al. 2004 '
            '\u2014 mouth rinse research), and up to 90 g/hr for very long efforts (Jeukendrup '
            '2004). The five bands are **Mealvana\'s interpolation**. The direction is well-supported. '
            'The specific cutoffs are ours.',
        dataChips: [
          '<60 min \u00b7 0\u201330 g/hr',
          '60\u201390 min \u00b7 30\u201360 g/hr',
          '90\u2013150 min \u00b7 45\u201360 g/hr',
          '150\u2013240 min \u00b7 60\u201390 g/hr',
          '>240 min \u00b7 80\u2013100 g/hr',
        ],
      ),
      const StorySection(
        question: 'What is gut training and why does it matter?',
        answer:
            'Athletes who consistently fuel during workouts upregulate the transporters '
            'that move carbs from gut to bloodstream. Your gut training level scales the '
            'entire band up or down.',
        citation:
            'Jeukendrup (2017) \u2014 Training the Gut for Athletes; Costa et al. (2019)',
        inlineEditType: InlineEditType.gutTraining,
        dataChips: [
          'Low \u00b7 0.7\u00d7',
          'Moderate \u00b7 1.0\u00d7',
          'High \u00b7 1.2\u00d7',
        ],
      ),
      const StorySection(
        question: 'Why doesn\'t body weight change the target?',
        answer:
            'During-exercise carb recommendations are **not body-weight dependent.** The '
            'limiting factor is gut absorption capacity \u2014 and that doesn\'t scale '
            'with body weight.',
        citation:
            'Jeukendrup (2014) \u2014 "There is no rationale for expressing carbohydrate '
            'recommendations per kilogram of body weight."',
      ),
      const StorySection(
        question: 'Why does sport type set a ceiling?',
        answer:
            'Running\'s vertical impact stresses the gut, limiting carb processing. '
            'Cycling\'s stable position removes that stress \u2014 cyclists can sustain '
            'nearly double the carb rate of runners. Gut training expands your band, but '
            'the sport ceiling is the hard limit it can never exceed. A highly gut-trained '
            'runner capped at **70 g/hr** on the run can realize the full benefit of their '
            'training up to **120 g/hr** on the bike.',
        citation:
            'Pfeiffer et al. (2012) \u2014 GI Problems in Endurance Sports',
        dataChips: [
          'Running \u00b7 max 70 g/hr',
          'Cycling \u00b7 max 120 g/hr',
          'Swimming \u00b7 0 g/hr',
        ],
      ),
    ];

    if (hasOverride) {
      sections.add(
        StorySection(
          question: 'Why does your personal target override the algorithm?',
          answer:
              'For efforts of 90 minutes or longer, your personal carb rate replaces the '
              'algorithm\'s midpoint. A newer athlete may start at 30 g/hr to avoid GI '
              'distress. An experienced athlete may push to 80 g/hr on a long ride. The '
              'algorithm gives you the science. Your personal target gives you the control.',
          inlineEditType: InlineEditType.personalTarget,
        ),
      );
    }

    return sections;
  }

  // ---------------------------------------------------------------------------
  // FULL STORY SECTIONS — BRICK
  // ---------------------------------------------------------------------------

  List<StorySection> _brickStorySections({
    required int cumulativeMin,
    required int segmentMin,
    required bool hasBrickPenalty,
    required bool hasOverride,
    double? personalCarbTargetGPerH,
    required String personalTargetSport,
  }) {
    final sections = <StorySection>[
      StorySection(
        question: 'Why does the band use total event time, not run time?',
        answer:
            'Glycogen depletion is cumulative \u2014 your body doesn\'t reset when you '
            'dismount the bike. By the time you start the run, you\'ve already been burning '
            'fuel for $cumulativeMin minutes. Using only the run duration ($segmentMin min) '
            'would dramatically underestimate how depleted you are and recommend a carb rate '
            'suited for a fresh runner.',
        citation: 'V4 algorithm \u2014 Mealvana cumulative time model',
      ),
    ];

    if (hasBrickPenalty) {
      sections.add(
        const StorySection(
          question: 'What is the brick penalty?',
          answer:
              'Running after cycling reduces your gut\'s ability to absorb carbohydrates. '
              'During the bike leg, blood is diverted away from the gut to working muscles. '
              'Transitioning to running \u2014 with its additional vertical impact \u2014 '
              'compounds this effect. The 20% reduction reflects the reduced splanchnic blood '
              'flow and mechanical stress during the early run.',
          citation:
              'Van Wijck et al. (2012) \u2014 Splanchnic hypoperfusion during exercise',
        ),
      );
    }

    // Gut training Q&A — same as single sport
    sections.add(
      const StorySection(
        question: 'What is gut training and why does it matter?',
        answer:
            'Your gut training level scales the entire duration band up or down '
            'before the sport ceiling is applied.',
        citation: 'Jeukendrup (2017); Costa et al. (2019)',
        inlineEditType: InlineEditType.gutTraining,
        dataChips: [
          'Low \u00b7 0.7\u00d7',
          'Moderate \u00b7 1.0\u00d7',
          'High \u00b7 1.2\u00d7',
        ],
      ),
    );

    if (hasOverride) {
      sections.add(
        StorySection(
          question: 'Why does your personal target override the algorithm?',
          answer:
              'For efforts of 90 minutes or longer your personal carb rate takes over. '
              'In a race context this is especially important \u2014 your personal target '
              'reflects your race-day fueling strategy, which may account for gut sensitivity '
              'late in the race, aid station availability, or coach guidance.',
          inlineEditType: InlineEditType.personalTarget,
        ),
      );
    }

    return sections;
  }

  // ---------------------------------------------------------------------------
  // POST-WORKOUT (AFTER)
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _postWorkoutCarbTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
  }) {
    final post = macroTargets.postRun;
    final durationH = macroTargets.metrics.durationH;
    final targetG = post.carbsG.round();
    final rangeLow = post.carbsLowG?.round() ?? (targetG * 0.8).round();
    final rangeHigh = post.carbsHighG?.round() ?? (targetG * 1.2).round();
    final durationMult = durationH > 2 ? 1.2 : 1.0;
    final durationNote = durationH > 2
        ? '1.2\u00d7 multiplier applied (workout > 2 hr)'
        : '1.0\u00d7 (standard recovery, workout \u2264 2 hr)';
    final weightRounded = bodyWeightKg.round();

    final tldrLines = <FormulaLine>[
      FormulaLine([
        fAccent('body weight '),
        fOp('\u00d7 '),
        fAccent('duration multiplier'),
      ]),
      FormulaLine([
        fAccent('${weightRounded}kg '),
        fOp('\u00d7 '),
        fAccent('${durationMult.toStringAsFixed(1)} g/kg '),
        fOp('= '),
        fResult('${targetG}g'),
      ], isResultLine: true),
    ];

    final storySections = <StorySection>[
      const StorySection(
        question: 'Why carbs after a workout?',
        answer:
            'Recovery carbs replenish the **glycogen** (stored energy) your '
            'muscles burned during your workout. Refilling those stores within '
            'the first hour kickstarts recovery for your next session.',
      ),
      StorySection(
        question: 'Why does duration change the multiplier?',
        answer:
            'Workouts longer than 2 hours deplete glycogen more aggressively, '
            'so we bump the recovery target by 20% '
            '(**1.2 g/kg** vs. 1.0 g/kg for shorter workouts).\n\n'
            'For your ${durationH.toStringAsFixed(1)} hr session: $durationNote.',
      ),
      StorySection(
        question: 'Why a range and not one exact number?',
        answer:
            'Real food doesn\'t come in precise grams. The '
            '**$rangeLow\u2013${rangeHigh}g** window gives you flexibility '
            'while staying in the recovery zone.',
      ),
      const StorySection(
        question: 'When should I eat?',
        answer:
            'Aim for the first hour after exercise, when your muscles are '
            'most receptive to refueling. Pair carbs with protein for the '
            'best recovery.',
      ),
    ];

    return NutrientTransparencyData(
      nutrientLabel: 'Carbs',
      primaryUnit: 'g',
      phase: 'after',
      tldrBody:
          'After your workout, we replenish glycogen with '
          '**${durationMult.toStringAsFixed(1)} g of carbs per kg of body weight**. '
          'Eat within the first hour for the best recovery.',
      tldrLines: tldrLines,
      tldrTip:
          '**${targetG}g** target ($rangeLow\u2013${rangeHigh}g range).',
      storySections: storySections,
      targetGrams: targetG.toDouble(),
      rangeLow: rangeLow.toDouble(),
      rangeHigh: rangeHigh.toDouble(),
      sportLabel: 'Post-Workout',
    );
  }

  // ---------------------------------------------------------------------------
  // HELPERS
  // ---------------------------------------------------------------------------

}
