// GENERATED by split of macro_explanation_service.dart — DO NOT hand-edit
// Calculation-section builders for the transparency UI accordion

part of 'macro_explanation_service.dart';

extension _$CalculationsExt on MacroExplanationService {
  double _tempMult(double? tempC) {
    if (tempC == null) return 1.0;
    final raw = 1.0 + (tempC - 22.0) * 0.04;
    return raw.clamp(0.50, 1.80);
  }

  double _humidityMult(double? humidityPct) {
    if (humidityPct == null) return 1.0;
    final raw = 1.0 + math.max(0, humidityPct - 50.0) * 0.002;
    return raw.clamp(1.0, 1.10);
  }

  double _indoorMult(bool? isIndoor) => (isIndoor == true) ? 1.30 : 1.0;

  String _replacementBandLabel(int durationMin) {
    if (durationMin < 60) return '< 60 min';
    if (durationMin <= 90) return '60–90 min';
    if (durationMin <= 150) return '90–150 min';
    if (durationMin < 240) return '150–240 min';
    return '240+ min';
  }

  /// Builds the "CALCULATE EFFECTIVE SWEAT RATE" + "REPLACEMENT STRATEGY"
  /// sections for the during-workout Fluids calculation accordion.
  List<CalculationSection> _buildDuringFluidCalculationSections({
    required DuringRunMacros during,
    required int durationMin,
    required double durationH,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final effective = during.effectiveSweatRateLPerH;
    final replacementPct = during.replacementPercent;
    if (effective == null || replacementPct == null) return const [];

    final tempMult = _tempMult(during.tempC);
    final humidityMult = _humidityMult(during.humidityPct);
    final indoorMult = _indoorMult(during.isIndoor);
    final multProduct = tempMult * humidityMult * indoorMult;
    final baseRate = multProduct > 0 ? effective / multProduct : effective;

    final fluidRateMlH = during.fluidRateMlPerH.round();
    final fluidTotalMl = during.fluidTotalMl.round();
    final floorMlH = during.floorMlPerH;
    final ceilingMlH = during.ceilingMlPerH;
    final replacePctInt = (replacementPct * 100).round();
    // _replacementBandLabel(durationMin) is reserved for a future step-header
    // variant; leave off the unused local here.

    // Step 1: base rate (tested or category)
    final FormulaLine step1 = during.isTested
        ? FormulaLine(
            [
              fAccent('sweat test '),
              fOp('→ '),
              fDim('${baseRate.toStringAsFixed(2)} L/hr '),
              fResult('TESTED ✓'),
            ],
            stepNumber: '①',
          )
        : FormulaLine(
            [
              fAccent('${_sweaterLabel(baseRate)} sweater '),
              fOp('→ '),
              fDim('${baseRate.toStringAsFixed(2)} L/hr '),
              fOp(_sweaterPercentile(baseRate)),
            ],
            stepNumber: '①',
          );

    // Step 2: temp mult
    double running = baseRate;
    running *= tempMult;
    final FormulaLine step2 = FormulaLine(
      [
        fAccent('${during.tempC?.toStringAsFixed(0) ?? '22'}°C '),
        fOp('→ × '),
        fDim('${tempMult.toStringAsFixed(2)} '),
        fOp('= '),
        fDim('${running.toStringAsFixed(2)} L/hr'),
      ],
      stepNumber: '②',
    );

    // Step 3: humidity mult
    running *= humidityMult;
    final FormulaLine step3 = FormulaLine(
      [
        fAccent('${during.humidityPct?.toStringAsFixed(0) ?? '50'}% humidity '),
        fOp('→ × '),
        fDim('${humidityMult.toStringAsFixed(2)} '),
        fOp('= '),
        fDim('${running.toStringAsFixed(2)} L/hr'),
      ],
      stepNumber: '③',
    );

    // Step 4: indoor/outdoor mult
    running *= indoorMult;
    final FormulaLine step4 = FormulaLine(
      [
        fAccent(during.isIndoor == true ? 'indoor ' : 'outdoor '),
        fOp('→ × '),
        fDim('${indoorMult.toStringAsFixed(2)} '),
        fOp('= '),
        fDim('${effective.toStringAsFixed(2)} L/hr '),
        fAccent('effective'),
      ],
      stepNumber: '④',
    );

    final sweatRateSection = CalculationSection(
      header: 'CALCULATE EFFECTIVE SWEAT RATE',
      lines: [step1, step2, step3, step4],
    );

    // ── REPLACEMENT STRATEGY ───────────────────────────────────────────────
    final effectiveMlHr = (effective * 1000).round();

    final step5 = FormulaLine(
      [
        fAccent('$durationMin min '),
        fOp('→ '),
        fAccent('$replacePctInt% '),
        fOp('→ '),
        fDim('${effective.toStringAsFixed(2)} '),
        fOp('× '),
        fDim('1000 '),
        fOp('× '),
        fDim('${(replacementPct).toStringAsFixed(2)} '),
        fOp('= '),
        fResult(_fmtMlRate((effectiveMlHr * replacementPct).round(), useImperial)),
      ],
      stepNumber: '⑤',
    );

    final replacementLines = <FormulaLine>[step5];

    if (floorMlH != null) {
      replacementLines.add(
        FormulaLine(
          [
            fOp('↓ '),
            fAccent('floor '),
            fDim('= ${_fmtMlRate(floorMlH, useImperial)} '),
            fOp('(2% of ${bodyWeightKg.round()} kg)'),
          ],
        ),
      );
    }
    if (ceilingMlH != null) {
      replacementLines.add(
        FormulaLine(
          [
            fOp('↑ '),
            fAccent('ceiling '),
            fDim('= ${_fmtMlRate(ceilingMlH, useImperial)} '),
            fOp('(GI limit)'),
          ],
        ),
      );
    }

    // Override check lines
    final pctBased = (effectiveMlHr * replacementPct).round();
    if (floorMlH != null) {
      replacementLines.add(
        FormulaLine(
          [
            fDim('${_fmtMlRate(pctBased, useImperial)} '),
            fOp(pctBased > floorMlH ? '> ' : '< '),
            fDim(_fmtMlRate(floorMlH, useImperial)),
            fOp(' → '),
            fAccent(pctBased > floorMlH ? 'no floor override' : 'floor raises target'),
          ],
        ),
      );
    }
    if (ceilingMlH != null) {
      replacementLines.add(
        FormulaLine(
          [
            fDim('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp(fluidRateMlH < ceilingMlH ? '< ' : '= '),
            fDim(_fmtMlRate(ceilingMlH, useImperial)),
            fOp(' → '),
            fAccent(
              fluidRateMlH < ceilingMlH ? 'no ceiling cap' : 'capped at ceiling',
            ),
          ],
        ),
      );
    }

    // Final result
    replacementLines.add(
      FormulaLine(
        [
          fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('× '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult(_fmtMlAmount(fluidTotalMl, useImperial)),
        ],
        isResultLine: true,
        showDividerBefore: true,
      ),
    );

    final replacementSection = CalculationSection(
      header: 'REPLACEMENT STRATEGY',
      lines: replacementLines,
    );

    return [sweatRateSection, replacementSection];
  }

  /// Display label for a sweat rate category given its base L/hr value.
  /// 0.90 → light, 1.28 → medium, 1.66 → heavy. Falls through to medium.
  String _sweaterLabel(double baseLph) {
    if (baseLph <= 1.05) return 'light';
    if (baseLph <= 1.45) return 'medium';
    return 'heavy';
  }

  /// Baker 2016 percentile annotation for a sweat-rate tier.
  /// Maps light → 25th, medium → 50th, heavy → 75th.
  String _sweaterPercentile(double baseLph) {
    if (baseLph <= 1.05) return '(25th pct)';
    if (baseLph <= 1.45) return '(50th pct)';
    return '(75th pct)';
  }

  /// Baker 2016 percentile annotation for a sweat-sodium tier.
  /// Maps low (≤700) → 25th, average (≤900) → 50th, high → 75th.
  String _saltPercentile(int concMgPerL) {
    if (concMgPerL <= 700) return '(25th pct)';
    if (concMgPerL <= 900) return '(50th pct)';
    return '(75th pct)';
  }

  /// Builds the calculation sections for the during-workout Sodium card.
  /// Shows: conc = category → mg/L, then sodium_mg/hr = fluid × (conc/1000).
  List<CalculationSection> _buildDuringSodiumCalculationSections({
    required DuringRunMacros during,
    required double durationH,
    bool useImperial = false,
  }) {
    final conc = during.sodiumConcMgPerL;
    if (conc == null) return const [];
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final sodiumRateMgH = during.sodiumRateMgPerH.round();
    final sodiumTotalMg = during.sodiumTotalMg.round();
    final floorMlH = during.floorMlPerH;
    final ceilingMlH = during.ceilingMlPerH;

    final sweatSection = CalculationSection(
      header: 'CALCULATE SODIUM RATE',
      lines: [
        FormulaLine(
          [
            fAccent('${_sodiumSaltLabel(conc)} salt '),
            fOp('→ '),
            fDim('$conc mg/L '),
            fOp(_saltPercentile(conc)),
          ],
          stepNumber: '①',
        ),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('× '),
            fDim('($conc ÷ 1000) '),
            fOp('= '),
            fResult('$sodiumRateMgH mg/hr'),
          ],
          stepNumber: '②',
        ),
      ],
    );

    final floorCeilLines = <FormulaLine>[];
    if (floorMlH != null) {
      final floorMg = ((floorMlH / 1000) * conc).round();
      floorCeilLines.add(
        FormulaLine([
          fOp('↓ '),
          fAccent('floor '),
          fDim('= ${_fmtMlRate(floorMlH, useImperial)} × ($conc ÷ 1000) = $floorMg mg/hr'),
        ]),
      );
    }
    if (ceilingMlH != null) {
      final ceilMg = ((ceilingMlH / 1000) * conc).round();
      floorCeilLines.add(
        FormulaLine([
          fOp('↑ '),
          fAccent('ceiling '),
          fDim('= ${_fmtMlRate(ceilingMlH, useImperial)} × ($conc ÷ 1000) = $ceilMg mg/hr'),
        ]),
      );
    }

    floorCeilLines.add(
      FormulaLine(
        [
          fAccent('$sodiumRateMgH mg/hr '),
          fOp('× '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('$sodiumTotalMg mg total'),
        ],
        isResultLine: true,
        showDividerBefore: true,
      ),
    );

    return [
      sweatSection,
      CalculationSection(
        header: 'FLOOR & CEILING',
        lines: floorCeilLines,
        // C21 — inherited-note callout per `transparency_during_sodium.md`.
        footerNote:
            'The ${_fmtMlRate(fluidRateMlH, useImperial)} fluid rate, floor, and ceiling all come '
            'from the Fluids section. Sodium automatically adjusts when '
            'fluid adjusts.',
      ),
    ];
  }

  String _sodiumSaltLabel(int concMgPerL) {
    if (concMgPerL <= 700) return 'low';
    if (concMgPerL <= 900) return 'average';
    return 'high';
  }

  // ---------------------------------------------------------------------------
  // BRICK / REDISTRIBUTION FLUID CALCULATION SECTIONS
  // Builds the same CALCULATE EFFECTIVE SWEAT RATE + REPLACEMENT STRATEGY
  // blocks but from a [BrickSegmentMacroTarget]. Replacement % uses the total
  // event duration (not the per-segment duration) per spec.
  // ---------------------------------------------------------------------------

  List<CalculationSection> _buildBrickFluidCalculationSections({
    required DuringRunMacros during,
    required BrickSegmentMacroTarget segment,
    required int totalEventMin,
    required double bodyWeightKg,
    bool showRedistributionNote = false,
    // When true and the workout has T1/T2 transitions, emit a blue info
    // callout below the calc pipeline explaining how the transitions
    // absorbed 600 ml of the total-event requirement. Only relevant on
    // the Multi-Segment scenario (not Redistribution, which has its own
    // purple callout).
    bool showTransitionAbsorptionNote = false,
    int? transitionCount,
    bool useImperial = false,
  }) {
    final effective = segment.effectiveSweatRateLPerH;
    final replacementPct = segment.replacementPercent;
    if (effective == null || replacementPct == null) return const [];

    final tempMult = _tempMult(during.tempC);
    final humidityMult = _humidityMult(during.humidityPct);
    final indoorMult = _indoorMult(during.isIndoor);
    final multProduct = tempMult * humidityMult * indoorMult;
    final baseRate = multProduct > 0 ? effective / multProduct : effective;

    final segDurationH = segment.durationMinutes / 60.0;
    final fluidRateMlH = segDurationH > 0
        ? (segment.waterMl / segDurationH).round()
        : 0;
    final waterTotalMl = segment.waterMl.round();
    final replacePctInt = (replacementPct * 100).round();
    final floorMlH = segment.floorMlPerH;
    final ceilingMlH = segment.ceilingMlPerH;

    // ── Sweat rate section ──────────────────────────────────────────────
    double running = baseRate;
    final sweatLines = <FormulaLine>[];
    sweatLines.add(
      segment.isTested
          ? FormulaLine(
              [
                fAccent('sweat test '),
                fOp('→ '),
                fDim('${baseRate.toStringAsFixed(2)} L/hr '),
                fResult('TESTED ✓'),
              ],
              stepNumber: '①',
            )
          : FormulaLine(
              [
                fAccent('${_sweaterLabel(baseRate)} sweater '),
                fOp('→ '),
                fDim('${baseRate.toStringAsFixed(2)} L/hr '),
                fOp(_sweaterPercentile(baseRate)),
              ],
              stepNumber: '①',
            ),
    );
    running *= tempMult;
    sweatLines.add(FormulaLine([
      fAccent('${during.tempC?.toStringAsFixed(0) ?? '22'}°C '),
      fOp('→ × '),
      fDim('${tempMult.toStringAsFixed(2)} '),
      fOp('= '),
      fDim('${running.toStringAsFixed(2)} L/hr'),
    ], stepNumber: '②'));
    running *= humidityMult;
    sweatLines.add(FormulaLine([
      fAccent('${during.humidityPct?.toStringAsFixed(0) ?? '50'}% humidity '),
      fOp('→ × '),
      fDim('${humidityMult.toStringAsFixed(2)} '),
      fOp('= '),
      fDim('${running.toStringAsFixed(2)} L/hr'),
    ], stepNumber: '③'));
    running *= indoorMult;
    sweatLines.add(FormulaLine([
      fAccent(during.isIndoor == true ? 'indoor ' : 'outdoor '),
      fOp('→ × '),
      fDim('${indoorMult.toStringAsFixed(2)} '),
      fOp('= '),
      fDim('${effective.toStringAsFixed(2)} L/hr '),
      fAccent('effective'),
    ], stepNumber: '④'));

    // ── Replacement strategy section ────────────────────────────────────
    final replacementLines = <FormulaLine>[];
    replacementLines.add(FormulaLine([
      fAccent('$totalEventMin min total '),
      fOp('→ '),
      fAccent('$replacePctInt% '),
      fOp('→ '),
      fDim('event-based replacement %'),
    ], stepNumber: '⑤'));

    if (floorMlH != null) {
      replacementLines.add(FormulaLine([
        fOp('↓ '),
        fAccent('floor '),
        fDim('= ${_fmtMlRate(floorMlH, useImperial)} '),
        fOp('(2% of ${bodyWeightKg.round()} kg BW)'),
      ]));
    }
    if (ceilingMlH != null) {
      final sportLabel = segment.sport.toLowerCase().contains('run')
          ? 'running GI'
          : segment.sport.toLowerCase().contains('cycl')
              ? 'cycling GI'
              : 'sport GI';
      replacementLines.add(FormulaLine([
        fOp('↑ '),
        fAccent('ceiling '),
        fDim('= ${_fmtMlRate(ceilingMlH, useImperial)} '),
        fOp('($sportLabel limit)'),
      ]));
    }

    if (showRedistributionNote) {
      replacementLines.add(FormulaLine([
        fOp('# '),
        fAccent('redistribution '),
        fDim('run shortfall → bike (bike absorbed extra)'),
      ]));
    }

    replacementLines.add(FormulaLine(
      [
        fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
        fOp('× '),
        fAccent('${_formatDuration(segDurationH)} hr '),
        fOp('= '),
        fResult(_fmtMlAmount(waterTotalMl, useImperial)),
      ],
      isResultLine: true,
      showDividerBefore: true,
    ));

    // Priority: Redistribution (purple) takes precedence over the
    // Multi-Segment transition-absorption note (blue) since the two would
    // never both apply to the same leg — redistribution already implies
    // the transitions weren't enough.
    String? footerNote;
    CalcNoteVariant footerVariant = CalcNoteVariant.info;
    if (showRedistributionNote) {
      footerNote =
          'The run leg can only absorb 800 ml/hr — the overflow has '
          'been shifted to this bike leg so the total race stays '
          'within 2% body weight loss. Transitions already absorbed '
          '${_fmtMlAmount(600, useImperial)}; the heavy sweat rate still required redistribution.';
      footerVariant = CalcNoteVariant.redistribution;
    } else if (showTransitionAbsorptionNote &&
        transitionCount != null &&
        transitionCount > 0) {
      // Spec `transparency_during_hydration.md` §Multi-Segment — blue
      // info callout explaining how T1/T2 each absorb 300 ml of the
      // total-event fluid requirement, keeping per-leg rates within
      // segment ceilings and avoiding the need for redistribution.
      final totalAbsorbedMl = transitionCount * 300;
      final transitionsLabel = transitionCount == 1 ? 'T2' : 'T1 and T2';
      footerNote =
          '$transitionsLabel ${transitionCount == 1 ? "provides" : "each provide"} '
          '${_fmtMlAmount(300, useImperial)}. '
          'These transition windows absorb ${_fmtMlAmount(totalAbsorbedMl, useImperial)} of the '
          'race fluid requirement, keeping the per-leg rate within '
          'segment GI ceilings (no redistribution needed).';
      footerVariant = CalcNoteVariant.info;
    }

    return [
      CalculationSection(
        header: 'CALCULATE EFFECTIVE SWEAT RATE',
        lines: sweatLines,
      ),
      CalculationSection(
        header: 'REPLACEMENT STRATEGY',
        lines: replacementLines,
        footerNote: footerNote,
        footerNoteVariant: footerVariant,
      ),
    ];
  }

  /// Sodium calc for a brick segment: (fluid_ml_hr / 1000) × conc.
  List<CalculationSection> _buildBrickSegmentSodiumCalculationSections({
    required BrickSegmentMacroTarget segment,
    required int concMgPerL,
    bool useImperial = false,
  }) {
    final segDurationH = segment.durationMinutes / 60.0;
    final fluidRateMlH = segDurationH > 0
        ? (segment.waterMl / segDurationH).round()
        : 0;
    final sodiumRateMgH = segDurationH > 0
        ? (segment.sodiumMg / segDurationH).round()
        : 0;
    final sodiumTotalMg = segment.sodiumMg.round();

    return [
      CalculationSection(
        header: 'CALCULATE SODIUM RATE',
        lines: [
          FormulaLine([
            fAccent('${_sodiumSaltLabel(concMgPerL)} salt '),
            fOp('→ '),
            fDim('$concMgPerL mg/L '),
            fOp(_saltPercentile(concMgPerL)),
          ], stepNumber: '①'),
          FormulaLine([
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('× '),
            fDim('($concMgPerL ÷ 1000) '),
            fOp('= '),
            fResult('$sodiumRateMgH mg/hr'),
          ], stepNumber: '②'),
          FormulaLine(
            [
              fAccent('$sodiumRateMgH mg/hr '),
              fOp('× '),
              fAccent('${_formatDuration(segDurationH)} hr '),
              fOp('= '),
              fResult('$sodiumTotalMg mg'),
            ],
            isResultLine: true,
            showDividerBefore: true,
          ),
        ],
      ),
    ];
  }

  /// Transition fluid: fixed 300 ml (T1/T2 per spec). Shows the bolus math
  /// and the sodium derivation side-by-side for the sodium variant.
  List<CalculationSection> _buildTransitionFluidCalculationSections({
    required int waterMl,
    bool isT1 = true,
    bool useImperial = false,
  }) {
    // Spec `transparency_during_hydration.md` §T1 / T2 — show fixed bolus,
    // range band, and T1 vs T2 differentiation lines. Not body-weight
    // scaled (noted explicitly).
    final rangeLow = (waterMl * 0.80).round();
    final rangeHigh = (waterMl * 1.20).round();
    final transitionLabel = isT1 ? 'T1' : 'T2';
    return [
      CalculationSection(
        header: 'TRANSITION BOLUS',
        lines: [
          FormulaLine(
            [
              fAccent('$transitionLabel '),
              fOp('→ '),
              fResult('${_fmtMlAmount(waterMl, useImperial)} fixed'),
              fDim(' (sip, then go)'),
            ],
            stepNumber: '①',
          ),
          FormulaLine([
            fOp('range '),
            fOp('→ '),
            fDim(_fmtMlRange(rangeLow, rangeHigh, useImperial)),
          ]),
          FormulaLine([
            fOp(isT1 ? 'T1: ' : 'T2: '),
            fDim(
              isT1
                  ? 'bridges swim hydration gap + wetsuit heat'
                  : 'last easy window before run GI tolerance drops',
            ),
          ]),
          const FormulaLine([
            FormulaSegment('# ', style: SegmentStyle.op),
            FormulaSegment(
              'not body-weight scaled (conservative fixed bolus)',
              style: SegmentStyle.dim,
            ),
          ]),
        ],
      ),
    ];
  }

  List<CalculationSection> _buildTransitionSodiumCalculationSections({
    required int waterMl,
    required int concMgPerL,
    bool useImperial = false,
  }) {
    final sodium = ((waterMl / 1000) * concMgPerL).round();
    return [
      CalculationSection(
        header: 'TRANSITION SODIUM',
        lines: [
          FormulaLine([
            fAccent('${_sodiumSaltLabel(concMgPerL)} salt '),
            fOp('→ '),
            fDim('$concMgPerL mg/L'),
          ], stepNumber: '①'),
          FormulaLine([
            fAccent('${_fmtMlAmount(waterMl, useImperial)} '),
            fOp('× '),
            fDim('($concMgPerL ÷ 1000) '),
            fOp('= '),
            fResult('$sodium mg'),
          ], stepNumber: '②'),
        ],
      ),
    ];
  }

  /// Pre-workout fluid tier math.
  ///
  /// Tier detection prefers the authoritative `tier` (sourced from the edge
  /// function field `pre_run_hydration_tier`): 1 = body-weight scaled,
  /// 2 = fixed 250 ml top-up, 3 = no hydration. When [tier] is null
  /// (legacy plans / older offline paths), falls back to the historical
  /// fluid-magnitude heuristic — but note that heuristic mislabels low-BW
  /// Tier 1 athletes whose BW × 6 ml lands ≤ 300 ml.
  List<CalculationSection> _buildPreWorkoutFluidCalculationSections({
    required double bodyWeightKg,
    required int fluidsMl,
    required int? fluidsLowMl,
    required int? fluidsHighMl,
    int? tier,
    bool isGateFired = false,
    bool useImperial = false,
  }) {
    final bool isTier3 = tier != null ? tier == 3 : fluidsMl == 0;
    final bool isTier2 =
        tier != null ? tier == 2 : (!isTier3 && fluidsMl <= 300);

    // Gate-fired: short + mild workout → no plan needed.
    if (isGateFired) {
      return [
        CalculationSection(
          header: 'PRE-WORKOUT HYDRATION',
          lines: const [
            FormulaLine([
              FormulaSegment('no structured intake ', style: SegmentStyle.accent),
              FormulaSegment('→ ', style: SegmentStyle.op),
              FormulaSegment(
                'workout < 60 min + temp < 30°C → no protocol needed',
                style: SegmentStyle.dim,
              ),
            ], stepNumber: '①'),
          ],
        ),
      ];
    }

    // Too late: < 10 min before start → fluid won't absorb.
    if (isTier3) {
      return [
        CalculationSection(
          header: 'PRE-WORKOUT HYDRATION',
          lines: const [
            FormulaLine([
              FormulaSegment('no structured intake ', style: SegmentStyle.accent),
              FormulaSegment('→ ', style: SegmentStyle.op),
              FormulaSegment(
                '< 10 min pre-start — fluid won\'t absorb in time',
                style: SegmentStyle.dim,
              ),
            ], stepNumber: '①'),
          ],
        ),
      ];
    }

    // Short window — fixed 250 ml top-up.
    if (isTier2) {
      return [
        CalculationSection(
          header: 'PRE-WORKOUT HYDRATION',
          lines: [
            const FormulaLine([
              FormulaSegment('10–120 min window ', style: SegmentStyle.accent),
              FormulaSegment('→ ', style: SegmentStyle.op),
              FormulaSegment('fixed top-up', style: SegmentStyle.accent),
            ], stepNumber: '①'),
            FormulaLine([
              fAccent('fixed top-up '),
              fOp('= '),
              fResult('${_fmtMlAmount(fluidsMl, useImperial)} '),
              fDim('[${_fmtMlRange(fluidsLowMl ?? 200, fluidsHighMl ?? 300, useImperial)}]'),
            ], stepNumber: '②'),
            const FormulaLine([
              FormulaSegment('→ ', style: SegmentStyle.op),
              FormulaSegment('not enough time for full protocol; rely on during-workout',
                  style: SegmentStyle.dim),
            ]),
          ],
        ),
      ];
    }

    // Full ACSM protocol — body-weight scaled.
    final mlPerKg = bodyWeightKg > 0
        ? (fluidsMl / bodyWeightKg).toStringAsFixed(1)
        : '6.0';
    return [
      CalculationSection(
        header: 'PRE-WORKOUT HYDRATION',
        lines: [
          const FormulaLine([
            FormulaSegment('≥ 2 hr window ', style: SegmentStyle.accent),
            FormulaSegment('→ ', style: SegmentStyle.op),
            FormulaSegment('full ACSM protocol (body-weight scaled)', style: SegmentStyle.accent),
          ], stepNumber: '①'),
          FormulaLine([
            fAccent('body weight '),
            fDim('${bodyWeightKg.round()} kg '),
            fOp('× '),
            fDim('$mlPerKg ml/kg '),
            fOp('= '),
            fResult('${_fmtMlAmount(fluidsMl, useImperial)} '),
            fDim('[${_fmtMlRange(fluidsLowMl ?? (bodyWeightKg * 5).round(), fluidsHighMl ?? (bodyWeightKg * 7).round(), useImperial)}]'),
          ], stepNumber: '②'),
        ],
      ),
    ];
  }

  /// Pre-workout sodium time-window math. Uses time-window language, not
  /// internal tier labels.
  List<CalculationSection> _buildPreWorkoutSodiumCalculationSections({
    required int sodiumMg,
    required int? sodiumLowMg,
    required int? sodiumHighMg,
    bool isGateFired = false,
    bool useImperial = false,
  }) {
    if (sodiumMg == 0) {
      final reasonText = isGateFired
          ? 'workout < 60 min + mild — drink-to-thirst with meals'
          : '< 10 min pre-start — no sodium needed';
      return [
        CalculationSection(
          header: 'PRE-WORKOUT SODIUM',
          lines: [
            FormulaLine([
              const FormulaSegment('no structured sodium ', style: SegmentStyle.accent),
              const FormulaSegment('→ ', style: SegmentStyle.op),
              FormulaSegment(reasonText, style: SegmentStyle.dim),
            ], stepNumber: '①'),
          ],
        ),
      ];
    }

    // ≥ 2 hr window (~450 mg) vs 10–120 min window (~150 mg): cutoff at 300 mg.
    final isFullProtocol = sodiumMg >= 300;
    final windowLabel =
        isFullProtocol ? '≥ 2 hr window' : '10–120 min window';
    final header = 'PRE-WORKOUT SODIUM';
    return [
      CalculationSection(
        header: header,
        lines: [
          FormulaLine([
            fAccent('$windowLabel '),
            fOp('→ '),
            fAccent(isFullProtocol ? 'full ACSM protocol' : 'short-window top-up'),
          ], stepNumber: '①'),
          FormulaLine([
            fAccent('fixed sodium '),
            fOp('= '),
            fResult('$sodiumMg mg '),
            fDim('[${sodiumLowMg ?? (isFullProtocol ? 300 : 100)}–${sodiumHighMg ?? (isFullProtocol ? 600 : 200)} mg]'),
          ], stepNumber: '②'),
          FormulaLine([
            fOp('→ '),
            fDim(isFullProtocol
                ? 'retains consumed fluid; aligns with ACSM 300–600 mg window'
                : 'keeps the ${_fmtMlAmount(250, useImperial)} in your body until start'),
          ]),
        ],
      ),
    ];
  }

  // ---------------------------------------------------------------------------
  // DURING SINGLE SPORT FLUID
  // ---------------------------------------------------------------------------

}
