// GENERATED by split of macro_explanation_service.dart — DO NOT hand-edit
// Fluid transparency data builders

part of 'macro_explanation_service.dart';

extension _$FluidExt on MacroExplanationService {
  NutrientTransparencyData _preWorkoutFluidTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final pre = macroTargets.preRun;
    final fluidsMl = pre.fluidsMl.round();
    final rangeLowMl = pre.fluidsLowMl?.round() ?? (fluidsMl * 0.8).round();
    final rangeHighMl = pre.fluidsHighMl?.round() ?? (fluidsMl * 1.2).round();

    // Determine tier from time (estimate from fluid value: 250mL = Tier 2, BW-based = Tier 1)
    // Tier 3 = 0 ml, Tier 2 = ~250 ml, Tier 1 = BW * 5–7 ml
    final isTier3 = fluidsMl == 0;
    final isTier2 = !isTier3 && (fluidsMl <= 300);
    final String blurb;
    final List<FormulaLine> tldrLines;

    if (isTier3) {
      blurb = 'Too late for structured pre-hydration. A few small sips are fine '
          'for comfort, but fluid taken now won\'t absorb before exercise begins. '
          'Focus on the during-workout plan instead.';
      tldrLines = const [];
    } else if (isTier2) {
      blurb = 'Not enough time for the full protocol. 250 ml is all that can '
          'meaningfully absorb before exercise begins. Sip it steadily \u2014 '
          'don\'t chug it just before you start.';
      tldrLines = [
        FormulaLine([
          fAccent('fixed top-up '),
          fOp('= '),
          fResult('${fluidsMl}mL'),
        ]),
      ];
    } else {
      blurb = 'The goal before a workout is to start **euhydrated** \u2014 at your '
          'normal baseline, not loaded or depleted. With enough time available, '
          'you have time for the full protocol: sip ${fluidsMl}mL gradually, let '
          'it absorb, and aim for pale yellow urine before you head out.';
      final mlPerKg = bodyWeightKg > 0
          ? (fluidsMl / bodyWeightKg).toStringAsFixed(1)
          : '6.0';
      tldrLines = [
        FormulaLine([
          fAccent('body weight '),
          fOp('\u00d7 '),
          fAccent('${mlPerKg} mL/kg '),
          fOp('= '),
          fResult('${fluidsMl}mL'),
        ]),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF), // blue
      primaryUnit: useImperial ? 'oz' : 'mL',
      phase: 'before',
      tldrBody: blurb,
      tldrLines: tldrLines,
      storySections: _preWorkoutFluidStorySections(isTier3: isTier3),
      calculationSections: _buildPreWorkoutFluidCalculationSections(
        bodyWeightKg: bodyWeightKg,
        fluidsMl: fluidsMl,
        fluidsLowMl: rangeLowMl,
        fluidsHighMl: rangeHighMl,
      ),
      videoTitle: 'Watch: Pre-Workout Hydration',
      targetGrams: fluidsMl.toDouble(),
      rangeLow: rangeLowMl.toDouble(),
      rangeHigh: rangeHighMl.toDouble(),
      sportLabel: 'Pre-Workout',
    );
  }

  List<StorySection> _preWorkoutFluidStorySections({
    required bool isTier3,
  }) {
    return [
      const StorySection(
        question: 'What does "euhydrated" mean?',
        answer:
            'Euhydration is your normal, well-hydrated baseline \u2014 neither '
            'dehydrated nor over-hydrated. The goal before a workout is to arrive '
            'at that baseline, not to "water load" beyond it. Excess fluid without '
            'sodium is excreted quickly and doesn\'t help performance.',
        citation: 'Sawka et al. (2007) \u2014 ACSM Position Stand on Exercise and Fluid Replacement',
        dataChips: ['Pre-hydration goal \u00b7 euhydration, not loading'],
      ),
      const StorySection(
        question: 'Why does sodium matter before a workout?',
        answer:
            'Pre-workout sodium keeps the fluid you drink in your body rather than '
            'sending it straight to your bladder. Without sodium, much of what you '
            'consume before exercise is excreted before you even start.',
        citation: 'Maughan & Shirreffs (2008) \u2014 European Journal of Sport Science',
      ),
      if (!isTier3)
        const StorySection(
          question: 'What\'s the range based on?',
          answer:
              'The ACSM recommends **5\u20137 mL/kg** of body weight as a pre-workout '
              'fluid protocol for the 2\u20134 hour window. The specific amount within '
              'that range adjusts for your weight and the timing of your meal.',
          citation: 'Sawka et al. (2007) \u2014 ACSM Position Stand; range: 5\u20137 mL/kg',
          dataChips: ['5 mL/kg \u00b7 lower bound', '6 mL/kg \u00b7 target', '7 mL/kg \u00b7 upper bound'],
        ),
    ];
  }

  // ---------------------------------------------------------------------------
  // FLUID MAP BUILDERS — assemble per-scenario maps
  // ---------------------------------------------------------------------------

  /// Builds the fluid [Map<Scenario, NutrientTransparencyData>] for a
  /// single-sport (non-brick) during workout.
  Map<Scenario, NutrientTransparencyData> _singleSportFluidMap({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationMin = macroTargets.metrics.durationMin.round();
    final isTested = during.isTested;
    final shortWorkoutGate = durationMin < 60 &&
        (during.tempC == null || (during.tempC ?? 25) < 30);

    final map = <Scenario, NutrientTransparencyData>{};

    // Single sport is always present
    map[Scenario.singleSport] = _duringSingleSportFluidTransparency(
      macroTargets: macroTargets,
      bodyWeightKg: bodyWeightKg,
      useImperial: useImperial,
    );

    // Short workout gate — different blurb, same numbers
    if (shortWorkoutGate) {
      map[Scenario.shortWorkout] = _shortWorkoutFluidTransparency(
        macroTargets: macroTargets,
        useImperial: useImperial,
      );
    }

    // Known-rate — different blurb emphasising the tested override
    if (isTested) {
      map[Scenario.knownRate] = _knownRateFluidTransparency(
        macroTargets: macroTargets,
        bodyWeightKg: bodyWeightKg,
        useImperial: useImperial,
      );
    }

    return map;
  }

  /// Builds the fluid [Map<Scenario, NutrientTransparencyData>] for a
  /// brick/tri segment (non-swim) during workout.
  Map<Scenario, NutrientTransparencyData> _brickSegmentFluidMap({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final isTested = segment.isTested;
    final hasRedistribution = [
      ...macroTargets.duringRun.safetyFlags,
      ...segment.safetyFlags,
    ].any((f) => f.toLowerCase().contains('redistri'));

    final map = <Scenario, NutrientTransparencyData>{};

    // Multi-segment is always present for bricks
    map[Scenario.multiSegment] = _brickSegmentFluidTransparency(
      macroTargets: macroTargets,
      segment: segment,
      bodyWeightKg: bodyWeightKg,
      useImperial: useImperial,
    );

    // Redistribution — only when run leg hit GI ceiling
    if (hasRedistribution) {
      map[Scenario.redistribution] = _redistributionFluidTransparency(
        macroTargets: macroTargets,
        segment: segment,
        bodyWeightKg: bodyWeightKg,
        useImperial: useImperial,
      );
    }

    // Known-rate
    if (isTested) {
      map[Scenario.knownRate] = _knownRateFluidTransparency(
        macroTargets: macroTargets,
        bodyWeightKg: 0, // weight not shown in brick-segment known-rate blurb
        useImperial: useImperial,
        forBrickSegment: segment,
      );
    }

    return map;
  }

  // ---------------------------------------------------------------------------
  // DURING SINGLE SPORT FLUID — known-rate variant
  // ---------------------------------------------------------------------------

  /// Returns a Fluids transparency card with copy emphasising the known-rate
  /// (sweat-test) override. Numbers are identical to [singleSport].
  NutrientTransparencyData _knownRateFluidTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
    BrickSegmentMacroTarget? forBrickSegment,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final fluidRateMlH = forBrickSegment != null
        ? (forBrickSegment.durationMinutes > 0
            ? (forBrickSegment.waterMl /
                    (forBrickSegment.durationMinutes / 60.0))
                .round()
            : 0)
        : during.fluidRateMlPerH.round();
    final fluidTotalMl = forBrickSegment != null
        ? forBrickSegment.waterMl.round()
        : during.fluidTotalMl.round();
    final effectiveSweatRate =
        forBrickSegment?.effectiveSweatRateLPerH ?? during.effectiveSweatRateLPerH;
    final replacementPct =
        forBrickSegment?.replacementPercent ?? during.replacementPercent;
    final floorMlH = forBrickSegment?.floorMlPerH ?? during.floorMlPerH;
    final ceilingMlH = forBrickSegment?.ceilingMlPerH ?? during.ceilingMlPerH;
    final fluidsLowMl =
        forBrickSegment?.waterLowMl ?? during.fluidsLowMl;
    final fluidsHighMl =
        forBrickSegment?.waterHighMl ?? during.fluidsHighMl;

    final List<FormulaLine> tldrLines;
    if (effectiveSweatRate != null && replacementPct != null) {
      final replacePctPct = (replacementPct * 100).round();
      final ceilNote = ceilingMlH != null ? '$ceilingMlH mL/hr' : 'GI ceiling';
      final floorNote = floorMlH != null ? '$floorMlH mL/hr' : '2% BW floor';
      tldrLines = [
        FormulaLine([
          fAccent('TESTED rate '),
          fDim('${effectiveSweatRate.toStringAsFixed(2)} L/hr '),
          fOp('\u00d7 '),
          fAccent('replacement '),
          fDim('${replacePctPct}% '),
          fOp('= '),
          fDim('$fluidRateMlH mL/hr'),
        ], stepNumber: '\u2460'),
        if (floorMlH != null)
          FormulaLine([
            fOp('\u2193 '),
            fAccent('floor '),
            fDim(floorNote),
          ], stepNumber: '\u2462'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim(ceilNote),
          ], stepNumber: '\u2463'),
        FormulaLine(
          [
            fAccent('$fluidRateMlH mL/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(forBrickSegment != null ? forBrickSegment.durationMinutes / 60.0 : durationH)} hr '),
            fOp('= '),
            fResult('${fluidTotalMl}mL'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('TESTED $fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(forBrickSegment != null ? forBrickSegment.durationMinutes / 60.0 : durationH)} hr '),
          fOp('= '),
          fResult('${fluidTotalMl}mL'),
        ], isResultLine: true),
      ];
    }

    final knownRateCalcSections = _buildDuringFluidCalculationSections(
      during: during,
      durationMin: macroTargets.metrics.durationMin.round(),
      durationH: durationH,
      bodyWeightKg: bodyWeightKg,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: true,
      tldrBody: 'Your fluid target is based on your **personal sweat test** result. '
          'The tested rate overrode the category lookup (Light/Medium/Heavy) — '
          'this is the most accurate input available. Floor and ceiling limits '
          'still apply to keep you in a safe range.',
      tldrLines: tldrLines,
      calculationSections: knownRateCalcSections,
      calculationWarning: during.safetyFlags.isNotEmpty
          ? during.safetyFlags.first
          : null,
      storySections: [
        const StorySection(
          question: 'How was the known rate applied?',
          answer:
              'Instead of using the Light/Medium/Heavy sweat-rate category lookup, '
              'your personal tested rate was used as the base input to the effective '
              'sweat rate calculation. Environmental multipliers (temperature, humidity, '
              'indoor) were still applied on top of your tested rate.',
          citation: 'Precision Fuel & Hydration / TrainingPeaks \u2014 standard at-home sweat test protocol',
          dataChips: ['TESTED \u2713 \u00b7 personal sweat test'],
        ),
        const StorySection(
          question: 'How do I update my tested rate?',
          answer:
              'Go to Settings \u2192 Sweat Profile to enter or update your known sweat '
              'rate. After saving, regenerate this activity\'s plan to see updated '
              'recommendations. Re-test every season or when conditions change significantly.',
          inlineEditType: InlineEditType.knownSweatRate,
          dataChips: ['TESTED \u2713 \u00b7 overrides category'],
        ),
        const StorySection(
          question: 'What if conditions are very different from my test?',
          answer:
              'Your tested rate is calibrated to the conditions of your test '
              '(temperature, humidity). If today\'s conditions differ significantly, '
              'the environmental multipliers partially adjust. For the most accuracy, '
              'run a test under similar conditions to your target event.',
          citation: 'Barnes & Baker (2019) \u2014 sweat rate variability',
          dataChips: ['Temp coefficient \u00b7 4%/\u00b0C', 'Humidity \u00b7 +2% above 50%'],
        ),
      ],
      videoTitle: 'Watch: Hydration Strategy',
      targetGrams: fluidTotalMl.toDouble(),
      rangeLow: fluidsLowMl,
      rangeHigh: fluidsHighMl,
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // SHORT WORKOUT FLUID — gate-applied variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _shortWorkoutFluidTransparency({
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final fluidTotalMl = during.fluidTotalMl.round();
    final durationH = macroTargets.metrics.durationH;
    final fluidsLowMl = during.fluidsLowMl;
    final fluidsHighMl = during.fluidsHighMl;

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: during.isTested,
      tldrBody: 'This workout is short and conditions are mild \u2014 no structured '
          'hydration plan needed. **Drink to thirst.** If you want a number, '
          'aim for no more than 10 oz. Don\'t exceed 20 oz.',
      tldrLines: [
        FormulaLine([
          fAccent('short gate '),
          fOp('= '),
          fAccent('duration < 60 min + mild temp '),
          fOp('\u2192 '),
          fDim('drink to thirst'),
        ]),
        FormulaLine(
          [
            fAccent('$fluidRateMlH mL/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${fluidTotalMl}mL'),
            fDim(' (conservative max)'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ],
      calculationSections: [
        CalculationSection(
          header: 'SHORT-WORKOUT GATE',
          lines: [
            FormulaLine([
              fAccent('duration '),
              fDim('${macroTargets.metrics.durationMin.round()} min '),
              fOp('< 60 '),
              fOp('AND '),
              fAccent('temp '),
              fDim('${during.tempC?.toStringAsFixed(0) ?? '22'}°C '),
              fOp('< 30 '),
              fOp('→ '),
              fAccent('gate fires'),
            ], stepNumber: '①'),
            FormulaLine([
              fOp('→ '),
              fDim('drink to thirst; conservative cap = 30% of sweat rate'),
            ], stepNumber: '②'),
            FormulaLine(
              [
                fAccent('$fluidRateMlH ml/hr '),
                fOp('× '),
                fAccent('${_formatDuration(durationH)} hr '),
                fOp('= '),
                fResult('$fluidTotalMl ml '),
                fDim('(conservative max)'),
              ],
              isResultLine: true,
              showDividerBefore: true,
            ),
          ],
        ),
      ],
      storySections: [
        const StorySection(
          question: 'Why "drink to thirst" for short workouts?',
          answer:
              'For efforts under 60 minutes in mild conditions, the body\'s thirst '
              'mechanism is an accurate guide. You cannot meaningfully deplete '
              'hydration status in that time window under normal temperatures. '
              'A structured plan adds complexity without benefit.',
          citation: 'Noakes (2012) \u2014 Hyponatremia in endurance sports',
          dataChips: [
            'Short gate \u00b7 < 60 min + temp < 30\u00b0C',
            'Gate bypassed \u00b7 if temp \u2265 30\u00b0C',
          ],
        ),
        const StorySection(
          question: 'Why is there still a number shown?',
          answer:
              'The plan shows a conservative ceiling of 30% sweat-loss replacement '
              'so you have a reference if you prefer structure. **Do not exceed 20 oz '
              '(600 mL).** Over-drinking during short workouts is a real risk of '
              'exercise-associated hyponatremia.',
          citation: 'Hew-Butler et al. (2015) \u2014 Clinical Journal of Sport Medicine',
          dataChips: ['Max \u00b7 20 oz / 600 mL', 'Replacement \u00b7 30% (soft, gated)'],
        ),
      ],
      videoTitle: 'Watch: Hydration Strategy',
      targetGrams: fluidTotalMl.toDouble(),
      rangeLow: fluidsLowMl,
      rangeHigh: fluidsHighMl,
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // REDISTRIBUTION FLUID — bike absorbed run shortfall variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _redistributionFluidTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final durationH = segment.durationMinutes / 60.0;
    final totalEventMin = macroTargets.metrics.durationMin.round();
    final waterMl = segment.waterMl.round();
    final effectiveSweatRate = segment.effectiveSweatRateLPerH;
    final replacementPct = segment.replacementPercent;
    final fluidRateMlH =
        durationH > 0 ? (waterMl / durationH).round() : 0;
    final ceilingMlH = segment.ceilingMlPerH;
    final fluidsLowMl = segment.waterLowMl;
    final fluidsHighMl = segment.waterHighMl;

    final List<FormulaLine> tldrLines;
    if (effectiveSweatRate != null && replacementPct != null) {
      final replacePctPct = (replacementPct * 100).round();
      tldrLines = [
        FormulaLine([
          fAccent('total event '),
          fDim('${totalEventMin} min '),
          fOp('\u2192 '),
          fAccent('replacement '),
          fDim('${replacePctPct}%'),
        ], stepNumber: '\u2460'),
        FormulaLine([
          fOp('# '),
          fAccent('redistribution '),
          fDim('run shortfall \u2192 bike'),
        ], stepNumber: '\u2461'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim('$ceilingMlH mL/hr '),
            fOp('(bike GI limit)'),
          ], stepNumber: '\u2462'),
        FormulaLine(
          [
            fAccent('$fluidRateMlH mL/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${waterMl}mL'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fOp('# '),
          fAccent('redistribution '),
          fDim('run shortfall \u2192 bike'),
        ]),
        FormulaLine([
          fAccent('$fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${waterMl}mL'),
        ], isResultLine: true, showDividerBefore: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: segment.isTested,
      tldrBody:
          'In a race or brick, the replacement strategy is based on '
          '**total event duration** \u2014 not just this leg. When the run leg '
          'can\'t absorb enough to stay within 2% body weight loss, the shortfall '
          'is redistributed here where your gut has more capacity.',
      tldrLines: tldrLines,
      calculationSections: _buildBrickFluidCalculationSections(
        during: macroTargets.duringRun,
        segment: segment,
        totalEventMin: totalEventMin,
        bodyWeightKg: bodyWeightKg,
        showRedistributionNote: true,
      ),
      calculationWarning: segment.safetyFlags.isNotEmpty
          ? segment.safetyFlags.first
          : null,
      storySections: [
        const StorySection(
          question: 'What is run\u2192bike redistribution?',
          answer:
              'When the run segment\'s recommended intake exceeds its 800 mL/hr GI '
              'ceiling, the unabsorbable portion is redistributed to the bike leg '
              '(which can handle up to 1200 mL/hr). This maximises fluid delivery '
              'across the full event while respecting each sport\'s absorption limit.',
          citation: 'Pfeiffer et al. (2012) \u2014 GI Problems in Endurance Sports',
          dataChips: [
            'Run GI ceiling \u00b7 800 mL/hr',
            'Bike GI ceiling \u00b7 1200 mL/hr',
            'Redistribution \u00b7 # flag',
          ],
        ),
        const StorySection(
          question: 'Why can\'t I just drink more on the run?',
          answer:
              'The running GI ceiling is a hard physiological limit \u2014 running\'s '
              'vertical impact dramatically reduces gut motility. Exceeding 800 mL/hr '
              'during running leads to bloating, nausea, and slowed pace far more '
              'reliably than it leads to better hydration.',
          dataChips: ['Run \u00b7 max 800 mL/hr (GI limit)', 'Bike \u00b7 max 1200 mL/hr'],
        ),
      ],
      videoTitle: 'Watch: Hydration Strategy',
      targetGrams: waterMl.toDouble(),
      rangeLow: fluidsLowMl,
      rangeHigh: fluidsHighMl,
      sportLabel: segment.sport,
    );
  }

  // ---------------------------------------------------------------------------
  // CALCULATION SECTION BUILDERS — step-by-step breakdown for the UI accordion
  //
  // The edge function already performs all these calculations, but for the
  // transparency UI we recompute the intermediate multipliers so we can
  // display them as numbered steps. Derivation is:
  //   effective = base × temp_mult × humidity_mult × indoor_mult  (clamped)
  //   base = effective / (temp_mult × humidity_mult × indoor_mult)
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _duringSingleSportFluidTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final durationMin = macroTargets.metrics.durationMin.round();
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final fluidTotalMl = during.fluidTotalMl.round();

    // Use derivation fields if available (new plans); fall back gracefully
    final effectiveSweatRate = during.effectiveSweatRateLPerH;
    final replacementPct = during.replacementPercent;
    final floorMlH = during.floorMlPerH;
    final ceilingMlH = during.ceilingMlPerH;
    final safetyFlags = during.safetyFlags;
    final isTested = during.isTested;

    final shortWorkoutGate = durationMin < 60 &&
        (during.tempC == null || (during.tempC ?? 25) < 30);

    final List<FormulaLine> tldrLines;
    final String blurb;

    if (shortWorkoutGate && fluidRateMlH < 200) {
      // Short-workout gate
      blurb =
          'This workout is short and conditions are mild \u2014 no structured '
          'hydration plan needed. **Drink to thirst.** If you want a number, '
          'aim for no more than 10 oz. Don\'t exceed 20 oz.';
      tldrLines = [
        FormulaLine([
          fAccent('short gate '),
          fOp('= '),
          fAccent('duration < 60 min + mild temp '),
          fOp('\u2192 '),
          fDim('drink to thirst'),
        ]),
      ];
    } else if (effectiveSweatRate != null && replacementPct != null) {
      // New derivation fields available
      blurb =
          'Your fluid target starts with a duration-based replacement strategy, '
          'then two overrides are applied: a **floor** that raises the target if '
          'needed to keep you within 2% body weight loss, and a **ceiling** that '
          'caps it at what your gut can absorb and what\'s safe for blood sodium. '
          'The final recommendation is always between those two bounds.';

      final replacePctPct = (replacementPct * 100).round();
      final ceilNote = ceilingMlH != null
          ? '${ceilingMlH} mL/hr'
          : 'GI ceiling';
      final floorNote = floorMlH != null ? '${floorMlH} mL/hr' : '2% BW floor';

      tldrLines = [
        FormulaLine([
          fAccent('${durationMin} min '),
          fOp('\u2192 '),
          fAccent('replacement '),
          fDim('${replacePctPct}%'),
        ], stepNumber: '\u2460'),
        FormulaLine([
          fAccent('sweat rate '),
          fDim('${effectiveSweatRate.toStringAsFixed(2)} L/hr '),
          fOp('\u00d7 '),
          fAccent('${replacePctPct}% '),
          fOp('= '),
          fDim('${fluidRateMlH} mL/hr'),
        ], stepNumber: '\u2461'),
        if (floorMlH != null)
          FormulaLine([
            fOp('\u2193 '),
            fAccent('floor '),
            fDim(floorNote),
            fOp(' (2% BW deficit)'),
          ], stepNumber: '\u2462'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim(ceilNote),
            fOp(' (GI limit)'),
          ], stepNumber: '\u2463'),
        if (safetyFlags.isNotEmpty)
          FormulaLine([
            fOp('\u2713 '),
            fAccent('safety '),
            fDim(safetyFlags.first),
          ]),
        FormulaLine(
          [
            fAccent('$fluidRateMlH mL/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${fluidTotalMl}mL'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      // Legacy plan — simple card
      blurb =
          'Your fluid target replaces a portion of your sweat losses during '
          'activity, keeping you within a safe hydration window.';
      tldrLines = [
        FormulaLine([
          fAccent('${fluidRateMlH} mL/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${fluidTotalMl}mL'),
        ], isResultLine: true),
      ];
    }

    final fluidsLowMl = during.fluidsLowMl;
    final fluidsHighMl = during.fluidsHighMl;

    final calcSections = _buildDuringFluidCalculationSections(
      during: during,
      durationMin: durationMin,
      durationH: durationH,
      bodyWeightKg: bodyWeightKg,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody: blurb,
      tldrLines: tldrLines,
      calculationSections: calcSections,
      calculationWarning: safetyFlags.isNotEmpty ? safetyFlags.first : null,
      storySections: _duringFluidStorySections(
        isTested: isTested,
        shortWorkoutGate: shortWorkoutGate,
        hasDerivationFields: effectiveSweatRate != null,
      ),
      videoTitle: 'Watch: Hydration Strategy',
      targetGrams: fluidTotalMl.toDouble(),
      rangeLow: fluidsLowMl,
      rangeHigh: fluidsHighMl,
      sportLabel: null,
    );
  }

  List<StorySection> _duringFluidStorySections({
    required bool isTested,
    required bool shortWorkoutGate,
    required bool hasDerivationFields,
  }) {
    return [
      if (shortWorkoutGate)
        const StorySection(
          question: 'Why "drink to thirst" for short workouts?',
          answer:
              'For efforts under 60 minutes in mild conditions, the body\'s thirst '
              'mechanism is an accurate guide. You cannot meaningfully deplete '
              'hydration status in that time window under normal temperatures.',
          citation: 'Noakes (2012) \u2014 Hyponatremia in endurance sports',
          dataChips: ['Short gate \u00b7 < 60 min + temp < 30\u00b0C'],
        ),
      const StorySection(
        question: 'Why replace a percentage of sweat losses, not all of it?',
        answer:
            'Replacing 100% of sweat losses during exercise can lead to '
            '**hyponatremia** (dangerously low blood sodium) by diluting the '
            'sodium remaining in your blood. Research shows 50\u201380% replacement '
            'is optimal, scaled up with event duration.',
        citation: 'Baker (2017) \u2014 Journal of the International Society of Sports Nutrition',
        dataChips: [
          '<60 min \u00b7 30%',
          '60\u201390 min \u00b7 50%',
          '90\u2013150 min \u00b7 60%',
          '150\u2013240 min \u00b7 70%',
          '240+ min \u00b7 80%',
        ],
      ),
      const StorySection(
        question: 'What is the 2% body weight floor?',
        answer:
            'Losing more than 2% of body weight through sweat starts to impair '
            'performance. The floor ensures your recommended rate is high enough '
            'to stay within that safety boundary, **even if the replacement % alone '
            'would leave you too depleted.**',
        citation: 'Sawka et al. (2007) \u2014 ACSM Position Stand',
        dataChips: ['>2% BW deficit \u00b7 performance impact', '>3% BW deficit \u00b7 significant risk'],
      ),
      const StorySection(
        question: 'What is the GI ceiling?',
        answer:
            'Your gut can only absorb so much fluid per hour. Drinking above '
            'the ceiling causes GI distress without improving hydration. '
            'Running\'s mechanical impact restricts absorption more than cycling.',
        citation: 'Pfeiffer et al. (2012) \u2014 GI Problems in Endurance Sports',
        dataChips: [
          'Run \u00b7 max 800 mL/hr',
          'Bike \u00b7 max 1200 mL/hr',
        ],
      ),
      StorySection(
        question: 'What\'s my actual sweat rate?',
        answer: isTested
            ? 'Your sweat rate is from a **personal sweat test** \u2014 the most '
                'accurate input available. This rate already accounts for your '
                'individual physiology. If conditions differ significantly from your '
                'test conditions, consider retesting.'
            : 'Your sweat rate is estimated from your sweat profile category and '
                'adjusted for temperature, humidity, and indoor conditions. '
                'For a more accurate number, weigh yourself nude before and after '
                'a known-duration workout and enter the result below.',
        citation: isTested
            ? null
            : 'Precision Fuel & Hydration / TrainingPeaks \u2014 standard at-home sweat test protocol',
        inlineEditType: InlineEditType.knownSweatRate,
        dataChips: isTested
            ? ['TESTED \u2713 \u00b7 personal sweat test']
            : [
                'Light \u00b7 0.90 L/hr',
                'Medium \u00b7 1.28 L/hr',
                'Heavy \u00b7 1.66 L/hr',
              ],
      ),
    ];
  }

  // ---------------------------------------------------------------------------
  // BRICK SEGMENT FLUID
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickSegmentFluidTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final segmentSport = segment.sport;
    final durationMin = segment.durationMinutes;
    final durationH = durationMin / 60.0;
    final totalEventMin = macroTargets.metrics.durationMin.round();

    // Segment water total
    final waterMl = segment.waterMl.round();

    // Derivation fields (segment level if available)
    final effectiveSweatRate = segment.effectiveSweatRateLPerH;
    final replacementPct = segment.replacementPercent;
    final floorMlH = segment.floorMlPerH;
    final ceilingMlH = segment.ceilingMlPerH;
    final isTested = segment.isTested;

    // Rate from segment totals
    final fluidRateMlH = durationH > 0
        ? (waterMl / durationH).round()
        : 0;

    final List<FormulaLine> tldrLines;
    final String blurb =
        'In a race or brick, the replacement strategy is based on '
        '**total event duration** \u2014 not just this leg. When the run leg '
        'can\'t absorb enough to stay within 2% body weight loss, the shortfall '
        'is redistributed here where your gut has more capacity.';

    if (effectiveSweatRate != null && replacementPct != null) {
      final replacePctPct = (replacementPct * 100).round();
      tldrLines = [
        FormulaLine([
          fAccent('total event '),
          fDim('${totalEventMin} min '),
          fOp('\u2192 '),
          fAccent('replacement '),
          fDim('${replacePctPct}%'),
        ], stepNumber: '\u2460'),
        FormulaLine([
          fAccent('sweat rate '),
          fDim('${effectiveSweatRate.toStringAsFixed(2)} L/hr '),
          fOp('\u00d7 '),
          fAccent('${replacePctPct}% '),
          fOp('= '),
          fDim('$fluidRateMlH mL/hr'),
        ], stepNumber: '\u2461'),
        if (floorMlH != null)
          FormulaLine([
            fOp('\u2193 '),
            fAccent('floor '),
            fDim('$floorMlH mL/hr'),
          ], stepNumber: '\u2462'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim('$ceilingMlH mL/hr '),
            fOp('(${segmentSport} limit)'),
          ], stepNumber: '\u2463'),
        FormulaLine(
          [
            fAccent('$fluidRateMlH mL/hr '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult('${waterMl}mL'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      // Legacy fallback
      tldrLines = [
        FormulaLine([
          fAccent('$fluidRateMlH mL/hr '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult('${waterMl}mL'),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody: blurb,
      tldrLines: tldrLines,
      calculationSections: _buildBrickFluidCalculationSections(
        during: macroTargets.duringRun,
        segment: segment,
        totalEventMin: totalEventMin,
        bodyWeightKg: bodyWeightKg,
      ),
      calculationWarning: segment.safetyFlags.isNotEmpty
          ? segment.safetyFlags.first
          : null,
      storySections: _duringFluidStorySections(
        isTested: isTested,
        shortWorkoutGate: false,
        hasDerivationFields: effectiveSweatRate != null,
      ),
      videoTitle: 'Watch: Hydration Strategy',
      targetGrams: waterMl.toDouble(),
      rangeLow: segment.waterLowMl,
      rangeHigh: segment.waterHighMl,
      sportLabel: segmentSport,
    );
  }

  // ---------------------------------------------------------------------------
  // SWIM FLUID — zero state
  // ---------------------------------------------------------------------------

  /// Public accessor so the sheet can request the swim zero-state directly
  /// without going through the map-returning [getFluidTransparencyData].
  NutrientTransparencyData _swimFluidTransparency() {
    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: 'mL/hr',
      phase: 'during',
      tldrBody:
          'No drinking during swim \u2014 T1 covers the deficit. '
          'Your sweat losses during the swim are accounted for in the '
          'total-event fluid budget and distributed across the bike and '
          'T1 transition windows.',
      tldrLines: const [],
      storySections: const [
        StorySection(
          question: 'Why no drinking during swim?',
          answer:
              'It is physically impossible to drink during an open-water or pool '
              'swim without stopping. Sweat losses during swimming are also lower '
              '(~0.4\u00d7 land sports) due to water cooling the skin. '
              'The fluid deficit from the swim is fully accounted for in the '
              'T1 transition and subsequent bike segment targets.',
          citation: 'Maughan & Shirreffs (2004) \u2014 swimming thermoregulation',
          dataChips: ['Swim sweat modifier \u00b7 0.4\u00d7 land sports'],
        ),
        StorySection(
          question: 'What covers the swim deficit?',
          answer:
              'T1 transition provides a fixed 300 mL bolus timed for what you can '
              'comfortably take in during a 2\u20135 minute transition stop. The bike '
              'leg then carries the remainder of the total-event fluid budget.',
          dataChips: ['T1 bolus \u00b7 300 mL fixed'],
        ),
      ],
      isSwimZero: true,
      swimCallout: 'Fluid deficit covered by: T1 transition \u00b7 Bike segment',
      targetGrams: 0,
      rangeLow: 0,
      rangeHigh: 0,
      sportLabel: 'Swim',
    );
  }

  // ---------------------------------------------------------------------------
  // TRANSITION FLUID
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _transitionFluidTransparency({
    required ExplanationPhase phase,
    required MacroTargets macroTargets,
  }) {
    final isT1 = phase == ExplanationPhase.transition1;
    final transitionName = isT1 ? 'T1' : 'T2';

    final transitions = macroTargets.brickPhaseTargets?.transitions;
    final tIdx = isT1 ? 0 : 1;
    final transition = (transitions != null && tIdx < transitions.length)
        ? transitions[tIdx]
        : null;
    final waterMl = transition?.waterMl.round() ?? 300;
    final isTested = transition?.isTested ?? false;

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: 'mL',
      phase: 'transition',
      isTested: isTested,
      tldrBody:
          'Transitions are brief, fixed hydration windows \u2014 not a '
          'calculated segment. The 300 mL target isn\'t derived from your sweat '
          'rate; it\'s a conservative bolus sized for what you can comfortably '
          'take in during a 2\u20135 minute stop. **$transitionName** '
          '${isT1 ? "bridges the swim gap and offsets wetsuit heat." : "is your last easy opportunity before running GI tolerance drops."}',
      tldrLines: [
        FormulaLine([
          fAccent('$transitionName '),
          fOp('= '),
          fAccent('fixed 300 mL '),
          fOp('\u2192 '),
          fResult('${waterMl}mL'),
        ]),
      ],
      calculationSections:
          _buildTransitionFluidCalculationSections(waterMl: waterMl),
      storySections: [
        StorySection(
          question: 'Why is the transition fluid fixed at 300 mL?',
          answer:
              'Transition windows are too short to calculate a precise sweat-rate-based '
              'target. 300 mL is a conservative bolus sized to what most athletes can '
              'comfortably consume and absorb during a 2\u20135 minute stop without '
              'causing GI distress when movement resumes.',
          citation: 'Consensus recommendation \u2014 USA Triathlon / ITU nutrition guidelines',
          dataChips: ['T1/T2 fixed \u00b7 300 mL', 'Confidence \u00b7 LOW'],
        ),
      ],
      targetGrams: waterMl.toDouble(),
      rangeLow: transition?.waterLowMl,
      rangeHigh: transition?.waterHighMl,
      sportLabel: transitionName,
    );
  }

  // ===========================================================================
  // SODIUM TRANSPARENCY
  // ===========================================================================

  /// Build structured transparency data for the Sodium card, keyed by [Scenario].
  ///
  /// Mirrors [getFluidTransparencyData] in structure. The [Scenario] keys in the
  /// returned map should be intersected with the fluid map's keys so both cards
  /// always show the same set of tabs.
}
