// GENERATED by split of macro_explanation_service.dart — DO NOT hand-edit
// Fluid transparency data builders

part of 'macro_explanation_service.dart';

// Conversion: 1 mL = 0.033814 fl oz. Used to pre-convert targetGrams /
// rangeLow / rangeHigh values in the fluid service when useImperial=true so
// the transparency card (which only knows the `unit` suffix) displays the
// right magnitude. See audit doc `docs/features/sodium_hydration/2026-04-22_audit.md`
// U1 for the bug this fixes (e.g. `1688mL` rendering as `1688oz`).
double _mlToDisplay(double ml, bool useImperial) =>
    useImperial ? (ml * 0.033814).roundToDouble() : ml;

double? _mlToDisplayOrNull(double? ml, bool useImperial) =>
    ml == null ? null : _mlToDisplay(ml, useImperial);

// ── Narrative/formula-line fluid-unit helpers ───────────────────────────────
// The structured targetGrams/rangeLow/rangeHigh fields above are already
// converted via _mlToDisplay, but the prose (tldrBody) and the step-by-step
// FormulaLine breakdowns embed their own literal "mL"/"ml" strings built
// from canonical mL ints. These helpers convert both the value AND the unit
// label so narrative text always matches the structured fields when
// useImperial is true. Only fluid volumes/rates (the user's personalized
// computed amounts) are touched here — physiological quantities (sodium mg,
// carb g/kg) and generic protocol/citation constants (ACSM "5-7 mL/kg", GI
// ceilings like "800 mL/hr") are intentionally left in metric since they
// describe the underlying research/protocol, not a personalized amount.
String _fluidUnit(bool useImperial) => useImperial ? 'oz' : 'mL';

String _fluidRateUnit(bool useImperial) => useImperial ? 'oz/hr' : 'mL/hr';

/// Formats a canonical mL amount (e.g. a fixed bolus or total) as a display
/// string in the user's preferred unit, e.g. `300 mL` or `10 oz`.
String _fmtMlAmount(num ml, bool useImperial) {
  final display = _mlToDisplay(ml.toDouble(), useImperial).round();
  return '$display ${_fluidUnit(useImperial)}';
}

/// Formats a canonical mL/hr rate as a display string in the user's
/// preferred unit, e.g. `645 mL/hr` or `22 oz/hr`.
String _fmtMlRate(num mlPerHour, bool useImperial) {
  final display = _mlToDisplay(mlPerHour.toDouble(), useImperial).round();
  return '$display ${_fluidRateUnit(useImperial)}';
}

/// Formats a canonical mL range (e.g. `200–300 mL`) as a display string in
/// the user's preferred unit.
String _fmtMlRange(num lowMl, num highMl, bool useImperial) {
  final low = _mlToDisplay(lowMl.toDouble(), useImperial).round();
  final high = _mlToDisplay(highMl.toDouble(), useImperial).round();
  return '$low–$high ${_fluidUnit(useImperial)}';
}

extension _$FluidExt on MacroExplanationService {
  NutrientTransparencyData _preWorkoutFluidTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final pre = macroTargets.preRun;
    final fluidsMl = pre.fluidsMl.round();
    final rangeLowMl = pre.fluidsLowMl?.round() ?? (fluidsMl * 0.8).round();
    final rangeHighMl = pre.fluidsHighMl?.round() ?? (fluidsMl * 1.2).round();

    // Prefer the authoritative `hydrationTier` from the edge function
    // (1 = body-weight scaled, 2 = fixed 250 ml top-up, 3 = no hydration).
    // Fall back to the legacy fluid-magnitude heuristic only when tier is
    // missing — older cached plans and some offline paths may not have
    // populated it. The heuristic mislabels low-bodyweight Tier 1 athletes
    // (e.g. 47.6 kg → 286 ml) as Tier 2; the explicit tier avoids that.
    final tier = pre.hydrationTier;
    final isTier3 = tier != null ? tier == 3 : fluidsMl == 0;
    final isTier2 = tier != null ? tier == 2 : (!isTier3 && fluidsMl <= 300);

    // When fluidsMl == 0, determine whether the gate fired (short + mild
    // workout → no plan needed) or whether it's a too-late scenario
    // (< 10 min before start → fluid won't absorb). The gate fires when
    // duration < 60 min AND temp < 30°C. We use duringRun because that's
    // where durationMin and tempC live; this mirrors the gate logic used
    // in the during-workout card.
    final durationMin = macroTargets.metrics.durationMin;
    final tempC = macroTargets.duringRun.tempC ?? 22.0;
    final isGateFired = isTier3 && durationMin < 60 && tempC < 30;

    final String blurb;
    final List<FormulaLine> tldrLines;

    if (isGateFired) {
      blurb =
          'No structured pre-hydration needed — this workout is short and '
          'mild. **Drink to thirst** in the hours before. If you want a number, '
          'keep it under ${_fmtMlAmount(500, useImperial)} total.';
      tldrLines = const [];
    } else if (isTier3) {
      blurb =
          'Too late for structured pre-hydration. A few small sips are fine '
          'for comfort, but fluid taken now won\'t absorb before exercise begins. '
          'Focus on the during-workout plan instead.';
      tldrLines = const [];
    } else if (isTier2) {
      blurb =
          'Not enough time for the full protocol. '
          '${_fmtMlAmount(fluidsMl, useImperial)} is all that can '
          'meaningfully absorb before exercise begins. Sip it steadily — '
          'don\'t chug it just before you start.';
      // Spec transparency_pre_hydration.md §Formula — multi-line TL;DR
      // showing fixed amount and total range label.
      tldrLines = [
        FormulaLine([
          fAccent('10–120 min window '),
          fOp('→ '),
          fResult(_fmtMlAmount(fluidsMl, useImperial)),
          fOp(' (fixed)'),
        ], stepNumber: '①'),
        FormulaLine([
          fOp('range '),
          fOp('→ '),
          fDim(_fmtMlRange(rangeLowMl, rangeHighMl, useImperial)),
        ]),
      ];
    } else {
      // Tier 1 — full ACSM protocol. Spec uses 6 ml/kg midpoint, 5 ml/kg
      // floor, 7 ml/kg ceiling.
      // Back-derive the approximate time before the workout from the carb
      // prescription: preRun.carbsG / (bodyWeightKg * 1 g/kg/hr) gives hours.
      // Clamped to 2–4 h since that's the Tier 1 window. When bodyWeightKg is
      // unavailable fall back to "2+ hours".
      final double derivedHours;
      if (bodyWeightKg > 0 && pre.carbsG > 0) {
        derivedHours = (pre.carbsG / bodyWeightKg).clamp(2.0, 4.0);
      } else {
        derivedHours = 2.0;
      }
      final hoursLabel = derivedHours == derivedHours.truncateToDouble()
          ? '${derivedHours.toInt()} hours'
          : '${derivedHours.toStringAsFixed(1)} hours';
      blurb =
          'The goal before a workout is to start **euhydrated** — at your '
          'normal baseline, not loaded or depleted. With $hoursLabel available, '
          'you have time for the full protocol: sip ${_fmtMlAmount(fluidsMl, useImperial)} '
          'gradually, let it absorb, and aim for pale yellow urine before you head out.';
      // Bucket the derived ml/kg to the spec-exact integer (5/6/7) when it's
      // close, to avoid displaying e.g. "5.5 mL/kg" — which was the prior
      // output even though the legacy calc used a non-spec tier.
      final rawPerKg = bodyWeightKg > 0 ? fluidsMl / bodyWeightKg : 6.0;
      final String mlPerKg;
      if (rawPerKg < 5.5) {
        mlPerKg = '5';
      } else if (rawPerKg < 6.5) {
        mlPerKg = '6';
      } else {
        mlPerKg = '7';
      }
      final floorMl = (bodyWeightKg * 5).round();
      final ceilMl = (bodyWeightKg * 7).round();
      tldrLines = [
        FormulaLine([
          fAccent('${bodyWeightKg.toStringAsFixed(0)} kg '),
          fOp('× '),
          fAccent('$mlPerKg ml/kg '),
          fOp('= '),
          fResult(_fmtMlAmount(fluidsMl, useImperial)),
        ], stepNumber: '①'),
        FormulaLine([
          fOp('↓ floor = '),
          fDim(_fmtMlAmount(floorMl, useImperial)),
          fOp(' (5 ml/kg)'),
        ]),
        FormulaLine([
          fOp('↑ ceiling = '),
          fDim(_fmtMlAmount(ceilMl, useImperial)),
          fOp(' (7 ml/kg)'),
        ]),
        FormulaLine([
          fOp('range '),
          fOp('→ '),
          fDim(_fmtMlRange(floorMl, ceilMl, useImperial)),
          fOp(' sipped over available window'),
        ]),
      ];
    }

    // Spec `transparency_pre_hydration.md`: Tier 1 card shows the
    // "pale yellow urine" tip as a callout below the formula. Tier 2, gate,
    // and too-late cards get no tip (no time for urine colour to respond).
    final String? tldrTip = (!isTier3 && !isTier2)
        ? 'If your urine is still dark at 2 hours before your workout, '
              'the ACSM recommends an additional **3–5 ml/kg**. Aim for pale '
              'yellow — straw coloured — before you start.'
        : null;

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF), // blue
      primaryUnit: useImperial ? 'oz' : 'mL',
      phase: 'before',
      tldrBody: blurb,
      tldrLines: tldrLines,
      tldrTip: tldrTip,
      storySections: _preWorkoutFluidStorySections(isTier3: isTier3),
      calculationSections: _buildPreWorkoutFluidCalculationSections(
        bodyWeightKg: bodyWeightKg,
        fluidsMl: fluidsMl,
        fluidsLowMl: rangeLowMl,
        fluidsHighMl: rangeHighMl,
        tier: tier,
        isGateFired: isGateFired,
        useImperial: useImperial,
      ),
      videoTitle: 'Watch: Pre-Workout Hydration',
      targetGrams: _mlToDisplay(fluidsMl.toDouble(), useImperial),
      rangeLow: _mlToDisplay(rangeLowMl.toDouble(), useImperial),
      rangeHigh: _mlToDisplay(rangeHighMl.toDouble(), useImperial),
      sportLabel: 'Pre-Workout',
    );
  }

  List<StorySection> _preWorkoutFluidStorySections({required bool isTier3}) {
    return [
      const StorySection(
        question: 'What is euhydration and why does it matter?',
        answer:
            'Euhydration is your normal, well-hydrated baseline \u2014 neither '
            'dehydrated nor over-hydrated. Even 1\u20132% body weight deficit '
            'measurably impairs performance and accelerates cardiovascular '
            'strain. Starting euhydrated means your sweat losses during exercise '
            'are recoverable, not compounding a pre-existing deficit.',
        citation:
            'Cheuvront & Kenefick (2014) \u2014 Comprehensive Physiology; '
            'Sawka et al. (2007) \u2014 ACSM Position Stand',
        dataChips: ['Pre-hydration goal \u00b7 euhydration, not loading'],
        confidence: ConfidenceLevel.high,
      ),
      if (!isTier3)
        const StorySection(
          question: 'Where does 5\u20137 ml/kg come from?',
          answer:
              'The ACSM recommends **5\u20137 mL/kg** of body weight as a '
              'pre-workout fluid protocol for the 2\u20134 hour window. This '
              'is enough to achieve euhydration without pushing excess fluid '
              'that would be excreted before exercise begins.',
          citation:
              'Sawka et al. (2007) \u2014 ACSM Position Stand; '
              'Thomas et al. (2016) \u2014 Academy of Nutrition & Dietetics',
          dataChips: [
            '5 mL/kg \u00b7 lower bound',
            '6 mL/kg \u00b7 target',
            '7 mL/kg \u00b7 upper bound',
          ],
          confidence: ConfidenceLevel.high,
        ),
      // C5 \u2014 time-availability tiering
      const StorySection(
        question: 'Why does the recommendation change with time available?',
        answer:
            'Fluid absorption takes time. With \u2265 2 hours, you can drink '
            'body-weight-scaled volume and have it absorb fully before exercise. '
            'With 10\u2013120 minutes, only a small top-up will absorb in time. '
            'Under 10 minutes, most of what you drink won\'t absorb before you '
            'start \u2014 it just sits in your stomach.',
        citation: 'NATA position stand \u2014 fluid replacement for athletes',
        dataChips: [
          '\u2265 2 hours \u00b7 BW \u00d7 5\u20137 mL/kg',
          '10\u2013120 min \u00b7 200\u2013300 mL fixed',
          '< 10 min \u00b7 sips only',
        ],
        confidence: ConfidenceLevel.medium,
      ),
      // C6 \u2014 early-morning / evening-before tip
      const StorySection(
        question: 'What about early morning workouts?',
        answer:
            'For 5\u20136 AM workouts, you often don\'t have a full 2-hour '
            'window to pre-hydrate. The practical workaround is to hydrate well '
            'the evening before \u2014 an extra 300\u2013500 mL of fluid with '
            'dinner, plus a normal-sized breakfast-time top-up. You wake up '
            'closer to baseline and don\'t need to chug water at the start.',
        citation: 'ACSM general 24-hour pre-exercise hydration guidance',
        transparencyNote:
            'The evening-before recommendation is based on ACSM\'s general '
            'guidance to maintain adequate hydration during the 24-hour period '
            'before exercise. It is a practical tip, not a separately '
            'calculated protocol.',
        confidence: ConfidenceLevel.medium,
      ),
    ];
  }

  // ---------------------------------------------------------------------------
  // FLUID MAP BUILDERS — assemble per-scenario maps
  // ---------------------------------------------------------------------------

  /// Builds the fluid [Map<Scenario, NutrientTransparencyData>] for a
  /// single-sport (non-brick) during workout.
  Map<Scenario, NutrientTransparencyData> _singleSportFluidMap({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationMin = macroTargets.metrics.durationMin.round();
    final isTested = during.isTested;
    final shortWorkoutGate =
        durationMin < 60 && (during.tempC == null || (during.tempC ?? 25) < 30);

    final map = <Scenario, NutrientTransparencyData>{};

    // Single sport is always present
    map[Scenario.singleSport] = _duringSingleSportFluidTransparency(
      macroTargets: macroTargets,
      bodyWeightKg: bodyWeightKg,
      useImperial: useImperial,
    );

    // Short workout gate — different blurb, same numbers
    if (shortWorkoutGate) {
      map[Scenario.shortWorkout] = _shortWorkoutFluidTransparency(
        macroTargets: macroTargets,
        useImperial: useImperial,
      );
    }

    // Known-rate — different blurb emphasising the tested override
    if (isTested) {
      map[Scenario.knownRate] = _knownRateFluidTransparency(
        macroTargets: macroTargets,
        bodyWeightKg: bodyWeightKg,
        useImperial: useImperial,
      );
    }

    return map;
  }

  /// Builds the fluid [Map<Scenario, NutrientTransparencyData>] for a
  /// brick/tri segment (non-swim) during workout.
  Map<Scenario, NutrientTransparencyData> _brickSegmentFluidMap({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final isTested = segment.isTested;
    final hasRedistribution = [
      ...macroTargets.duringRun.safetyFlags,
      ...segment.safetyFlags,
    ].any((f) => f.toLowerCase().contains('redistri'));

    final map = <Scenario, NutrientTransparencyData>{};

    // Multi-segment is always present for bricks
    map[Scenario.multiSegment] = _brickSegmentFluidTransparency(
      macroTargets: macroTargets,
      segment: segment,
      bodyWeightKg: bodyWeightKg,
      useImperial: useImperial,
    );

    // Redistribution — only when run leg hit GI ceiling
    if (hasRedistribution) {
      map[Scenario.redistribution] = _redistributionFluidTransparency(
        macroTargets: macroTargets,
        segment: segment,
        bodyWeightKg: bodyWeightKg,
        useImperial: useImperial,
      );
    }

    // Known-rate
    if (isTested) {
      map[Scenario.knownRate] = _knownRateFluidTransparency(
        macroTargets: macroTargets,
        bodyWeightKg: 0, // weight not shown in brick-segment known-rate blurb
        useImperial: useImperial,
        forBrickSegment: segment,
      );
    }

    return map;
  }

  // ---------------------------------------------------------------------------
  // DURING SINGLE SPORT FLUID — known-rate variant
  // ---------------------------------------------------------------------------

  /// Returns a Fluids transparency card with copy emphasising the known-rate
  /// (sweat-test) override. Numbers are identical to [singleSport].
  NutrientTransparencyData _knownRateFluidTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
    BrickSegmentMacroTarget? forBrickSegment,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final fluidRateMlH = forBrickSegment != null
        ? (forBrickSegment.durationMinutes > 0
              ? (forBrickSegment.waterMl /
                        (forBrickSegment.durationMinutes / 60.0))
                    .round()
              : 0)
        : during.fluidRateMlPerH.round();
    final fluidTotalMl = forBrickSegment != null
        ? forBrickSegment.waterMl.round()
        : during.fluidTotalMl.round();
    final effectiveSweatRate =
        forBrickSegment?.effectiveSweatRateLPerH ??
        during.effectiveSweatRateLPerH;
    final replacementPct =
        forBrickSegment?.replacementPercent ?? during.replacementPercent;
    final floorMlH = forBrickSegment?.floorMlPerH ?? during.floorMlPerH;
    final ceilingMlH = forBrickSegment?.ceilingMlPerH ?? during.ceilingMlPerH;
    final fluidsLowMl = forBrickSegment?.waterLowMl ?? during.fluidsLowMl;
    final fluidsHighMl = forBrickSegment?.waterHighMl ?? during.fluidsHighMl;

    final List<FormulaLine> tldrLines;
    if (effectiveSweatRate != null && replacementPct != null) {
      final replacePctPct = (replacementPct * 100).round();
      final ceilNote = ceilingMlH != null
          ? _fmtMlRate(ceilingMlH, useImperial)
          : 'GI ceiling';
      final floorNote = floorMlH != null
          ? _fmtMlRate(floorMlH, useImperial)
          : '2% BW floor';
      tldrLines = [
        FormulaLine([
          fAccent('TESTED rate '),
          fDim('${effectiveSweatRate.toStringAsFixed(2)} L/hr '),
          fOp('\u00d7 '),
          fAccent('replacement '),
          fDim('${replacePctPct}% '),
          fOp('= '),
          fDim(_fmtMlRate(fluidRateMlH, useImperial)),
        ], stepNumber: '\u2460'),
        if (floorMlH != null)
          FormulaLine([
            fOp('\u2193 '),
            fAccent('floor '),
            fDim(floorNote),
          ], stepNumber: '\u2462'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim(ceilNote),
          ], stepNumber: '\u2463'),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('\u00d7 '),
            fAccent(
              '${_formatDuration(forBrickSegment != null ? forBrickSegment.durationMinutes / 60.0 : durationH)} hr ',
            ),
            fOp('= '),
            fResult(_fmtMlAmount(fluidTotalMl, useImperial)),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fAccent('TESTED ${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent(
            '${_formatDuration(forBrickSegment != null ? forBrickSegment.durationMinutes / 60.0 : durationH)} hr ',
          ),
          fOp('= '),
          fResult(_fmtMlAmount(fluidTotalMl, useImperial)),
        ], isResultLine: true),
      ];
    }

    final knownRateCalcSections = _buildDuringFluidCalculationSections(
      during: during,
      durationMin: macroTargets.metrics.durationMin.round(),
      durationH: durationH,
      bodyWeightKg: bodyWeightKg,
      useImperial: useImperial,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: true,
      tldrBody:
          'Your fluid target is based on your **personal sweat test** result. '
          'The tested rate overrode the category lookup (Light/Medium/Heavy) — '
          'this is the most accurate input available. Floor and ceiling limits '
          'still apply to keep you in a safe range.',
      tldrLines: tldrLines,
      calculationSections: knownRateCalcSections,
      calculationWarning: during.safetyFlags.isNotEmpty
          ? during.safetyFlags.first
          : null,
      storySections: [
        const StorySection(
          question: 'How was the known rate applied?',
          answer:
              'Instead of using the Light/Medium/Heavy sweat-rate category lookup, '
              'your personal tested rate was used as the base input to the effective '
              'sweat rate calculation. Environmental multipliers (temperature, humidity, '
              'indoor) were still applied on top of your tested rate.',
          citation:
              'Precision Fuel & Hydration / TrainingPeaks \u2014 standard at-home sweat test protocol',
          dataChips: ['TESTED \u2713 \u00b7 personal sweat test'],
        ),
        const StorySection(
          question: 'How do I update my tested rate?',
          answer:
              'Go to Settings \u2192 Sweat Profile to enter or update your known sweat '
              'rate. After saving, regenerate this activity\'s plan to see updated '
              'recommendations. Re-test every season or when conditions change significantly.',
          inlineEditType: InlineEditType.knownSweatRate,
          dataChips: ['TESTED \u2713 \u00b7 overrides category'],
        ),
        const StorySection(
          question: 'What if conditions are very different from my test?',
          answer:
              'Your tested rate is calibrated to the conditions of your test '
              '(temperature, humidity). If today\'s conditions differ significantly, '
              'the environmental multipliers partially adjust. For the most accuracy, '
              'run a test under similar conditions to your target event.',
          citation: 'Barnes & Baker (2019) \u2014 sweat rate variability',
          dataChips: [
            'Temp coefficient \u00b7 4%/\u00b0C',
            'Humidity \u00b7 +2% above 50%',
          ],
        ),
      ],
      videoTitle: 'Watch: Hydration During Exercise',
      targetGrams: _mlToDisplay(fluidTotalMl.toDouble(), useImperial),
      rangeLow: _mlToDisplayOrNull(fluidsLowMl, useImperial),
      rangeHigh: _mlToDisplayOrNull(fluidsHighMl, useImperial),
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // SHORT WORKOUT FLUID — gate-applied variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _shortWorkoutFluidTransparency({
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final fluidTotalMl = during.fluidTotalMl.round();
    final durationH = macroTargets.metrics.durationH;
    final fluidsLowMl = during.fluidsLowMl;
    final fluidsHighMl = during.fluidsHighMl;

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: during.isTested,
      tldrBody: useImperial
          ? 'This workout is short and conditions are mild \u2014 no structured '
                'hydration plan needed. **Drink to thirst.** If you want a number, '
                'aim for no more than 10 oz. Don\'t exceed 20 oz.'
          : 'This workout is short and conditions are mild \u2014 no structured '
                'hydration plan needed. **Drink to thirst.** If you want a number, '
                'aim for no more than 300 mL. Don\'t exceed 600 mL.',
      tldrLines: [
        FormulaLine([
          fAccent('short gate '),
          fOp('= '),
          fAccent('duration < 60 min + mild temp '),
          fOp('\u2192 '),
          fDim('drink to thirst'),
        ]),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult(_fmtMlAmount(fluidTotalMl, useImperial)),
            fDim(' (conservative max)'),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ],
      calculationSections: [
        CalculationSection(
          header: 'SHORT-WORKOUT GATE',
          lines: [
            FormulaLine([
              fAccent('duration '),
              fDim('${macroTargets.metrics.durationMin.round()} min '),
              fOp('< 60 '),
              fOp('AND '),
              fAccent('temp '),
              fDim('${during.tempC?.toStringAsFixed(0) ?? '22'}°C '),
              fOp('< 30 '),
              fOp('→ '),
              fAccent('gate fires'),
            ], stepNumber: '①'),
            FormulaLine([
              fOp('→ '),
              fDim('drink to thirst; conservative cap = 30% of sweat rate'),
            ], stepNumber: '②'),
            FormulaLine(
              [
                fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
                fOp('× '),
                fAccent('${_formatDuration(durationH)} hr '),
                fOp('= '),
                fResult('${_fmtMlAmount(fluidTotalMl, useImperial)} '),
                fDim('(conservative max)'),
              ],
              isResultLine: true,
              showDividerBefore: true,
            ),
          ],
        ),
      ],
      storySections: [
        const StorySection(
          question: 'Why "drink to thirst" for short workouts?',
          answer:
              'For efforts under 60 minutes in mild conditions, the body\'s thirst '
              'mechanism is an accurate guide. You cannot meaningfully deplete '
              'hydration status in that time window under normal temperatures. '
              'A structured plan adds complexity without benefit.',
          citation: 'Noakes (2012) \u2014 Hyponatremia in endurance sports',
          dataChips: [
            'Short gate \u00b7 < 60 min + temp < 30\u00b0C',
            'Gate bypassed \u00b7 if temp \u2265 30\u00b0C',
          ],
        ),
        const StorySection(
          question: 'Why is there still a number shown?',
          answer:
              'The plan shows a conservative ceiling of 30% sweat-loss replacement '
              'so you have a reference if you prefer structure. **Do not exceed 20 oz '
              '(600 mL).** Over-drinking during short workouts is a real risk of '
              'exercise-associated hyponatremia.',
          citation:
              'Hew-Butler et al. (2015) \u2014 Clinical Journal of Sport Medicine',
          dataChips: [
            'Max \u00b7 20 oz / 600 mL',
            'Replacement \u00b7 30% (soft, gated)',
          ],
        ),
      ],
      videoTitle: 'Watch: Hydration During Exercise',
      targetGrams: _mlToDisplay(fluidTotalMl.toDouble(), useImperial),
      rangeLow: _mlToDisplayOrNull(fluidsLowMl, useImperial),
      rangeHigh: _mlToDisplayOrNull(fluidsHighMl, useImperial),
      sportLabel: null,
    );
  }

  // ---------------------------------------------------------------------------
  // REDISTRIBUTION FLUID — bike absorbed run shortfall variant
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _redistributionFluidTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final durationH = segment.durationMinutes / 60.0;
    final totalEventMin = macroTargets.metrics.durationMin.round();
    final waterMl = segment.waterMl.round();
    final effectiveSweatRate = segment.effectiveSweatRateLPerH;
    final replacementPct = segment.replacementPercent;
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;
    final ceilingMlH = segment.ceilingMlPerH;
    final fluidsLowMl = segment.waterLowMl;
    final fluidsHighMl = segment.waterHighMl;

    final List<FormulaLine> tldrLines;
    if (effectiveSweatRate != null && replacementPct != null) {
      final replacePctPct = (replacementPct * 100).round();
      tldrLines = [
        FormulaLine([
          fAccent('total event '),
          fDim('${totalEventMin} min '),
          fOp('\u2192 '),
          fAccent('replacement '),
          fDim('${replacePctPct}%'),
        ], stepNumber: '\u2460'),
        FormulaLine([
          fOp('# '),
          fAccent('redistribution '),
          fDim('run shortfall \u2192 bike'),
        ], stepNumber: '\u2461'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim(_fmtMlRate(ceilingMlH, useImperial)),
            fOp('(bike GI limit)'),
          ], stepNumber: '\u2462'),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult(_fmtMlAmount(waterMl, useImperial)),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      tldrLines = [
        FormulaLine([
          fOp('# '),
          fAccent('redistribution '),
          fDim('run shortfall \u2192 bike'),
        ]),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult(_fmtMlAmount(waterMl, useImperial)),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: segment.isTested,
      tldrBody:
          'In a race or brick, the replacement strategy is based on '
          '**total event duration** \u2014 not just this leg. When the run leg '
          'can\'t absorb enough to stay within 2% body weight loss, the shortfall '
          'is redistributed here where your gut has more capacity.',
      tldrLines: tldrLines,
      calculationSections: _buildBrickFluidCalculationSections(
        during: macroTargets.duringRun,
        segment: segment,
        totalEventMin: totalEventMin,
        bodyWeightKg: bodyWeightKg,
        showRedistributionNote: true,
        useImperial: useImperial,
      ),
      calculationWarning: segment.safetyFlags.isNotEmpty
          ? segment.safetyFlags.first
          : null,
      storySections: [
        const StorySection(
          question: 'What is run\u2192bike redistribution?',
          answer:
              'When the run segment\'s recommended intake exceeds its 800 mL/hr GI '
              'ceiling, the unabsorbable portion is redistributed to the bike leg '
              '(which can handle up to 1200 mL/hr). This maximises fluid delivery '
              'across the full event while respecting each sport\'s absorption limit.',
          citation:
              'Pfeiffer et al. (2012) \u2014 GI Problems in Endurance Sports',
          dataChips: [
            'Run GI ceiling \u00b7 800 mL/hr',
            'Bike GI ceiling \u00b7 1200 mL/hr',
            'Redistribution \u00b7 # flag',
          ],
        ),
        const StorySection(
          question: 'Why can\'t I just drink more on the run?',
          answer:
              'The running GI ceiling is a hard physiological limit \u2014 running\'s '
              'vertical impact dramatically reduces gut motility. Exceeding 800 mL/hr '
              'during running leads to bloating, nausea, and slowed pace far more '
              'reliably than it leads to better hydration.',
          dataChips: [
            'Run \u00b7 max 800 mL/hr (GI limit)',
            'Bike \u00b7 max 1200 mL/hr',
          ],
        ),
      ],
      videoTitle: 'Watch: Hydration During Exercise',
      targetGrams: _mlToDisplay(waterMl.toDouble(), useImperial),
      rangeLow: _mlToDisplayOrNull(fluidsLowMl, useImperial),
      rangeHigh: _mlToDisplayOrNull(fluidsHighMl, useImperial),
      sportLabel: segment.sport,
    );
  }

  // ---------------------------------------------------------------------------
  // CALCULATION SECTION BUILDERS — step-by-step breakdown for the UI accordion
  //
  // The edge function already performs all these calculations, but for the
  // transparency UI we recompute the intermediate multipliers so we can
  // display them as numbered steps. Derivation is:
  //   effective = base × temp_mult × humidity_mult × indoor_mult  (clamped)
  //   base = effective / (temp_mult × humidity_mult × indoor_mult)
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _duringSingleSportFluidTransparency({
    required MacroTargets macroTargets,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final during = macroTargets.duringRun;
    final durationH = macroTargets.metrics.durationH;
    final durationMin = macroTargets.metrics.durationMin.round();
    final fluidRateMlH = during.fluidRateMlPerH.round();
    final fluidTotalMl = during.fluidTotalMl.round();

    // Use derivation fields if available (new plans); fall back gracefully
    final effectiveSweatRate = during.effectiveSweatRateLPerH;
    final replacementPct = during.replacementPercent;
    final floorMlH = during.floorMlPerH;
    final ceilingMlH = during.ceilingMlPerH;
    final safetyFlags = during.safetyFlags;
    final isTested = during.isTested;

    final shortWorkoutGate =
        durationMin < 60 && (during.tempC == null || (during.tempC ?? 25) < 30);

    final List<FormulaLine> tldrLines;
    final String blurb;

    if (shortWorkoutGate && fluidRateMlH < 200) {
      // Short-workout gate
      blurb = useImperial
          ? 'This workout is short and conditions are mild \u2014 no structured '
                'hydration plan needed. **Drink to thirst.** If you want a number, '
                'aim for no more than 10 oz. Don\'t exceed 20 oz.'
          : 'This workout is short and conditions are mild \u2014 no structured '
                'hydration plan needed. **Drink to thirst.** If you want a number, '
                'aim for no more than 300 mL. Don\'t exceed 600 mL.';
      tldrLines = [
        FormulaLine([
          fAccent('short gate '),
          fOp('= '),
          fAccent('duration < 60 min + mild temp '),
          fOp('\u2192 '),
          fDim('drink to thirst'),
        ]),
      ];
    } else if (effectiveSweatRate != null && replacementPct != null) {
      // New derivation fields available
      blurb =
          'Your fluid target starts with a duration-based replacement strategy, '
          'then two overrides are applied: a **floor** that raises the target if '
          'needed to keep you within 2% body weight loss, and a **ceiling** that '
          'caps it at what your gut can absorb and what\'s safe for blood sodium. '
          'The final recommendation is always between those two bounds.';

      final replacePctPct = (replacementPct * 100).round();
      final ceilNote = ceilingMlH != null
          ? _fmtMlRate(ceilingMlH, useImperial)
          : 'GI ceiling';
      final floorNote = floorMlH != null
          ? _fmtMlRate(floorMlH, useImperial)
          : '2% BW floor';

      tldrLines = [
        FormulaLine([
          fAccent('${durationMin} min '),
          fOp('\u2192 '),
          fAccent('replacement '),
          fDim('${replacePctPct}%'),
        ], stepNumber: '\u2460'),
        FormulaLine([
          fAccent('sweat rate '),
          fDim('${effectiveSweatRate.toStringAsFixed(2)} L/hr '),
          fOp('\u00d7 '),
          fAccent('${replacePctPct}% '),
          fOp('= '),
          fDim(_fmtMlRate(fluidRateMlH, useImperial)),
        ], stepNumber: '\u2461'),
        if (floorMlH != null)
          FormulaLine([
            fOp('\u2193 '),
            fAccent('floor '),
            fDim(floorNote),
            fOp(' (2% BW deficit)'),
          ], stepNumber: '\u2462'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim(ceilNote),
            fOp(' (GI limit)'),
          ], stepNumber: '\u2463'),
        if (safetyFlags.isNotEmpty)
          FormulaLine([
            fOp('\u2713 '),
            fAccent('safety '),
            fDim(safetyFlags.first),
          ]),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult(_fmtMlAmount(fluidTotalMl, useImperial)),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      // Legacy plan — simple card
      blurb =
          'Your fluid target replaces a portion of your sweat losses during '
          'activity, keeping you within a safe hydration window.';
      tldrLines = [
        FormulaLine([
          fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult(_fmtMlAmount(fluidTotalMl, useImperial)),
        ], isResultLine: true),
      ];
    }

    final fluidsLowMl = during.fluidsLowMl;
    final fluidsHighMl = during.fluidsHighMl;

    final calcSections = _buildDuringFluidCalculationSections(
      during: during,
      durationMin: durationMin,
      durationH: durationH,
      bodyWeightKg: bodyWeightKg,
      useImperial: useImperial,
    );

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody: blurb,
      tldrLines: tldrLines,
      calculationSections: calcSections,
      calculationWarning: safetyFlags.isNotEmpty ? safetyFlags.first : null,
      storySections: _duringFluidStorySections(
        isTested: isTested,
        shortWorkoutGate: shortWorkoutGate,
        hasDerivationFields: effectiveSweatRate != null,
      ),
      videoTitle: 'Watch: Hydration During Exercise',
      targetGrams: _mlToDisplay(fluidTotalMl.toDouble(), useImperial),
      rangeLow: _mlToDisplayOrNull(fluidsLowMl, useImperial),
      rangeHigh: _mlToDisplayOrNull(fluidsHighMl, useImperial),
      sportLabel: null,
    );
  }

  List<StorySection> _duringFluidStorySections({
    required bool isTested,
    required bool shortWorkoutGate,
    required bool hasDerivationFields,
  }) {
    return [
      if (shortWorkoutGate)
        const StorySection(
          question: 'Why "drink to thirst" for short workouts?',
          answer:
              'For efforts under 60 minutes in mild conditions, the body\'s thirst '
              'mechanism is an accurate guide. You cannot meaningfully deplete '
              'hydration status in that time window under normal temperatures.',
          citation: 'Noakes (2012) \u2014 Hyponatremia in endurance sports',
          dataChips: ['Short gate \u00b7 < 60 min + temp < 30\u00b0C'],
        ),
      const StorySection(
        question: 'Why replace a percentage of sweat losses, not all of it?',
        answer:
            'Replacing 100% of sweat losses during exercise can lead to '
            '**hyponatremia** (dangerously low blood sodium) by diluting the '
            'sodium remaining in your blood. Research shows 50\u201380% replacement '
            'is optimal, scaled up with event duration.',
        citation:
            'Baker (2017) \u2014 Journal of the International Society of Sports Nutrition',
        dataChips: [
          '<60 min \u00b7 30%',
          '60\u201390 min \u00b7 50%',
          '90\u2013150 min \u00b7 60%',
          '150\u2013240 min \u00b7 70%',
          '240+ min \u00b7 80%',
        ],
      ),
      const StorySection(
        question: 'What is the 2% body weight floor?',
        answer:
            'Losing more than 2% of body weight through sweat starts to impair '
            'performance. The floor ensures your recommended rate is high enough '
            'to stay within that safety boundary, **even if the replacement % alone '
            'would leave you too depleted.**',
        citation: 'Sawka et al. (2007) \u2014 ACSM Position Stand',
        dataChips: [
          '>2% BW deficit \u00b7 performance impact',
          '>3% BW deficit \u00b7 significant risk',
        ],
      ),
      const StorySection(
        question: 'What is the GI ceiling?',
        answer:
            'Your gut can only absorb so much fluid per hour. Drinking above '
            'the ceiling causes GI distress without improving hydration. '
            'Running\'s mechanical impact restricts absorption more than cycling.',
        citation:
            'Pfeiffer et al. (2012) \u2014 GI Problems in Endurance Sports',
        dataChips: ['Run \u00b7 max 800 mL/hr', 'Bike \u00b7 max 1200 mL/hr'],
      ),
      StorySection(
        question: 'What\'s my actual sweat rate?',
        answer: isTested
            ? 'Your sweat rate is from a **personal sweat test** \u2014 the most '
                  'accurate input available. This rate already accounts for your '
                  'individual physiology. If conditions differ significantly from your '
                  'test conditions, consider retesting.'
            : 'Your sweat rate is estimated from your sweat profile category and '
                  'adjusted for temperature, humidity, and indoor conditions. '
                  'For a more accurate number, weigh yourself nude before and after '
                  'a known-duration workout and enter the result below.',
        citation: isTested
            ? null
            : 'Precision Fuel & Hydration / TrainingPeaks \u2014 standard at-home sweat test protocol',
        inlineEditType: InlineEditType.knownSweatRate,
        dataChips: isTested
            ? ['TESTED \u2713 \u00b7 personal sweat test']
            : [
                'Light \u00b7 0.90 L/hr \u00b7 25th pct',
                'Medium \u00b7 1.28 L/hr \u00b7 50th pct',
                'Heavy \u00b7 1.66 L/hr \u00b7 75th pct',
              ],
        confidence: ConfidenceLevel.high,
      ),
      // C15 \u2014 Temperature Q
      const StorySection(
        question: 'Why does temperature change the target?',
        answer:
            'Heat stress increases sweat rate roughly 4% per degree Celsius '
            'above a neutral 22\u00b0C baseline. We apply the multiplier on top '
            'of your base rate and clamp it to a 0.50\u00d7\u20131.80\u00d7 '
            'safety band so a single extreme data point can\'t produce absurd '
            'targets.',
        citation: 'Jenkins et al. (2023) \u2014 Temperature and sweat rate',
        dataChips: [
          '10\u00b0C \u00b7 0.52\u00d7',
          '22\u00b0C \u00b7 1.0\u00d7 neutral',
          '30\u00b0C \u00b7 1.32\u00d7',
          '>40\u00b0C \u00b7 1.80\u00d7 capped',
        ],
        confidence: ConfidenceLevel.medium,
      ),
      // C16 \u2014 Humidity Q with transparency note
      const StorySection(
        question: 'Does humidity matter?',
        answer:
            'Humidity reduces how efficiently sweat evaporates, so more fluid '
            'drips off without contributing to cooling. We apply a small '
            'multiplier (max +10%) when humidity rises above 50%, as a '
            'conservative practical adjustment.',
        citation: 'Che Muhamed et al. (2016); Jenkins et al. (2023)',
        transparencyNote:
            'Jenkins et al. (2023) found humidity did not significantly '
            'increase sweat rate on its own. The small multiplier (max '
            '1.10\u00d7) is Mealvana\'s conservative practical estimate \u2014 '
            'not directly validated by the research.',
        dataChips: [
          '50% RH \u00b7 1.00\u00d7 baseline',
          '80% RH \u00b7 1.06\u00d7',
          '100% RH \u00b7 1.10\u00d7 capped',
        ],
        confidence: ConfidenceLevel.medium,
      ),
      // C17 \u2014 Indoor Q with transparency note
      const StorySection(
        question: 'Why do you sweat more indoors?',
        answer:
            'Indoor workouts remove wind-driven evaporative cooling. Without '
            'airflow, your body has to sweat more to move heat out. We apply '
            'a 1.30\u00d7 multiplier for indoor sessions on top of temperature '
            'and humidity adjustments.',
        citation: 'Practical adjustment based on trainer / treadmill data',
        transparencyNote:
            'The 1.30\u00d7 indoor multiplier is conceptually well-supported '
            'but not directly quantified in published research. This is our '
            'lowest-confidence adjustment \u2014 we plan to refine it with user '
            'data over time.',
        dataChips: ['Indoor \u00b7 1.30\u00d7', 'Outdoor \u00b7 1.00\u00d7'],
        confidence: ConfidenceLevel.low,
      ),
      // C18 \u2014 EAH / overhydration Q (SAFETY-CRITICAL)
      const StorySection(
        question: 'Why is drinking too much water also dangerous?',
        answer:
            '**Exercise-associated hyponatremia (EAH)** happens when athletes '
            'drink more fluid than they sweat, diluting blood sodium to '
            'dangerously low levels. Symptoms include nausea, headache, '
            'confusion; severe cases can be fatal. The ceiling on your plan '
            'caps intake at 100% of your sweat rate (and never above the '
            'sport\'s GI absorption limit) to prevent this.',
        citation:
            'Hew-Butler et al. (2015) \u2014 Clinical Journal of Sport Medicine; '
            'Sawka et al. (2007) ACSM',
        dataChips: [
          'Ceiling \u00b7 100% of sweat rate',
          'GI cap \u00b7 run 800, bike 1200 mL/hr',
        ],
        confidence: ConfidenceLevel.high,
      ),
      // C19 \u2014 Warning-flag-meaning Q
      const StorySection(
        question: 'What does the warning flag mean?',
        answer:
            'When we can\'t keep your estimated deficit under 2% body weight '
            'even at the recommended intake, we flag it. Pre-hydrate well and '
            'rehydrate immediately after. A >3% deficit is the threshold for '
            'significant dehydration \u2014 treat hot long efforts with extra '
            'caution and plan rest stops.',
        citation: 'Sawka et al. (2007) \u2014 2% BW threshold',
        dataChips: ['Flag \u2265 2% BW', 'Significant \u2265 3% BW'],
        confidence: ConfidenceLevel.high,
      ),
    ];
  }

  // ---------------------------------------------------------------------------
  // BRICK SEGMENT FLUID
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _brickSegmentFluidTransparency({
    required MacroTargets macroTargets,
    required BrickSegmentMacroTarget segment,
    required double bodyWeightKg,
    bool useImperial = false,
  }) {
    final segmentSport = segment.sport;
    final durationMin = segment.durationMinutes;
    final durationH = durationMin / 60.0;
    final totalEventMin = macroTargets.metrics.durationMin.round();

    // Segment water total
    final waterMl = segment.waterMl.round();

    // Derivation fields (segment level if available)
    final effectiveSweatRate = segment.effectiveSweatRateLPerH;
    final replacementPct = segment.replacementPercent;
    final floorMlH = segment.floorMlPerH;
    final ceilingMlH = segment.ceilingMlPerH;
    final isTested = segment.isTested;

    // Rate from segment totals
    final fluidRateMlH = durationH > 0 ? (waterMl / durationH).round() : 0;

    final List<FormulaLine> tldrLines;
    final String blurb =
        'In a race or brick, the replacement strategy is based on '
        '**total event duration** \u2014 not just this leg. When the run leg '
        'can\'t absorb enough to stay within 2% body weight loss, the shortfall '
        'is redistributed here where your gut has more capacity.';

    if (effectiveSweatRate != null && replacementPct != null) {
      final replacePctPct = (replacementPct * 100).round();
      tldrLines = [
        FormulaLine([
          fAccent('total event '),
          fDim('${totalEventMin} min '),
          fOp('\u2192 '),
          fAccent('replacement '),
          fDim('${replacePctPct}%'),
        ], stepNumber: '\u2460'),
        FormulaLine([
          fAccent('sweat rate '),
          fDim('${effectiveSweatRate.toStringAsFixed(2)} L/hr '),
          fOp('\u00d7 '),
          fAccent('${replacePctPct}% '),
          fOp('= '),
          fDim(_fmtMlRate(fluidRateMlH, useImperial)),
        ], stepNumber: '\u2461'),
        if (floorMlH != null)
          FormulaLine([
            fOp('\u2193 '),
            fAccent('floor '),
            fDim(_fmtMlRate(floorMlH, useImperial)),
          ], stepNumber: '\u2462'),
        if (ceilingMlH != null)
          FormulaLine([
            fOp('\u2191 '),
            fAccent('ceiling '),
            fDim('${_fmtMlRate(ceilingMlH, useImperial)} '),
            fOp('(${segmentSport} limit)'),
          ], stepNumber: '\u2463'),
        FormulaLine(
          [
            fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
            fOp('\u00d7 '),
            fAccent('${_formatDuration(durationH)} hr '),
            fOp('= '),
            fResult(_fmtMlAmount(waterMl, useImperial)),
          ],
          isResultLine: true,
          showDividerBefore: true,
        ),
      ];
    } else {
      // Legacy fallback
      tldrLines = [
        FormulaLine([
          fAccent('${_fmtMlRate(fluidRateMlH, useImperial)} '),
          fOp('\u00d7 '),
          fAccent('${_formatDuration(durationH)} hr '),
          fOp('= '),
          fResult(_fmtMlAmount(waterMl, useImperial)),
        ], isResultLine: true),
      ];
    }

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz/hr' : 'mL/hr',
      phase: 'during',
      isTested: isTested,
      tldrBody: blurb,
      tldrLines: tldrLines,
      calculationSections: _buildBrickFluidCalculationSections(
        during: macroTargets.duringRun,
        segment: segment,
        totalEventMin: totalEventMin,
        bodyWeightKg: bodyWeightKg,
        // G5 spec `transparency_during_hydration.md` §Multi-Segment —
        // show the blue info callout explaining how T1/T2 absorb
        // 300 ml each. Transition count is inferred from the brick
        // phase targets; if unknown, default to 0 which suppresses
        // the callout.
        showTransitionAbsorptionNote: true,
        transitionCount:
            macroTargets.brickPhaseTargets?.transitions.length ?? 0,
        useImperial: useImperial,
      ),
      calculationWarning: segment.safetyFlags.isNotEmpty
          ? segment.safetyFlags.first
          : null,
      storySections: _duringFluidStorySections(
        isTested: isTested,
        shortWorkoutGate: false,
        hasDerivationFields: effectiveSweatRate != null,
      ),
      videoTitle: 'Watch: Hydration During Exercise',
      targetGrams: _mlToDisplay(waterMl.toDouble(), useImperial),
      rangeLow: _mlToDisplayOrNull(segment.waterLowMl, useImperial),
      rangeHigh: _mlToDisplayOrNull(segment.waterHighMl, useImperial),
      sportLabel: segmentSport,
    );
  }

  // ---------------------------------------------------------------------------
  // SWIM FLUID — zero state
  // ---------------------------------------------------------------------------

  /// Public accessor so the sheet can request the swim zero-state directly
  /// without going through the map-returning [getFluidTransparencyData].
  NutrientTransparencyData _swimFluidTransparency() {
    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: 'mL/hr',
      phase: 'during',
      tldrBody:
          'No drinking during swim \u2014 T1 covers the deficit. '
          'Your sweat losses during the swim are accounted for in the '
          'total-event fluid budget and distributed across the bike and '
          'T1 transition windows.',
      tldrLines: const [],
      storySections: const [
        StorySection(
          question: 'Why no drinking during swim?',
          answer:
              'It is physically impossible to drink during an open-water or pool '
              'swim without stopping. Sweat losses during swimming are also lower '
              '(~0.4\u00d7 land sports) due to water cooling the skin. '
              'The fluid deficit from the swim is fully accounted for in the '
              'T1 transition and subsequent bike segment targets.',
          citation:
              'Maughan & Shirreffs (2004) \u2014 swimming thermoregulation',
          dataChips: ['Swim sweat modifier \u00b7 0.4\u00d7 land sports'],
        ),
      ],
      isSwimZero: true,
      swimCallout:
          'Fluid deficit covered by: T1 transition \u00b7 Bike segment',
      targetGrams: 0,
      rangeLow: 0,
      rangeHigh: 0,
      sportLabel: 'Swim',
    );
  }

  // ---------------------------------------------------------------------------
  // TRANSITION FLUID
  // ---------------------------------------------------------------------------

  NutrientTransparencyData _transitionFluidTransparency({
    required ExplanationPhase phase,
    required MacroTargets macroTargets,
    bool useImperial = false,
  }) {
    final isT1 = phase == ExplanationPhase.transition1;
    final transitionName = isT1 ? 'T1' : 'T2';

    final transitions = macroTargets.brickPhaseTargets?.transitions;
    final tIdx = isT1 ? 0 : 1;
    final transition = (transitions != null && tIdx < transitions.length)
        ? transitions[tIdx]
        : null;
    final waterMl = transition?.waterMl.round() ?? 300;
    final isTested = transition?.isTested ?? false;

    return NutrientTransparencyData(
      nutrientLabel: 'Fluids',
      nutrientColor: const Color(0xFF4A9EFF),
      primaryUnit: useImperial ? 'oz' : 'mL',
      phase: 'transition',
      isTested: isTested,
      tldrBody:
          'Transitions are brief, fixed hydration windows \u2014 not a '
          'calculated segment. The ${_fmtMlAmount(waterMl, useImperial)} target '
          "isn't derived from your sweat rate; it's a conservative bolus sized "
          'for what you can comfortably take in during a 2\u20135 minute stop. '
          '**$transitionName** '
          '${isT1 ? "bridges the swim gap and offsets wetsuit heat." : "is your last easy opportunity before running GI tolerance drops."}',
      tldrLines: [
        FormulaLine([
          fAccent('$transitionName '),
          fOp('= '),
          fAccent('fixed ${_fmtMlAmount(waterMl, useImperial)} '),
          fOp('\u2192 '),
          fResult(_fmtMlAmount(waterMl, useImperial)),
        ]),
      ],
      calculationSections: _buildTransitionFluidCalculationSections(
        waterMl: waterMl,
        isT1: isT1,
        useImperial: useImperial,
      ),
      storySections: [
        StorySection(
          question: 'Why is the transition fluid fixed at 300 mL?',
          answer:
              'Transition windows are too short to calculate a precise sweat-rate-based '
              'target. 300 mL is a conservative bolus sized to what most athletes can '
              'comfortably consume and absorb during a 2\u20135 minute stop without '
              'causing GI distress when movement resumes.',
          citation:
              'Consensus recommendation \u2014 USA Triathlon / ITU nutrition guidelines',
          dataChips: ['T1/T2 fixed \u00b7 300 mL', 'Confidence \u00b7 LOW'],
        ),
      ],
      targetGrams: _mlToDisplay(waterMl.toDouble(), useImperial),
      rangeLow: _mlToDisplayOrNull(transition?.waterLowMl, useImperial),
      rangeHigh: _mlToDisplayOrNull(transition?.waterHighMl, useImperial),
      sportLabel: transitionName,
    );
  }

  // ===========================================================================
  // SODIUM TRANSPARENCY
  // ===========================================================================

  /// Build structured transparency data for the Sodium card, keyed by [Scenario].
  ///
  /// Mirrors [getFluidTransparencyData] in structure. The [Scenario] keys in the
  /// returned map should be intersected with the fluid map's keys so both cards
  /// always show the same set of tabs.
}
