/**
 * send-nutrition-plan-email — request handler.
 *
 * Split out of `index.ts` so the real handler can be exercised in tests without
 * `serve()` binding a port. `index.ts` is now the thin wiring file.
 *
 * Auth: a signed-in caller is required (ai-cost ticket 01, mp-466). The app already
 * sends the Supabase user JWT on `functions.invoke`. Without a valid token the
 * function returns 401 and sends nothing — the Resend call is never made.
 */
import { authenticate } from '../_shared/vana/auth.ts';

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const FROM_EMAIL = 'support@mealvana.io';
const DEFAULT_SUBJECT = 'Your Nutrition Plan from Mealvana Endurance';
const RESEND_API_URL = 'https://api.resend.com/emails';

/** Only the shape this handler needs — the shared helper returns more. */
type AuthOutcome = { ok: true } | { ok: false; status: number; error: string };

export interface SendEmailDeps {
  /** Caller check. Defaults to the shared `_shared/vana/auth.ts` helper. */
  authenticate?: (req: Request) => Promise<AuthOutcome>;
  /** Outbound HTTP, so tests never reach Resend. */
  fetchFn?: typeof fetch;
  /** Resend API key. Defaults to the RESEND_API_KEY secret. */
  apiKey?: string;
}

export interface EmailPayload {
  recipientEmail?: string;
  senderName?: string;
  subject?: string;
  comments?: string;
  pdfAttachment?: string;
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

export function buildEmailHtml(senderName?: string, comments?: string): string {
  return `
      <html>
        <head>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
            }
            .header {
              text-align: center;
              padding: 20px 0;
              border-bottom: 2px solid #381633;
            }
            .content {
              padding: 20px 0;
            }
            .footer {
              text-align: center;
              padding: 20px 0;
              border-top: 1px solid #ddd;
              font-size: 12px;
              color: #666;
            }
            .comments {
              background-color: #f8f6eb;
              padding: 15px;
              border-radius: 8px;
              margin: 20px 0;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h2 style="color: #381633; margin: 0;">Nutrition Plan from Mealvana Endurance</h2>
          </div>
          <div class="content">
            ${senderName ? `<p><strong>From:</strong> ${senderName}</p>` : ''}
            ${comments ? `<div class="comments"><p><strong>Message:</strong></p><p>${comments}</p></div>` : ''}
            <p>Please find your personalized nutrition plan attached as a PDF.</p>
            <p>This plan was generated by Mealvana Endurance, designed specifically for endurance athletes.</p>
          </div>
          <div class="footer">
            <p>Generated with Mealvana Endurance</p>
            <p><a href="https://mealvana.io" style="color: #381633;">mealvana.io</a></p>
          </div>
        </body>
      </html>
    `;
}

export async function handleSendEmail(
  req: Request,
  deps: SendEmailDeps = {},
): Promise<Response> {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  const auth = deps.authenticate ?? authenticate;
  const doFetch = deps.fetchFn ?? fetch;
  // Read from the RESEND_API_KEY Supabase secret (set on dev+prod 2026-07-01;
  // value also in secrets/resend.env). No hardcoded fallback — a missing secret
  // should surface as a Resend 401, not silently use a stale key.
  const apiKey = deps.apiKey ?? Deno.env.get('RESEND_API_KEY') ?? '';

  // Caller check first: no body is read and no mail is sent for a stranger.
  const result = await auth(req);
  if (!result.ok) {
    return json({ success: false, error: result.error }, result.status);
  }

  try {
    const { recipientEmail, senderName, subject, comments, pdfAttachment }: EmailPayload =
      await req.json();

    if (!recipientEmail) {
      return json({ success: false, error: 'Recipient email is required' }, 400);
    }
    if (!pdfAttachment) {
      return json({ success: false, error: 'PDF attachment is required' }, 400);
    }

    const emailHtml = buildEmailHtml(senderName, comments);

    const resendResponse = await doFetch(RESEND_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: recipientEmail,
        subject: subject || DEFAULT_SUBJECT,
        html: emailHtml,
        attachments: [{ filename: 'nutrition-plan.pdf', content: pdfAttachment }],
      }),
    });

    const resendData = await resendResponse.json();

    if (!resendResponse.ok) {
      console.error('Resend API error:', resendData);
      return json(
        { success: false, error: resendData.message || 'Failed to send email' },
        resendResponse.status,
      );
    }

    return json(
      { success: true, message: 'Email sent successfully', emailId: resendData.id },
      200,
    );
  } catch (error) {
    console.error('Error sending email:', error);
    return json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
      },
      500,
    );
  }
}
