import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') || 're_DHjg7ayY_PmqLvMtUm7W5GXJaugAtQn93';
// const FROM_EMAIL = 'onboarding@resend.dev'; // Will change to support@mealvana.io after DNS verification
const FROM_EMAIL = 'support@mealvana.io'; // Will change to support@mealvana.io after DNS verification
serve(async (req)=>{
  // CORS headers
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type'
  };
  // Handle OPTIONS request for CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', {
      headers: corsHeaders
    });
  }
  try {
    // Parse request body
    const requestData = await req.json();
    const { recipientEmail, senderName, subject, comments, pdfAttachment } = requestData;
    // Validate required fields
    if (!recipientEmail) {
      return new Response(JSON.stringify({
        success: false,
        error: 'Recipient email is required'
      }), {
        status: 400,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        }
      });
    }
    if (!pdfAttachment) {
      return new Response(JSON.stringify({
        success: false,
        error: 'PDF attachment is required'
      }), {
        status: 400,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        }
      });
    }
    // Build email HTML content
    const emailHtml = `
      <html>
        <head>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
            }
            .header {
              text-align: center;
              padding: 20px 0;
              border-bottom: 2px solid #381633;
            }
            .content {
              padding: 20px 0;
            }
            .footer {
              text-align: center;
              padding: 20px 0;
              border-top: 1px solid #ddd;
              font-size: 12px;
              color: #666;
            }
            .comments {
              background-color: #f8f6eb;
              padding: 15px;
              border-radius: 8px;
              margin: 20px 0;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h2 style="color: #381633; margin: 0;">Nutrition Plan from Mealvana Endurance</h2>
          </div>
          <div class="content">
            ${senderName ? `<p><strong>From:</strong> ${senderName}</p>` : ''}
            ${comments ? `<div class="comments"><p><strong>Message:</strong></p><p>${comments}</p></div>` : ''}
            <p>Please find your personalized nutrition plan attached as a PDF.</p>
            <p>This plan was generated by Mealvana Endurance, designed specifically for endurance athletes.</p>
          </div>
          <div class="footer">
            <p>Generated with Mealvana Endurance</p>
            <p><a href="https://mealvana.io" style="color: #381633;">mealvana.io</a></p>
          </div>
        </body>
      </html>
    `;
    // Send email via Resend API
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: recipientEmail,
        subject: subject || 'Your Nutrition Plan from Mealvana Endurance',
        html: emailHtml,
        attachments: [
          {
            filename: 'nutrition-plan.pdf',
            content: pdfAttachment
          }
        ]
      })
    });
    const resendData = await resendResponse.json();
    // Check if email was sent successfully
    if (!resendResponse.ok) {
      console.error('Resend API error:', resendData);
      return new Response(JSON.stringify({
        success: false,
        error: resendData.message || 'Failed to send email'
      }), {
        status: resendResponse.status,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        }
      });
    }
    // Return success response
    return new Response(JSON.stringify({
      success: true,
      message: 'Email sent successfully',
      emailId: resendData.id
    }), {
      status: 200,
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/json'
      }
    });
  } catch (error) {
    console.error('Error sending email:', error);
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    }), {
      status: 500,
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/json'
      }
    });
  }
});
