/**
 * Unit Tests for send-nutrition-plan-email Edge Function
 *
 * Tests template rendering, Resend API call assembly, validation of required
 * fields, graceful error handling, and edge cases.
 *
 * Stubs global `fetch` for the Resend API — no network required.
 *
 * Run with:
 *   deno test --allow-env supabase/functions/send-nutrition-plan-email/index.test.ts
 */

import {
  assertEquals,
  assertExists,
  assert,
} from 'https://deno.land/std@0.168.0/testing/asserts.ts';
import { describe, it } from 'https://deno.land/std@0.168.0/testing/bdd.ts';

// ---------------------------------------------------------------------------
// Constants (mirrored from production)
// ---------------------------------------------------------------------------

const FROM_EMAIL = 'support@mealvana.io';
const DEFAULT_SUBJECT = 'Your Nutrition Plan from Mealvana Endurance';
const RESEND_API_URL = 'https://api.resend.com/emails';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface EmailPayload {
  recipientEmail?: string;
  senderName?: string;
  subject?: string;
  comments?: string;
  pdfAttachment?: string;
}

interface ResendRequestCapture {
  url: string;
  method: string;
  headers: Record<string, string>;
  body: {
    from: string;
    to: string;
    subject: string;
    html: string;
    attachments: Array<{ filename: string; content: string }>;
  };
}

// ---------------------------------------------------------------------------
// Handler — mirrors send-nutrition-plan-email/index.ts with injectable fetch
// ---------------------------------------------------------------------------

type FetchStub = (url: string | URL, init?: RequestInit) => Promise<Response>;

async function handleSendEmail(
  payload: EmailPayload,
  fakeFetch: FetchStub,
  apiKey = 'test-resend-api-key',
): Promise<Response> {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  };

  const { recipientEmail, senderName, subject, comments, pdfAttachment } = payload;

  // Validate required: recipientEmail
  if (!recipientEmail) {
    return new Response(
      JSON.stringify({ success: false, error: 'Recipient email is required' }),
      {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    );
  }

  // Validate required: pdfAttachment
  if (!pdfAttachment) {
    return new Response(
      JSON.stringify({ success: false, error: 'PDF attachment is required' }),
      {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    );
  }

  // Build HTML template
  const emailHtml = `
    <html>
      <head>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            text-align: center;
            padding: 20px 0;
            border-bottom: 2px solid #381633;
          }
          .content {
            padding: 20px 0;
          }
          .footer {
            text-align: center;
            padding: 20px 0;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
          }
          .comments {
            background-color: #f8f6eb;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h2 style="color: #381633; margin: 0;">Nutrition Plan from Mealvana Endurance</h2>
        </div>
        <div class="content">
          ${senderName ? `<p><strong>From:</strong> ${senderName}</p>` : ''}
          ${comments ? `<div class="comments"><p><strong>Message:</strong></p><p>${comments}</p></div>` : ''}
          <p>Please find your personalized nutrition plan attached as a PDF.</p>
          <p>This plan was generated by Mealvana Endurance, designed specifically for endurance athletes.</p>
        </div>
        <div class="footer">
          <p>Generated with Mealvana Endurance</p>
          <p><a href="https://mealvana.io" style="color: #381633;">mealvana.io</a></p>
        </div>
      </body>
    </html>
  `;

  try {
    const resendResponse = await fakeFetch(RESEND_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: recipientEmail,
        subject: subject || DEFAULT_SUBJECT,
        html: emailHtml,
        attachments: [
          {
            filename: 'nutrition-plan.pdf',
            content: pdfAttachment,
          },
        ],
      }),
    });

    const resendData = await resendResponse.json();

    if (!resendResponse.ok) {
      return new Response(
        JSON.stringify({ success: false, error: resendData.message || 'Failed to send email' }),
        {
          status: resendResponse.status,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        },
      );
    }

    return new Response(
      JSON.stringify({ success: true, message: 'Email sent successfully', emailId: resendData.id }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    );
  }
}

// ---------------------------------------------------------------------------
// Fake fetch helpers
// ---------------------------------------------------------------------------

/** Captures the outgoing Resend request for assertion */
function capturingFetch(
  resendResponse: { id?: string; message?: string } = { id: 'email-id-123' },
  status = 200,
): { fakeFetch: FetchStub; captured: () => ResendRequestCapture | null } {
  let capture: ResendRequestCapture | null = null;

  const fakeFetch: FetchStub = async (url, init) => {
    const body = init?.body ? JSON.parse(init.body as string) : {};
    const headers = init?.headers as Record<string, string> ?? {};
    capture = {
      url: url.toString(),
      method: init?.method ?? 'GET',
      headers,
      body,
    };
    return new Response(JSON.stringify(resendResponse), {
      status,
      headers: { 'Content-Type': 'application/json' },
    });
  };

  return { fakeFetch, captured: () => capture };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('send-nutrition-plan-email — input validation', () => {
  it('returns 400 when recipientEmail is missing', async () => {
    const { fakeFetch } = capturingFetch();
    const res = await handleSendEmail({ pdfAttachment: 'base64data' }, fakeFetch);
    assertEquals(res.status, 400);
    const body = await res.json();
    assertEquals(body.success, false);
    assert(body.error.includes('Recipient email'));
  });

  it('returns 400 when pdfAttachment is missing', async () => {
    const { fakeFetch } = capturingFetch();
    const res = await handleSendEmail({ recipientEmail: 'athlete@example.com' }, fakeFetch);
    assertEquals(res.status, 400);
    const body = await res.json();
    assertEquals(body.success, false);
    assert(body.error.includes('PDF attachment'));
  });

  it('returns 400 when both recipientEmail and pdfAttachment are missing', async () => {
    const { fakeFetch } = capturingFetch();
    const res = await handleSendEmail({}, fakeFetch);
    assertEquals(res.status, 400);
    // recipientEmail is checked first
    assert((await res.json()).error.includes('Recipient email'));
  });

  it('does NOT call Resend API when validation fails', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail({ pdfAttachment: 'data' /* no recipientEmail */ }, fakeFetch);
    assertEquals(captured(), null, 'Resend API should not be called when validation fails');
  });
});

describe('send-nutrition-plan-email — Resend API call assembly', () => {
  const validPayload: EmailPayload = {
    recipientEmail: 'athlete@ironman.com',
    pdfAttachment: 'JVBERi0xLjQ...', // fake base64
    senderName: 'Coach Lee',
    subject: 'Your Race Day Fuel Plan',
    comments: 'Great job on your long run!',
  };

  it('sends to correct Resend endpoint', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch);
    assertEquals(captured()?.url, RESEND_API_URL);
  });

  it('uses POST method', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch);
    assertEquals(captured()?.method, 'POST');
  });

  it('sends from support@mealvana.io', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch);
    assertEquals(captured()?.body.from, FROM_EMAIL);
  });

  it('sends to the provided recipientEmail', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch);
    assertEquals(captured()?.body.to, 'athlete@ironman.com');
  });

  it('uses the provided subject when supplied', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch);
    assertEquals(captured()?.body.subject, 'Your Race Day Fuel Plan');
  });

  it('uses the default subject when subject is omitted', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(captured()?.body.subject, DEFAULT_SUBJECT);
  });

  it('attaches PDF with filename nutrition-plan.pdf', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch);
    const attachments = captured()?.body.attachments;
    assertExists(attachments);
    assertEquals(attachments!.length, 1);
    assertEquals(attachments![0].filename, 'nutrition-plan.pdf');
    assertEquals(attachments![0].content, 'JVBERi0xLjQ...');
  });

  it('includes Bearer token in Authorization header', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(validPayload, fakeFetch, 'my-test-api-key');
    assertEquals(captured()?.headers['Authorization'], 'Bearer my-test-api-key');
  });
});

describe('send-nutrition-plan-email — HTML template rendering', () => {
  it('renders senderName when provided', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data', senderName: 'Lee Martin' },
      fakeFetch,
    );
    const html = captured()?.body.html ?? '';
    assert(html.includes('Lee Martin'), 'HTML should contain sender name');
    assert(html.includes('From:'), 'HTML should contain From: label');
  });

  it('does NOT render senderName section when omitted', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' /* no senderName */ },
      fakeFetch,
    );
    const html = captured()?.body.html ?? '';
    assert(!html.includes('<strong>From:</strong>'), 'From section should be absent when senderName not provided');
  });

  it('renders comments section when provided', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      {
        recipientEmail: 'a@b.com',
        pdfAttachment: 'data',
        comments: 'Stay hydrated during the run!',
      },
      fakeFetch,
    );
    const html = captured()?.body.html ?? '';
    assert(html.includes('Stay hydrated during the run!'));
    assert(html.includes('Message:'));
  });

  it('does NOT render comments section when omitted', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' /* no comments */ },
      fakeFetch,
    );
    const html = captured()?.body.html ?? '';
    assert(!html.includes('<strong>Message:</strong>'), 'Message section should be absent when comments not provided');
  });

  it('HTML always contains the Mealvana branding header', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    const html = captured()?.body.html ?? '';
    assert(html.includes('Nutrition Plan from Mealvana Endurance'));
    assert(html.includes('mealvana.io'));
    assert(html.includes('#381633'), 'Brand colour should be in HTML');
  });

  it('HTML contains the PDF description text', async () => {
    const { fakeFetch, captured } = capturingFetch();
    await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    const html = captured()?.body.html ?? '';
    assert(html.includes('personalized nutrition plan attached as a PDF'));
  });
});

describe('send-nutrition-plan-email — success response', () => {
  it('returns 200 with emailId on success', async () => {
    const { fakeFetch } = capturingFetch({ id: 'resend-email-id-abc' });
    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(res.status, 200);
    const body = await res.json();
    assertEquals(body.success, true);
    assertEquals(body.emailId, 'resend-email-id-abc');
    assertEquals(body.message, 'Email sent successfully');
  });
});

describe('send-nutrition-plan-email — error handling', () => {
  it('returns Resend error status when Resend API fails', async () => {
    const { fakeFetch } = capturingFetch(
      { message: 'Invalid API key' },
      401,
    );
    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(res.status, 401);
    const body = await res.json();
    assertEquals(body.success, false);
    assertEquals(body.error, 'Invalid API key');
  });

  it('returns 422 status code when Resend returns 422 (e.g. bad email format)', async () => {
    const { fakeFetch } = capturingFetch(
      { message: 'Invalid email address' },
      422,
    );
    const res = await handleSendEmail(
      { recipientEmail: 'not-an-email', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(res.status, 422);
    const body = await res.json();
    assertEquals(body.success, false);
    // NOTE: The function does NOT validate email format itself — it relies on
    // Resend to reject malformed addresses. This is a seam where a bad address
    // still reaches the API.
  });

  it('returns 500 when fetch throws (network error)', async () => {
    const fakeFetch: FetchStub = () => Promise.reject(new Error('connection refused'));
    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(res.status, 500);
    const body = await res.json();
    assertEquals(body.success, false);
    assert(body.error.includes('connection refused'));
  });

  it('returns 500 when fetch throws a non-Error object', async () => {
    const fakeFetch: FetchStub = () => Promise.reject('string error');
    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(res.status, 500);
    const body = await res.json();
    assertEquals(body.success, false);
    assertEquals(body.error, 'Unknown error occurred');
  });

  it('uses fallback error message when Resend response has no message field', async () => {
    // deno-lint-ignore no-explicit-any
    const { fakeFetch } = capturingFetch({ } as any, 500); // empty body — no 'message' field
    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: 'data' },
      fakeFetch,
    );
    const body = await res.json();
    assertEquals(body.error, 'Failed to send email');
  });
});

describe('send-nutrition-plan-email — edge cases', () => {
  it('handles empty string recipientEmail as missing (returns 400)', async () => {
    const { fakeFetch } = capturingFetch();
    const res = await handleSendEmail(
      { recipientEmail: '', pdfAttachment: 'data' },
      fakeFetch,
    );
    assertEquals(res.status, 400);
  });

  it('handles empty string pdfAttachment as missing (returns 400)', async () => {
    const { fakeFetch } = capturingFetch();
    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: '' },
      fakeFetch,
    );
    assertEquals(res.status, 400);
  });

  it('BUG NOTE: API key is partially hardcoded in production source', () => {
    // The production file has:
    //   const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') || 're_DHjg7ayY_...';
    // This means if RESEND_API_KEY is unset the hardcoded key is used.
    // The key should be rotated and the fallback removed.
    // Severity: MEDIUM — the key is in source control.
    assert(true, 'Bug documented — see comment above');
  });

  it('sends large PDF attachments without truncation', async () => {
    // Generate a ~50KB fake base64 payload (realistic PDF size)
    const largePdf = 'A'.repeat(50 * 1024);
    const { fakeFetch, captured } = capturingFetch({ id: 'big-email' });

    const res = await handleSendEmail(
      { recipientEmail: 'a@b.com', pdfAttachment: largePdf },
      fakeFetch,
    );

    assertEquals(res.status, 200);
    assertEquals(
      captured()?.body.attachments[0].content.length,
      largePdf.length,
      'Large PDF content must not be truncated',
    );
  });
});
