-- ============================================================================
-- Migration: Add post-workout recovery foods to template_foods catalog
--
-- Purpose: Insert 20 new recovery-specific foods needed by post_workout_templates.
-- Idempotent via ON CONFLICT(name) — safe to re-run.
--
-- Source: docs/features/formula_templates/post_workout_template_foods.json
-- Date: 2026-04-08
-- ============================================================================

INSERT INTO public.template_foods (
  name,
  display_name,
  serving_size,
  serving_weight_g,
  calories,
  carbs_g,
  protein_g,
  fat_g,
  fiber_g,
  sodium_mg,
  fluid_ml,
  allergens,
  digestion_speed,
  is_active,
  excluded_diets,
  product_type,
  activity_types,
  categories,
  show_in_preferences,
  is_essential,
  is_electrolyte,
  requires_preparation,
  caffeine_mg,
  potassium_mg,
  is_drink_pool,
  drink_pool_phases,
  is_liquid,
  max_servings_before,
  max_servings_during,
  max_servings_after,
  to_exclude_from_solver,
  display_name_plural,
  description,
  serving_amount,
  serving_unit,
  serving_qualifier,
  is_indivisible,
  default_during,
  min_servings_during
)
VALUES
  -- ========== PROTEIN SOURCES ==========

  -- Whey Protein Powder
  (
    'whey_protein_powder',
    'Whey Protein Powder',
    '1 scoop (30g)',
    30.0,
    120,
    3.0, 25.0, 1.5,
    0.0,
    130.0,
    0.0,
    '{dairy}'::text[],
    'fast',
    true,
    '{vegan}'::text[],
    'supplement',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, true, 0.0, 160.0,
    false, '{}'::text[], false,
    0, 0, 2,
    false,
    'scoops Whey Protein Powder',
    'Whey protein isolate/concentrate. ~3g leucine per scoop for maximum muscle protein synthesis.',
    1, NULL, NULL, true, false, 0
  ),

  -- Plant Protein Powder
  (
    'plant_protein_powder',
    'Plant Protein Powder',
    '1 scoop (35g)',
    35.0,
    130,
    5.0, 22.0, 2.5,
    2.0,
    300.0,
    0.0,
    '{}'::text[],
    'medium',
    true,
    '{paleo}'::text[],
    'supplement',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, true, 0.0, 120.0,
    false, '{}'::text[], false,
    0, 0, 2,
    false,
    'scoops Plant Protein Powder',
    'Pea + rice protein blend. Complete amino acid profile. ~2g leucine per scoop. Vegan-friendly.',
    1, NULL, NULL, true, false, 0
  ),

  -- Grilled Chicken Breast
  (
    'grilled_chicken',
    'Grilled Chicken Breast',
    '4 oz (113g)',
    113.0,
    130,
    0.0, 26.0, 3.0,
    0.0,
    60.0,
    0.0,
    '{}'::text[],
    'slow',
    true,
    '{vegan,vegetarian}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, true, 0.0, 310.0,
    false, '{}'::text[], false,
    0, 0, 3,
    false,
    'servings Grilled Chicken Breast',
    'Lean protein, high leucine (~2.5g per serving). Meal-prep staple for recovery bowls.',
    1, NULL, NULL, false, false, 0
  ),

  -- Salmon (cooked)
  (
    'salmon',
    'Salmon (cooked)',
    '4 oz (113g)',
    113.0,
    210,
    0.0, 23.0, 12.0,
    0.0,
    60.0,
    0.0,
    '{fish}'::text[],
    'slow',
    true,
    '{vegan,vegetarian}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, true, 0.0, 430.0,
    false, '{}'::text[], false,
    0, 0, 2,
    false,
    'servings Salmon',
    'Rich in omega-3 EPA/DHA. Powerful anti-inflammatory. Elite triathlete recovery staple.',
    1, NULL, NULL, false, false, 0
  ),

  -- Tofu (firm)
  (
    'tofu',
    'Tofu (firm)',
    '4 oz (113g)',
    113.0,
    90,
    2.0, 10.0, 5.0,
    1.0,
    15.0,
    0.0,
    '{soy}'::text[],
    'medium',
    true,
    '{paleo}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, true, 0.0, 150.0,
    false, '{}'::text[], false,
    0, 0, 3,
    false,
    'servings Tofu',
    'Complete plant protein. Vegan recovery meal protein source. Versatile in stir-fry, bowls.',
    1, NULL, NULL, false, false, 0
  ),

  -- Beef Jerky
  (
    'beef_jerky',
    'Beef Jerky',
    '1 oz (28g)',
    28.0,
    80,
    5.0, 13.0, 1.0,
    0.0,
    590.0,
    0.0,
    '{}'::text[],
    'slow',
    true,
    '{vegan,vegetarian}'::text[],
    'whole_food',
    '{running,cycling}'::text[],
    '{after_run}'::text[],
    true,
    false, false, false, 0.0, 180.0,
    false, '{}'::text[], false,
    0, 0, 4,
    false,
    'oz Beef Jerky',
    'High leucine, very salty (replaces sodium). No refrigeration. Ultra runner portable favorite.',
    1, NULL, NULL, false, false, 0
  ),

  -- Cheddar Cheese
  (
    'cheddar_cheese',
    'Cheddar Cheese',
    '1 oz (28g)',
    28.0,
    115,
    0.5, 7.0, 9.5,
    0.0,
    180.0,
    0.0,
    '{dairy}'::text[],
    'slow',
    true,
    '{vegan,paleo}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, false, 0.0, 28.0,
    false, '{}'::text[], false,
    0, 0, 2,
    false,
    'oz Cheddar Cheese',
    'Adds protein + calcium + sodium to burritos/bowls.',
    1, NULL, NULL, false, false, 0
  ),

  -- ========== CARB / VEGETABLE SOURCES ==========

  -- Black Beans (canned)
  (
    'black_beans',
    'Black Beans (canned)',
    '1/2 cup',
    130.0,
    110,
    20.0, 7.0, 0.5,
    7.0,
    460.0,
    0.0,
    '{}'::text[],
    'medium',
    true,
    '{paleo}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, false, 0.0, 305.0,
    false, '{}'::text[], false,
    0, 0, 3,
    false,
    'servings Black Beans',
    'Complex carbs + plant protein + fiber. Burrito/bowl staple. High sodium for electrolyte replacement.',
    0.5, 'cup', NULL, false, false, 0
  ),

  -- Whole Wheat Tortilla
  (
    'whole_wheat_tortilla',
    'Whole Wheat Tortilla',
    '1 large (10")',
    64.0,
    210,
    36.0, 6.0, 5.0,
    3.0,
    540.0,
    0.0,
    '{gluten}'::text[],
    'medium',
    true,
    '{paleo}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, false, 0.0, 85.0,
    false, '{}'::text[], false,
    0, 0, 2,
    false,
    'Whole Wheat Tortillas',
    'Burrito base. Dense carbs + sodium. Freezer-friendly for batch meal prep.',
    1, NULL, NULL, true, false, 0
  ),

  -- Broccoli (steamed)
  (
    'broccoli',
    'Broccoli (steamed)',
    '1 cup',
    156.0,
    55,
    11.0, 4.0, 0.5,
    5.0,
    65.0,
    130.0,
    '{}'::text[],
    'medium',
    true,
    '{}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, true, 0.0, 460.0,
    false, '{}'::text[], false,
    0, 0, 3,
    false,
    'cups Broccoli',
    'Vitamins C, K, folate. High potassium. Recovery bowl vegetable component.',
    1, 'cup', NULL, false, false, 0
  ),

  -- Mixed Vegetables (stir-fry)
  (
    'mixed_vegetables',
    'Mixed Vegetables (stir-fry)',
    '1 cup',
    150.0,
    60,
    12.0, 3.0, 0.5,
    4.0,
    45.0,
    120.0,
    '{}'::text[],
    'medium',
    true,
    '{}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, true, 0.0, 300.0,
    false, '{}'::text[], false,
    0, 0, 3,
    false,
    'cups Mixed Vegetables',
    'Generic stir-fry vegetables (bell peppers, snap peas, carrots, broccoli).',
    1, 'cup', NULL, false, false, 0
  ),

  -- Avocado
  (
    'avocado',
    'Avocado',
    '1/2 medium',
    68.0,
    120,
    6.0, 1.5, 11.0,
    5.0,
    5.0,
    55.0,
    '{}'::text[],
    'slow',
    true,
    '{}'::text[],
    'whole_food',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, false, 0.0, 345.0,
    false, '{}'::text[], false,
    0, 0, 2,
    false,
    'halves Avocado',
    'Healthy monounsaturated fats + potassium (345mg). Anti-inflammatory.',
    0.5, NULL, 'medium', false, false, 0
  ),

  -- ========== BEVERAGES ==========

  -- Tart Cherry Juice
  (
    'tart_cherry_juice',
    'Tart Cherry Juice',
    '1 cup (8 oz)',
    240.0,
    140,
    33.0, 1.0, 0.0,
    0.0,
    15.0,
    230.0,
    '{}'::text[],
    'fast',
    true,
    '{}'::text[],
    'beverage',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, false, 0.0, 410.0,
    false, '{}'::text[], true,
    1, 0, 2,
    false,
    'cups Tart Cherry Juice',
    '100% pure tart cherry juice. Anthocyanins reduce inflammation by up to 49%. Best with 7-10 day pre-loading.',
    1, 'cup', NULL, false, false, 0
  ),

  -- Recovery Drink Mix
  (
    'recovery_drink_mix',
    'Recovery Drink Mix',
    '1 serving (mix in 16 oz water)',
    55.0,
    200,
    40.0, 15.0, 1.0,
    0.0,
    200.0,
    475.0,
    '{dairy}'::text[],
    'fast',
    true,
    '{vegan}'::text[],
    'supplement',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, true, 0.0, 180.0,
    false, '{}'::text[], true,
    0, 0, 2,
    false,
    'servings Recovery Drink Mix',
    'Generic 3:1 carb:protein recovery powder. Brands: Skratch Recovery, Hammer Recoverite, SiS REGO.',
    1, NULL, NULL, true, false, 0
  ),

  -- Core Power Elite Shake
  (
    'core_power_shake',
    'Core Power Elite Shake',
    '1 bottle (14 oz)',
    414.0,
    230,
    16.0, 42.0, 4.5,
    0.0,
    260.0,
    400.0,
    '{dairy}'::text[],
    'medium',
    true,
    '{vegan,paleo}'::text[],
    'beverage',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    true,
    false, false, false, 0.0, 580.0,
    false, '{}'::text[], true,
    0, 0, 2,
    false,
    'bottles Core Power Elite Shake',
    'Ultra-filtered milk protein RTD. 42g protein, zero prep. Available at gas stations.',
    1, NULL, NULL, true, false, 0
  ),

  -- Low-Fat Milk (1%)
  (
    'milk_lowfat',
    'Low-Fat Milk (1%)',
    '1 cup (8 oz)',
    244.0,
    105,
    13.0, 8.5, 2.5,
    0.0,
    110.0,
    220.0,
    '{dairy}'::text[],
    'medium',
    true,
    '{vegan,paleo}'::text[],
    'beverage',
    '{running,cycling,swimming}'::text[],
    '{after_run,before_run}'::text[],
    true,
    false, false, false, 0.0, 370.0,
    true, '{snack,top_up}'::text[], true,
    2, 0, 3,
    false,
    'cups Low-Fat Milk',
    'Classic recovery beverage base. Provides carbs, protein, fluid, calcium, sodium, potassium.',
    1, 'cup', NULL, false, false, 0
  ),

  -- Oat Milk
  (
    'oat_milk',
    'Oat Milk',
    '1 cup (8 oz)',
    240.0,
    120,
    16.0, 3.0, 5.0,
    2.0,
    100.0,
    220.0,
    '{gluten}'::text[],
    'medium',
    true,
    '{paleo}'::text[],
    'beverage',
    '{running,cycling,swimming}'::text[],
    '{after_run,before_run}'::text[],
    true,
    false, false, false, 0.0, 190.0,
    false, '{}'::text[], true,
    2, 0, 3,
    false,
    'cups Oat Milk',
    'Vegan milk alternative. Adds carbs + creamy texture to smoothies. Often fortified with calcium.',
    1, 'cup', NULL, false, false, 0
  ),

  -- ========== CONDIMENTS / EXTRAS ==========

  -- Salsa
  (
    'salsa',
    'Salsa',
    '2 tbsp',
    30.0,
    10,
    2.0, 0.0, 0.0,
    0.5,
    200.0,
    25.0,
    '{}'::text[],
    'fast',
    true,
    '{}'::text[],
    'condiment',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, false, 0.0, 60.0,
    false, '{}'::text[], false,
    0, 0, 4,
    true,
    'tbsp Salsa',
    'Low calorie. Adds sodium (electrolyte) + flavor to burritos/bowls.',
    2, 'tbsp', NULL, false, false, 0
  ),

  -- Soy Sauce
  (
    'soy_sauce',
    'Soy Sauce',
    '1 tbsp',
    18.0,
    10,
    1.0, 1.0, 0.0,
    0.0,
    900.0,
    15.0,
    '{soy,gluten}'::text[],
    'fast',
    true,
    '{paleo}'::text[],
    'condiment',
    '{running,cycling,swimming}'::text[],
    '{after_run}'::text[],
    false,
    false, false, false, 0.0, 30.0,
    false, '{}'::text[], true,
    0, 0, 2,
    true,
    'tbsp Soy Sauce',
    'High sodium condiment for stir-fry. Replaces electrolytes lost in sweat.',
    1, 'tbsp', NULL, false, false, 0
  ),

  -- Trail Mix
  (
    'trail_mix',
    'Trail Mix',
    '1/4 cup (35g)',
    35.0,
    175,
    15.0, 5.0, 12.0,
    2.0,
    55.0,
    0.0,
    '{tree_nuts}'::text[],
    'medium',
    true,
    '{}'::text[],
    'whole_food',
    '{running,cycling}'::text[],
    '{after_run}'::text[],
    true,
    false, false, false, 0.0, 120.0,
    false, '{}'::text[], false,
    0, 0, 4,
    false,
    'servings Trail Mix',
    'Nuts + dried fruit + dark chocolate chips. Portable, calorie-dense. Antioxidants from dark chocolate.',
    0.25, 'cup', NULL, false, false, 0
  )

ON CONFLICT (name)
DO UPDATE SET
  display_name = EXCLUDED.display_name,
  serving_size = EXCLUDED.serving_size,
  serving_weight_g = EXCLUDED.serving_weight_g,
  calories = EXCLUDED.calories,
  carbs_g = EXCLUDED.carbs_g,
  protein_g = EXCLUDED.protein_g,
  fat_g = EXCLUDED.fat_g,
  fiber_g = EXCLUDED.fiber_g,
  sodium_mg = EXCLUDED.sodium_mg,
  fluid_ml = EXCLUDED.fluid_ml,
  allergens = EXCLUDED.allergens,
  digestion_speed = EXCLUDED.digestion_speed,
  is_active = EXCLUDED.is_active,
  excluded_diets = EXCLUDED.excluded_diets,
  product_type = EXCLUDED.product_type,
  activity_types = (
    SELECT COALESCE(array_agg(DISTINCT a), '{}'::text[])
    FROM unnest(coalesce(public.template_foods.activity_types, '{}'::text[]) || EXCLUDED.activity_types) AS u(a)
  ),
  categories = (
    SELECT COALESCE(array_agg(DISTINCT c), '{}'::text[])
    FROM unnest(coalesce(public.template_foods.categories, '{}'::text[]) || EXCLUDED.categories) AS u(c)
  ),
  show_in_preferences = EXCLUDED.show_in_preferences,
  is_essential = EXCLUDED.is_essential,
  is_electrolyte = EXCLUDED.is_electrolyte,
  requires_preparation = EXCLUDED.requires_preparation,
  caffeine_mg = EXCLUDED.caffeine_mg,
  potassium_mg = EXCLUDED.potassium_mg,
  is_drink_pool = EXCLUDED.is_drink_pool,
  drink_pool_phases = (
    SELECT COALESCE(array_agg(DISTINCT p), '{}'::text[])
    FROM unnest(coalesce(public.template_foods.drink_pool_phases, '{}'::text[]) || EXCLUDED.drink_pool_phases) AS u(p)
  ),
  is_liquid = EXCLUDED.is_liquid,
  max_servings_before = GREATEST(coalesce(public.template_foods.max_servings_before, 0), EXCLUDED.max_servings_before),
  max_servings_during = GREATEST(coalesce(public.template_foods.max_servings_during, 0), EXCLUDED.max_servings_during),
  max_servings_after = GREATEST(coalesce(public.template_foods.max_servings_after, 0), EXCLUDED.max_servings_after),
  to_exclude_from_solver = EXCLUDED.to_exclude_from_solver,
  display_name_plural = EXCLUDED.display_name_plural,
  description = EXCLUDED.description,
  serving_amount = EXCLUDED.serving_amount,
  serving_unit = EXCLUDED.serving_unit,
  serving_qualifier = EXCLUDED.serving_qualifier,
  is_indivisible = EXCLUDED.is_indivisible,
  default_during = (public.template_foods.default_during OR EXCLUDED.default_during),
  min_servings_during = EXCLUDED.min_servings_during,
  updated_at = now();

-- ============================================================================
-- Verification query (uncomment to check)
-- ============================================================================
-- SELECT name, display_name, carbs_g, protein_g, fat_g, sodium_mg, categories, is_active
-- FROM public.template_foods
-- WHERE name IN (
--   'whey_protein_powder','plant_protein_powder','grilled_chicken','salmon','tofu',
--   'beef_jerky','cheddar_cheese','black_beans','whole_wheat_tortilla','broccoli',
--   'mixed_vegetables','avocado','tart_cherry_juice','recovery_drink_mix',
--   'core_power_shake','milk_lowfat','oat_milk','salsa','soy_sauce','trail_mix'
-- )
-- ORDER BY name;
