#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the meal-planning sandbox trial run (ticket 21; mp-270, mp-289).
#
# A person with a fresh sandbox account on each store subscribes through the
# seven-day introductory offer, and this wizard checks DEV after each step:
# the entitlement row is active on day one, the Allowance landed, the
# cancellation arrived, the trial ended on the paywall, and Restore reopened
# the app. Every step and its evidence go into a dated log under
# docs/release/sandbox-trial-runs/, which is committed with the release.
# No meal-planning release without a GREEN log on both stores
# (docs/deployment/supabase-deploy-playbook.md §8, P3c).
#
# Usage (from the repo root, on the branch whose build is on the device):
#   scripts/sandbox-trial-wizard.sh              # both stores, iOS first
#   scripts/sandbox-trial-wizard.sh ios          # one store
#   scripts/sandbox-trial-wizard.sh android
#   scripts/sandbox-trial-wizard.sh preflight    # read-only DEV checks, no prompts
#
# Safety, by construction:
#   - DEV only. The project ref is a constant; there is no flag to change it.
#   - Read only. Every query must be a SELECT and is sent with read_only:true
#     (the Management API runs it in a read-only transaction).
#   - Never in CI (mp-289): refuses to start when CI variables are set or
#     stdin is not a terminal.
#   - Writes nothing but the log file. No RevenueCat, App Store Connect or
#     Play Console calls: the store steps are the human's.
#
# Auth: $SUPABASE_MANAGEMENT_TOKEN, else secrets/supabase_management_api.env
# (this checkout, then the main clone), else ~/.supabase/pat.
# ──────────────────────────────────────────────────────────────────────────

readonly DEV_REF="vlmtsdzpnjnavdgytcmi"
readonly API="https://api.supabase.com/v1"
readonly DEV_IOS_BUNDLE="com.milkman.mealvanaendurance.dev"
readonly DEV_ANDROID_PACKAGE="com.milkman.mealvanaendurance.dev"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RUNS_DIR="$REPO_ROOT/docs/release/sandbox-trial-runs"

MGMT_TOKEN=""
LOG_FILE=""
STORE=""
STORE_FAILS=0
LAST_JSON=""
VERDICTS=()

usage() {
  awk 'f && /^# ─/ {exit} f {sub(/^# ?/, ""); print} /^# STAGES: the meal-planning/ {f=1}' "$0"
}

die() { printf '%s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

refuse_ci() {
  local v
  for v in CI CODEMAGIC CM_BUILD_ID GITHUB_ACTIONS BUILDKITE JENKINS_URL; do
    if [[ -n "${!v:-}" ]]; then
      die "refusing to run: \$$v is set. The sandbox trial is run by hand and never in CI (mp-289)."
    fi
  done
}

load_token() {
  if [[ -n "${SUPABASE_MANAGEMENT_TOKEN:-}" ]]; then MGMT_TOKEN="$SUPABASE_MANAGEMENT_TOKEN"; return; fi
  local common f line
  common="$(git -C "$REPO_ROOT" rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"
  for f in "$REPO_ROOT/secrets/supabase_management_api.env" "${common%/.git}/secrets/supabase_management_api.env"; do
    [[ -r "$f" ]] || continue
    line="$(grep -E '^SUPABASE_MANAGEMENT_TOKEN=' "$f" | tail -n1 || true)"
    if [[ -n "$line" ]]; then MGMT_TOKEN="${line#*=}"; MGMT_TOKEN="${MGMT_TOKEN//\"/}"; return; fi
  done
  if [[ -r "$HOME/.supabase/pat" ]]; then MGMT_TOKEN="$(tr -d '[:space:]' < "$HOME/.supabase/pat")"; return; fi
  die "no Supabase Management API token: set \$SUPABASE_MANAGEMENT_TOKEN or put one in secrets/supabase_management_api.env"
}

# _curl_auth ARGS... runs curl with the token in a config on stdin-less fd,
# so it never shows in the process list.
_curl_auth() {
  curl -sS --max-time 30 -K <(printf 'header = "Authorization: Bearer %s"\n' "$MGMT_TOKEN") "$@"
}

# dev_select SQL prints the JSON result of a read-only SELECT against DEV.
dev_select() {
  local sql="$1" body
  if ! printf '%s' "$sql" | tr '\n' ' ' | grep -Eiq '^[[:space:]]*(select|with)[[:space:]]'; then
    die "internal: refusing a non-SELECT query"
  fi
  body="$(SQL="$sql" python3 -c 'import json,os; print(json.dumps({"query": os.environ["SQL"], "read_only": True}))')"
  _curl_auth -X POST "$API/projects/$DEV_REF/database/query" \
    -H "Content-Type: application/json" -d "$body"
}

# json_first JSON FIELD prints FIELD of the first row ("" when absent).
json_first() {
  JSON="$1" FIELD="$2" python3 -c '
import json, os
try:
    d = json.loads(os.environ["JSON"])
except Exception:
    d = None
if isinstance(d, list) and d and isinstance(d[0], dict):
    v = d[0].get(os.environ["FIELD"])
    print("" if v is None else (str(v).lower() if isinstance(v, bool) else v))
'
}

json_pretty() {
  JSON="$1" python3 -c '
import json, os
try:
    print(json.dumps(json.loads(os.environ["JSON"]), indent=2))
except Exception:
    print(os.environ["JSON"])
'
}

is_error_json() {
  JSON="$1" python3 -c '
import json, os, sys
try:
    d = json.loads(os.environ["JSON"])
except Exception:
    sys.exit(0)
sys.exit(0 if isinstance(d, dict) and ("message" in d or "error" in d) else 1)
'
}

sql_quote() { printf '%s' "${1//\'/\'\'}"; }

# check SQL: runs a query whose first row carries a boolean `pass`.
check() {
  LAST_JSON="$(dev_select "$1" || true)"
  if is_error_json "$LAST_JSON"; then
    warn "DEV query failed: $LAST_JSON"
    return 1
  fi
  [[ "$(json_first "$LAST_JSON" pass)" == "true" ]]
}

# poll SECONDS SQL: repeats check every 10 s until it passes or time runs out.
poll() {
  local limit="$1" sql="$2" waited=0
  printf '  %schecking DEV every 10 s for up to %s s%s ' "$DIM" "$limit" "$RESET"
  while true; do
    if check "$sql"; then printf '%s✓%s\n' "$GREEN" "$RESET"; return 0; fi
    if (( waited >= limit )); then printf '%s✗%s\n' "$RED" "$RESET"; return 1; fi
    printf '.'
    sleep 10
    waited=$((waited + 10))
  done
}

# webhook_logs USER_ID MINUTES: the webhook's log lines for this user (evidence only).
webhook_logs() {
  local uid="$1" minutes="$2" sql enc start end
  sql="select timestamp, event_message from function_logs where event_message like '%[rc-webhook]%' and event_message like '%${uid}%' order by timestamp asc limit 50"
  enc="$(python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))' "$sql")"
  start="$(date -u -v-"${minutes}"M +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "-${minutes} minutes" +%Y-%m-%dT%H:%M:%SZ)"
  end="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  _curl_auth "$API/projects/$DEV_REF/analytics/endpoints/logs.all?sql=${enc}&iso_timestamp_start=${start}&iso_timestamp_end=${end}" \
    | JSON_IN="$(cat)" python3 -c '
import json, os, datetime
try:
    rows = json.loads(os.environ["JSON_IN"]).get("result") or []
except Exception:
    rows = []
for r in rows:
    ts = datetime.datetime.utcfromtimestamp(r["timestamp"] / 1_000_000).strftime("%H:%M:%SZ")
    print(ts, (r.get("event_message") or "").strip())
if not rows:
    print("(no webhook log lines for this user in the window; logs can lag a minute)")
' 2>/dev/null || true
}

# ── Log ───────────────────────────────────────────────────────────────────

log() { printf '%s\n' "$*" >> "$LOG_FILE"; }

start_log() {
  local store="$1" day base n=1
  day="$(date +%Y-%m-%d)"
  mkdir -p "$RUNS_DIR"
  base="$RUNS_DIR/${day}-${store}"
  LOG_FILE="${base}.md"
  while [[ -e "$LOG_FILE" ]]; do n=$((n + 1)); LOG_FILE="${base}-${n}.md"; done
  STORE_FAILS=0
  {
    printf '# Sandbox trial run: %s, %s\n\n' "$store" "$day"
    printf 'Gate for any meal-planning release (mp-270, mp-289; playbook §8 P3c).\n'
    printf 'Written by `scripts/sandbox-trial-wizard.sh`. Checks are read-only SELECTs against DEV (`%s`).\n\n' "$DEV_REF"
    printf -- '- Started: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf -- '- Build commit: `%s` on `%s`\n' \
      "$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)" \
      "$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
    if [[ -n "$(git -C "$REPO_ROOT" status --porcelain --untracked-files=no 2>/dev/null)" ]]; then
      printf -- '- Working tree had uncommitted changes to tracked files at start\n'
    fi
  } > "$LOG_FILE"
  note "logging to ${LOG_FILE#"$REPO_ROOT"/}"
}

# log_step NAME RESULT [EVIDENCE] where RESULT is PASS or FAIL.
log_step() {
  local name="$1" result="$2" evidence="${3:-}"
  [[ "$result" == "PASS" ]] || STORE_FAILS=$((STORE_FAILS + 1))
  log ""
  log "## ${name}: ${result}"
  log ""
  log "Checked $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  if [[ -n "$evidence" ]]; then
    log ""
    log '```'
    log "$evidence"
    log '```'
  fi
}

close_log() {
  local verdict="$1"
  log ""
  log "## Result: ${verdict}"
  log ""
  log "Finished $(date -u +%Y-%m-%dT%H:%M:%SZ). Commit this file with the release."
  VERDICTS+=("${STORE}: ${verdict} (${LOG_FILE#"$REPO_ROOT"/})")
}

# outcome NAME EVIDENCE: after a failed check, retry / record / abort.
# Returns 0 to retry, 1 when the failure was recorded and the run goes on.
outcome() {
  local name="$1" evidence="$2" reply=""
  printf '\n%s\n' "$(json_pretty "$evidence")" | sed 's/^/    /'
  printf '\n  %s? [r]etry the check, record [f]ail and go on, or [a]bort this store%s ' "$YELLOW" "$RESET"
  read -r reply || true
  case "$reply" in
    r|R) return 0 ;;
    a|A)
      log_step "$name" FAIL "$evidence"
      close_log "RED (aborted at: ${name})"
      finish_store_abort
      ;;
    *) log_step "$name" FAIL "$evidence"; return 1 ;;
  esac
}

# human_check NAME QUESTION: a y/N the checker answers from the device.
human_check() {
  local name="$1" question="$2"
  if confirm "$question"; then
    log_step "$name" PASS "Checker confirmed on the device: ${question}"
    return 0
  fi
  local what=""
  printf '  %sWhat did you see instead?%s ' "$BOLD" "$RESET"
  read -r what || true
  log_step "$name" FAIL "Checker did not confirm: ${question}
Saw instead: ${what}"
  return 1
}

ABORTED=0
finish_store_abort() { ABORTED=1; }

# ── Preflight ─────────────────────────────────────────────────────────────

preflight() {
  local ok=0 json
  command -v curl >/dev/null 2>&1 || die "curl is required"
  command -v python3 >/dev/null 2>&1 || die "python3 is required"
  load_token

  json="$(dev_select "select now() as t" || true)"
  if [[ -n "$(json_first "$json" t)" ]]; then say "DEV reachable, read-only query ran ($(json_first "$json" t))"
  else warn "DEV query failed: $json"; ok=1; fi

  json="$(dev_select "select
      (select count(*) from information_schema.columns where table_schema='public' and table_name='user_entitlements'
         and column_name in ('active_until','period_type','event_at')) = 3
      and (select count(*) from information_schema.columns where table_schema='public' and table_name='token_wallets'
         and column_name in ('allowance','allowance_monthly','allowance_expires_at')) = 3
      and (select count(*) from pg_proc where proname in ('grant_allowance','forfeit_allowance')) >= 2 as pass" || true)"
  if [[ "$(json_first "$json" pass)" == "true" ]]; then say "DEV schema carries the two-field entitlement cache and the Allowance (tickets 18, 20)"
  else warn "DEV schema is missing the ticket 18/20 migrations: $json"; ok=1; fi

  json="$(_curl_auth "$API/projects/$DEV_REF/functions/revenuecat-webhook" || true)"
  if [[ "$(JSON="$json" python3 -c 'import json,os; print(json.loads(os.environ["JSON"]).get("status",""))' 2>/dev/null)" == "ACTIVE" ]]; then
    say "revenuecat-webhook is deployed on DEV (deploy counter $(JSON="$json" python3 -c 'import json,os; print(json.loads(os.environ["JSON"]).get("version"))'))"
  else warn "revenuecat-webhook is not active on DEV: $json"; ok=1; fi

  return $ok
}

# ── One store ─────────────────────────────────────────────────────────────

run_store() {
  STORE="$1"
  ABORTED=0
  local uid="" email="" pack_baseline=0 purchase_event_at="" last_event_at="" q_uid json

  # 1 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: a fresh sandbox account and the dev app on a real device"
  start_log "$STORE"
  if [[ "$STORE" == "ios" ]]; then
    say "The run needs a sandbox Apple Account that has never subscribed, on a physical iPhone."
    say "(The simulator cannot sign into sandbox, and a StoreKit config purchase never reaches RevenueCat.)"
    open_url "https://appstoreconnect.apple.com/access/users/sandbox"
    step "Users and Access → Sandbox → Test Accounts → + : create a tester with an email never used before."
    step "iPhone: Settings → Developer → Sandbox Apple Account → sign in as that tester."
    step "Install this branch's dev app ($DEV_IOS_BUNDLE) on the iPhone:"
    say  "    ./scripts/run_dev.sh -d <iphone device id>     (flutter devices lists it)"
    note "A TestFlight build buys with your own Apple Account, not the fresh tester: it does not count."
  else
    say "The run needs a Google account that has never subscribed to Mealvana Pro, on a physical phone."
    say "(The dev app's 'free-week' offer is for new subscribers only.)"
    open_url "https://play.google.com/console/"
    step "Play Console → Settings → License testing: add the fresh Google account, Save."
    step "Phone: make that account the one the Play Store app uses."
    step "Install this branch's dev app ($DEV_ANDROID_PACKAGE):"
    say  "    ./scripts/run_dev.sh -d <android device id>    (flutter devices lists it)"
    note "If the paywall later says plans aren't available, install the dev app from the internal testing track instead."
  fi
  local device="" store_account=""
  ask SANDBOX_DEVICE "Device model and OS version (e.g. iPhone 15, iOS 26.0):"
  device="$SANDBOX_DEVICE"
  ask SANDBOX_STORE_ACCOUNT "The fresh store account's email:"
  store_account="$SANDBOX_STORE_ACCOUNT"
  log "- Device: ${device}"
  log "- Store account (sandbox): ${store_account}"
  pause "Press Enter when the dev app is open on the device, signed out."

  # 2 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: a new athlete finishes onboarding and lands on the paywall"
  step "In the dev app, sign up with an email that has never had a Mealvana account."
  step "Finish onboarding. It ends on the paywall: Monthly and Annual with store prices,"
  say  "  and the line \"7 days free, then <price>\"."
  while true; do
    ask SANDBOX_APP_EMAIL "The new Mealvana account's email:"
    email="$SANDBOX_APP_EMAIL"
    json="$(dev_select "select u.id::text as user_id,
        p.id is not null as has_profile,
        (select count(*) from public.user_entitlements e where e.user_id = u.id) as entitlement_rows,
        coalesce(w.balance, 0) as balance,
        coalesce(w.allowance, 0) as allowance,
        u.created_at,
        (p.id is not null
          and not exists (select 1 from public.user_entitlements e where e.user_id = u.id)
          and coalesce(w.allowance, 0) = 0) as pass
      from auth.users u
      left join public.users p on p.id = u.id
      left join public.token_wallets w on w.user_id = u.id
      where lower(u.email) = lower('$(sql_quote "$email")')" || true)"
    uid="$(json_first "$json" user_id)"
    if [[ "$uid" =~ ^[0-9a-f-]{36}$ && "$(json_first "$json" pass)" == "true" ]]; then
      say "Found ${uid}: a profile row, no entitlement row, no Allowance. Fresh."
      log "- Mealvana account: ${email} (user id \`${uid}\`)"
      log_step "1. The account is new on DEV" PASS "$(json_pretty "$json")"
      break
    fi
    if [[ -z "$uid" ]]; then warn "No DEV auth user with that email (a typo, or the account was made against another project)."
    else warn "That account is not fresh, or its profile row has not synced yet."; fi
    outcome "1. The account is new on DEV" "${json:-[]}" || { uid="$(json_first "$json" user_id)"; log "- Mealvana account: ${email} (user id \`${uid:-unknown}\`)"; break; }
    [[ $ABORTED == 1 ]] && return
  done
  [[ "$uid" =~ ^[0-9a-f-]{36}$ ]] || { close_log "RED (no DEV user id for the account)"; return; }
  q_uid="$(sql_quote "$uid")"
  local bal alw
  bal="$(json_first "$json" balance)"; alw="$(json_first "$json" allowance)"
  [[ "$bal" =~ ^[0-9]+$ ]] || bal=0; [[ "$alw" =~ ^[0-9]+$ ]] || alw=0
  pack_baseline=$((bal - alw))
  human_check "2. The paywall shows the introductory offer" \
    "Does the paywall show Monthly and Annual with prices and \"7 days free, then <price>\"?" || true

  # 3 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: subscribe through the introductory offer"
  step "On the paywall select Monthly, then tap \"Start trial\"."
  if [[ "$STORE" == "ios" ]]; then step "Confirm the App Store sheet; it names the sandbox environment. Sign in as the tester if asked."
  else step "Confirm the Play sheet; a license tester sees a test payment method. Pick the one that always approves."; fi
  step "The app should leave the paywall and open on the main screen."
  warn "Sandbox time is compressed: the free week lasts minutes. Go straight through the next three stages."
  human_check "3. Subscribed with the free trial and the app opened" \
    "Did the purchase complete and the app open past the paywall?" || true

  # 4 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: the entitlement is active on day one"
  say "The webhook's INITIAL_PURCHASE should write the row: period_type TRIAL, active_until in the future."
  local sql_day_one="select (e.period_type = 'TRIAL' and e.active_until > now()) as pass,
      e.period_type, e.active_until, e.event_at, now() as checked_at
    from public.user_entitlements e where e.user_id = '${q_uid}'"
  while true; do
    if poll 120 "$sql_day_one"; then
      purchase_event_at="$(json_first "$LAST_JSON" event_at)"
      log_step "4. Entitlement active on day one (TRIAL)" PASS "$(json_pretty "$LAST_JSON")
webhook log:
$(webhook_logs "$uid" 30)"
      break
    fi
    outcome "4. Entitlement active on day one (TRIAL)" "${LAST_JSON:-[]}" || break
    [[ $ABORTED == 1 ]] && return
  done
  [[ -n "$purchase_event_at" ]] || purchase_event_at="$(json_first "$(dev_select "select event_at from public.user_entitlements where user_id = '${q_uid}'" || true)" event_at)"

  # 5 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: the Allowance landed"
  say "The same delivery grants the monthly Allowance into the wallet (grant_allowance, keyed on the RevenueCat event id)."
  local sql_allowance="select (w.allowance > 0 and w.allowance_monthly > 0 and w.allowance_expires_at is not null
          and l.ref is not null and l.delta = w.allowance_monthly
          and w.balance - w.allowance = ${pack_baseline}) as pass,
      w.balance, w.allowance, w.allowance_monthly, w.allowance_expires_at,
      l.ref as rc_event_id, l.delta as granted, l.created_at as granted_at
    from public.token_wallets w
    left join lateral (select ref, delta, created_at from public.token_ledger
                        where user_id = w.user_id and reason = 'grant_allowance'
                        order by created_at desc limit 1) l on true
    where w.user_id = '${q_uid}'"
  while true; do
    if poll 60 "$sql_allowance"; then
      say "Allowance $(json_first "$LAST_JSON" allowance) of $(json_first "$LAST_JSON" allowance_monthly), pack credits untouched (${pack_baseline})."
      log_step "5. The Allowance landed" PASS "$(json_pretty "$LAST_JSON")"
      break
    fi
    outcome "5. The Allowance landed" "${LAST_JSON:-[]}" || break
    [[ $ABORTED == 1 ]] && return
  done

  # 6 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: cancel the subscription"
  if [[ "$STORE" == "ios" ]]; then
    step "iPhone: Settings → Developer → Sandbox Apple Account → Manage → Mealvana Pro → Cancel (free trial)."
  else
    step "Phone: Play Store → profile → Payments & subscriptions → Subscriptions → Mealvana Pro → Cancel subscription."
  fi
  say "Access runs to the end of the trial, so the row stays active; its event time moves forward."
  pause "Press Enter once the store says the subscription is cancelled."
  local sql_cancel="select (e.event_at > '$(sql_quote "${purchase_event_at:-1970-01-01}")'::timestamptz) as pass,
      e.period_type, e.active_until, e.event_at, e.active_until > now() as still_active, now() as checked_at
    from public.user_entitlements e where e.user_id = '${q_uid}'"
  while true; do
    if poll 180 "$sql_cancel"; then
      local cancel_note=""
      [[ "$(json_first "$LAST_JSON" period_type)" == "TRIAL" ]] || cancel_note="
Note: period_type is no longer TRIAL: the trial had already converted before the cancellation arrived."
      log_step "6. The cancellation reached DEV" PASS "$(json_pretty "$LAST_JSON")${cancel_note}
webhook log:
$(webhook_logs "$uid" 60)"
      break
    fi
    outcome "6. The cancellation reached DEV" "${LAST_JSON:-[]}" || break
    [[ $ABORTED == 1 ]] && return
  done

  # 7 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: the trial ends and the account meets the paywall"
  say "Waiting for the row's active_until to pass (sandbox trials end within minutes)."
  local sql_closed="select (e.active_until <= now()) as pass,
      e.period_type, e.active_until, e.event_at, now() as checked_at,
      coalesce(w.balance, 0) as balance, coalesce(w.allowance, 0) as allowance,
      (select count(*) from public.token_ledger l where l.user_id = e.user_id and l.reason = 'forfeit_allowance') as forfeits
    from public.user_entitlements e
    left join public.token_wallets w on w.user_id = e.user_id
    where e.user_id = '${q_uid}'"
  while true; do
    if poll 1200 "$sql_closed"; then
      last_event_at="$(json_first "$LAST_JSON" event_at)"
      local forfeit_note="Allowance forfeited (EXPIRATION delivered): allowance 0, forfeit ledger rows $(json_first "$LAST_JSON" forfeits)."
      [[ "$(json_first "$LAST_JSON" allowance)" == "0" ]] || forfeit_note="Allowance not yet forfeited: no EXPIRATION delivered at check time (the next debit forfeits it)."
      log_step "7a. The server gate closed" PASS "$(json_pretty "$LAST_JSON")
${forfeit_note}"
      break
    fi
    outcome "7a. The server gate closed" "${LAST_JSON:-[]}" || break
    [[ $ABORTED == 1 ]] && return
  done
  last_event_at="${last_event_at:-$(json_first "$(dev_select "select event_at from public.user_entitlements where user_id = '${q_uid}'" || true)" event_at)}"
  step "Force-quit the dev app and open it again. If it still opens, wait five minutes and relaunch once more."
  step "Expect the paywall with exactly: Restore purchases, Manage subscription, Sign out, Delete account."
  step "Expect no close button and no way into the app behind it."
  human_check "7b. The account meets the paywall" \
    "Is the app on the paywall with only those four actions besides the plans?" || true

  # 8 ─────────────────────────────────────────────────────────────────────
  stage "${STORE}: Restore reopens the app"
  say "Resubscribe outside the app, so Restore is the only thing in the app that can reopen it."
  if [[ "$STORE" == "ios" ]]; then
    step "iPhone: Settings → Developer → Sandbox Apple Account → Manage → Mealvana Pro → pick Monthly again."
  else
    step "Phone: Play Store → profile → Payments & subscriptions → Subscriptions → Mealvana Pro → Resubscribe."
  fi
  step "Back in the dev app, on the paywall, tap \"Restore purchases\"."
  step "Expect \"Your subscription has been restored.\" and the app opening past the paywall."
  human_check "8a. Restore reopened the app" \
    "Did Restore say the subscription was restored and open the app?" || true
  local sql_restore="select (e.active_until > now() and e.event_at > '$(sql_quote "${last_event_at:-1970-01-01}")'::timestamptz) as pass,
      e.period_type, e.active_until, e.event_at, now() as checked_at,
      (select count(*) from public.token_ledger l where l.user_id = e.user_id and l.reason = 'grant_allowance') as allowance_grants
    from public.user_entitlements e where e.user_id = '${q_uid}'"
  while true; do
    if poll 180 "$sql_restore"; then
      log_step "8b. The server gate reopened" PASS "$(json_pretty "$LAST_JSON")
webhook log:
$(webhook_logs "$uid" 120)"
      break
    fi
    outcome "8b. The server gate reopened" "${LAST_JSON:-[]}" || break
    [[ $ABORTED == 1 ]] && return
  done

  if (( STORE_FAILS == 0 )); then close_log GREEN; else close_log "RED (${STORE_FAILS} step(s) failed)"; fi
  say ""
  step "Tidy up: cancel the resubscription in the store so the sandbox account stops renewing."
  pause "Press Enter to continue."
}

# ── Dispatch ──────────────────────────────────────────────────────────────

MODE="${1:-both}"
case "$MODE" in
  -h|--help) usage; exit 0 ;;
  preflight)
    refuse_ci
    if preflight; then printf '%s✓ preflight passed%s\n' "$GREEN" "$RESET"; exit 0; fi
    die "preflight failed"
    ;;
  ios|android|both) ;;
  *) usage; exit 2 ;;
esac

refuse_ci
[[ -t 0 ]] || die "refusing to run without a terminal: the sandbox trial is run by hand (mp-289)."

STORES=()
case "$MODE" in
  both) STORES=(ios android) ;;
  *) STORES=("$MODE") ;;
esac
TOTAL_STAGES=$((1 + 8 * ${#STORES[@]}))

banner "Meal-planning sandbox trial run: ${STORES[*]}"

stage "Preflight: DEV is ready for the run"
preflight || { warn "Fix the above before running the trial."; exit 1; }
note "Every check below is a read-only SELECT against DEV ($DEV_REF). Nothing is written but the log."
pause "Press Enter to begin."

for s in "${STORES[@]}"; do
  run_store "$s"
done

_clear
printf '\n%s%s  Sandbox trial run finished%s\n' "$BOLD" "$BLUE" "$RESET"
all_green=0
for v in "${VERDICTS[@]}"; do
  note "$v"
  [[ "$v" == *": GREEN ("* ]] || all_green=1
done
printf '\n  %sCommit the log(s) under docs/release/sandbox-trial-runs/ with the release.%s\n' "$GREEN" "$RESET"
note "The gate needs a GREEN log for ios AND android (playbook §8 P3c)."
printf '\n'
exit "$all_green"
