/**
 * Regenerates test/features/onboarding/fixtures/plan_preview_parity.json
 * from the REAL TS formulas — which are themselves pinned by the ratified
 * vectors (vectors.conformance.test.ts). Never hand-patch the fixture:
 * re-run this after any ruled formula change so the Dart twin
 * (DailyBaselineCalculator) and the TS side move in lockstep.
 *
 *   deno run --allow-read --allow-write --node-modules-dir=none \
 *     supabase/functions/calculate-daily-macros-v6/tools/generate-parity-fixtures.ts
 */

import { calculateRMR } from '../formulas/rmr.ts';
import { baselineMacros, clampMacros } from '../formulas/baseline.ts';
import {
  carbDemand,
  sessionCost,
  zoneDistributionToIF,
} from '../formulas/session.ts';
import { calculateTDEE } from '../formulas/neat-tef.ts';
import { applyFatCap } from '../pipeline.ts';
import type { Sex, Sport } from '../types.ts';

const rmrCases = [
  { name: 'male baseline', weight_kg: 70, height_cm: 172, age: 35, sex: 'male', body_fat_pct: null },
  { name: 'female baseline', weight_kg: 60, height_cm: 165, age: 30, sex: 'female', body_fat_pct: null },
  { name: 'non-male branch (other) equals female offset', weight_kg: 60, height_cm: 165, age: 30, sex: 'other', body_fat_pct: null },
  { name: 'cunningham when body fat known', weight_kg: 70, height_cm: 172, age: 35, sex: 'male', body_fat_pct: 15 },
  { name: 'generic defaults case (non-male)', weight_kg: 70, height_cm: 172, age: 35, sex: 'female', body_fat_pct: null },
];

const baselineCases = [
  { name: 'no lbm, under masters', weight_kg: 70, lbm_kg: null, age: 35 },
  { name: 'masters boundary at 45', weight_kg: 70, lbm_kg: null, age: 45 },
  { name: 'just under masters at 44', weight_kg: 70, lbm_kg: null, age: 44 },
  { name: 'lbm-driven protein', weight_kg: 70, lbm_kg: 59.5, age: 35 },
];

const clampCases = [
  { name: 'carb ceiling 12 g/kg', carb_g: 900, prot_g: 98, weight_kg: 70 },
  { name: 'carb floor 3 g/kg', carb_g: 100, prot_g: 98, weight_kg: 70 },
  { name: 'protein floor 1.2 g/kg', carb_g: 280, prot_g: 80, weight_kg: 70 },
  { name: 'protein ceiling 2.5 g/kg', carb_g: 280, prot_g: 200, weight_kg: 70 },
];

const sessionCases = [
  {
    name: 'preview representative endurance session (run 2.5h)',
    pct_conversational: 0.80, pct_tempo: 0.15, pct_allout: 0.05,
    sport: 'running', duration_hr: 2.5, weight_kg: 70,
  },
  {
    name: 'short easy session gets no 1.15 multiplier',
    pct_conversational: 1.0, pct_tempo: 0.0, pct_allout: 0.0,
    sport: 'running', duration_hr: 1.0, weight_kg: 70,
  },
  {
    name: 'strength is a flat 27 g/hr, IF ignored (Q-003)',
    pct_conversational: 0.0, pct_tempo: 0.0, pct_allout: 1.0,
    sport: 'strength', duration_hr: 1.0, weight_kg: 70,
  },
];

const tdeeCases = [
  {
    name: 'rest day converges (male 70kg baseline, moderate NEAT)',
    rmr: 1605, neat: 401.25, session_kcal: 0,
    carb_g: 280, prot_g: 98, weight_kg: 70,
  },
  {
    name: 'fat pinned at floor when carbs dominate (2 passes)',
    rmr: 1605, neat: 361.125, session_kcal: 0,
    carb_g: 394, prot_g: 98, weight_kg: 70,
  },
];

const fatCapCases = [
  {
    name: 'training-day residual caps at 30 %E, excess to carb (Q-014)',
    rmr: 1605, neat: 441.375, session_kcal: 1863.0577777777778,
    carb_g: 402.5617879390505, prot_g: 98, weight_kg: 70,
  },
  {
    name: 'rest-day residual barely over the cap',
    rmr: 1605, neat: 401.25, session_kcal: 0,
    carb_g: 280, prot_g: 98, weight_kg: 70,
  },
];

const fixture = {
  _comment:
    'Shared parity fixtures pinning DailyBaselineCalculator (Dart) against calculate-daily-macros formulas (TS), both consumed by test/features/onboarding/daily_baseline_calculator_test.dart AND supabase/functions/calculate-daily-macros-v6/parity-fixtures.test.ts. GENERATED by tools/generate-parity-fixtures.ts from the vector-pinned formulas (bundle daily-macros-dashboard@v1) — regenerate, never hand-patch.',
  rmr: rmrCases.map((c) => ({
    ...c,
    expected: calculateRMR(
      c.weight_kg,
      c.height_cm,
      c.age,
      (c.sex === 'male' ? 'male' : 'female') as Sex,
      c.body_fat_pct,
    ),
  })),
  baseline: baselineCases.map((c) => {
    const r = baselineMacros(c.weight_kg, c.lbm_kg, c.age);
    return { ...c, expected_carb_g: r.carb_g, expected_prot_g: r.prot_g };
  }),
  clamp: clampCases.map((c) => {
    const r = clampMacros(c.carb_g, c.prot_g, c.weight_kg);
    return { ...c, expected_carb_g: r.carb_g, expected_prot_g: r.prot_g };
  }),
  session: sessionCases.map((c) => {
    const intensityFactor = zoneDistributionToIF(
      c.pct_conversational,
      c.pct_tempo,
      c.pct_allout,
    );
    return {
      ...c,
      expected_if: intensityFactor,
      if_tolerance: 0.000001,
      expected_kcal: sessionCost(
        c.sport as Sport,
        c.duration_hr,
        intensityFactor,
        c.weight_kg,
      ),
      kcal_tolerance: 0.001,
      expected_carb_g: carbDemand(
        c.sport as Sport,
        intensityFactor,
        c.duration_hr,
        c.weight_kg,
      ),
      carb_tolerance: 0.001,
    };
  }),
  tdee: tdeeCases.map((c) => {
    const r = calculateTDEE(
      c.rmr,
      c.neat,
      c.session_kcal,
      c.carb_g,
      c.prot_g,
      c.weight_kg,
    );
    return {
      ...c,
      expected_tdee: r.tdee,
      expected_fat_g: r.fat_g,
      expected_tef: r.tef,
      expected_fat_at_floor: r.fat_at_floor,
      tolerance: 0.001,
    };
  }),
  fat_cap: fatCapCases.map((c) => {
    const t = calculateTDEE(
      c.rmr,
      c.neat,
      c.session_kcal,
      c.carb_g,
      c.prot_g,
      c.weight_kg,
    );
    const capped = applyFatCap(c.carb_g, t.fat_g, t.tdee, c.weight_kg);
    return {
      ...c,
      pre_cap_fat_g: t.fat_g,
      tdee: t.tdee,
      expected_carb_g: capped.carb_g,
      expected_fat_g: capped.fat_g,
      tolerance: 0.001,
    };
  }),
};

const outPath = new URL(
  '../../../../test/features/onboarding/fixtures/plan_preview_parity.json',
  import.meta.url,
);
Deno.writeTextFileSync(outPath, JSON.stringify(fixture, null, 2) + '\n');
console.log(`wrote ${outPath.pathname}`);
