// node --test test/scripts/patrol-targets.test.mjs
//
// What the self-hosted runner's Patrol job runs: every *_test.dart in integration_test/ and
// integration_test/flows/ minus the exclusion list, and how many patrolTest cases that makes.
// Every case builds a hand-written integration_test folder in a temp dir and checks what the
// script returns, prints and exits with.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { plan } from '../../scripts/patrol-targets.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const cli = join(root, 'scripts/patrol-targets.mjs');

const oneCase = name => `import 'package:patrol/patrol.dart';\nvoid main() {\n  patrolTest('${name}', ($) async {});\n}\n`;

/** A repo root holding integration_test/ with the given files (path -> content). */
function repo(files, exclusions = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'patrol-targets-'));
  mkdirSync(join(dir, 'integration_test/flows'), { recursive: true });
  mkdirSync(join(dir, 'integration_test/helpers'), { recursive: true });
  for (const [p, body] of Object.entries(files)) writeFileSync(join(dir, 'integration_test', p), body);
  writeFileSync(join(dir, 'integration_test/runner_exclusions.json'), JSON.stringify(exclusions));
  return dir;
}

test('every test file in the folder and in flows/ is a target; helpers and non-tests are not', () => {
  const dir = repo({
    'patrol_smoke_test.dart': oneCase('smoke'),
    'flows/a_flow_test.dart': oneCase('a'),
    'flows/b_flow_test.dart': oneCase('b'),
    'helpers/flow_launcher.dart': 'void launchApp() {}\n',
    'test_bundle.dart': '// generated by patrol\n',
    'README.md': '# x\n',
  });
  assert.deepEqual(plan(dir).targets, [
    'integration_test/flows/a_flow_test.dart',
    'integration_test/flows/b_flow_test.dart',
    'integration_test/patrol_smoke_test.dart',
  ]);
});

test('a flow on the exclusion list is not a target and its cases do not count', () => {
  const dir = repo(
    { 'flows/a_flow_test.dart': oneCase('a'), 'flows/chat_flow_test.dart': oneCase('chat') },
    { 'flows/chat_flow_test.dart': { reason: 'ai-spend', why: 'calls vana-chat' } },
  );
  const p = plan(dir);
  assert.deepEqual(p.targets, ['integration_test/flows/a_flow_test.dart']);
  assert.equal(p.expected, 1);
  assert.deepEqual(p.excluded, [{ target: 'integration_test/flows/chat_flow_test.dart', reason: 'ai-spend', why: 'calls vana-chat' }]);
});

test('the expected count is the patrolTest calls across the targets', () => {
  const two = `void main() {\n  patrolTest('x', ($) async {});\n\n  patrolTest(\n    'y',\n    ($) async {},\n  );\n}\n`;
  const dir = repo({ 'flows/a_flow_test.dart': oneCase('a'), 'flows/b_flow_test.dart': two });
  assert.equal(plan(dir).expected, 3);
});

test('a patrolTest named only in a comment does not count', () => {
  const body = `/// Every case is a patrolTest(...) call.\n// patrolTest('old', ...) was removed\n${oneCase('a')}`;
  assert.equal(plan(repo({ 'flows/a_flow_test.dart': body })).expected, 1);
});

test('a file that registers cases in a loop declares its count with runner-cases', () => {
  const loop = `// runner-cases: 3\nvoid main() {\n  for (final p in ['a', 'b', 'c']) {\n    patrolTest(p, ($) async {});\n  }\n}\n`;
  assert.equal(plan(repo({ 'flows/loop_flow_test.dart': loop })).expected, 3);
});

test('an exclusion naming a flow that does not exist is refused, so the list cannot go stale', () => {
  const dir = repo({ 'flows/a_flow_test.dart': oneCase('a') }, { 'flows/gone_flow_test.dart': { reason: 'ai-spend', why: 'x' } });
  assert.throws(() => plan(dir), /gone_flow_test\.dart.*does not exist/);
});

test('an exclusion without a reason and a why is refused', () => {
  const dir = repo({ 'flows/a_flow_test.dart': oneCase('a') }, { 'flows/a_flow_test.dart': { reason: 'ai-spend' } });
  assert.throws(() => plan(dir), /a_flow_test\.dart.*reason and a why/);
});

test('the CLI prints one --target per line, and the count', () => {
  const dir = repo({ 'flows/a_flow_test.dart': oneCase('a'), 'patrol_smoke_test.dart': oneCase('s') });
  const targets = spawnSync('node', [cli, 'targets', '--root', dir], { encoding: 'utf8' });
  assert.equal(targets.status, 0, targets.stderr);
  assert.equal(targets.stdout, 'integration_test/flows/a_flow_test.dart\nintegration_test/patrol_smoke_test.dart\n');
  const count = spawnSync('node', [cli, 'count', '--root', dir], { encoding: 'utf8' });
  assert.equal(count.stdout, '2\n');
});

test('the CLI exits non-zero and says why when the exclusion list is broken', () => {
  const dir = repo({ 'flows/a_flow_test.dart': oneCase('a') }, { 'flows/gone_flow_test.dart': { reason: 'ai-spend', why: 'x' } });
  const r = spawnSync('node', [cli, 'targets', '--root', dir], { encoding: 'utf8' });
  assert.equal(r.status, 1);
  assert.match(r.stderr, /gone_flow_test\.dart/);
  assert.equal(r.stdout, '');
});

test("the repo's own exclusion list names only flows that exist, each with a reason", () => {
  const p = plan(root);
  assert.ok(p.targets.length > 0);
  assert.ok(p.excluded.every(e => e.reason && e.why));
  assert.ok(p.expected >= p.targets.length);
});
