// Formula Kit data — production schema
// Before: sub_phase ∈ {meal, snack, top_up}
// During: no static macros (algorithm-driven)

const DIET_LABELS = {
  vegan: "Vegan",
  vegetarian: "Vegetarian",
  gluten_free: "Gluten-Free",
  dairy_free: "Dairy-Free",
  keto: "Keto",
  low_carb: "Low Carb",
  paleo: "Paleo",
};

const BEFORE_FORMULAS = [
  // ===== MEAL (1.5–3h) — 11 templates =====
  { id: "b-bagel-pbj", name: "Bagel + PB + Jam", category: "Bagel",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 33, protein: 9, fat: 8, sodium: 380, fluid: 0 },
    components: ["1 bagel", "2 tbsp peanut butter", "1 tbsp jam"],
    servings: [0.5, 2], addOns: ["+ Banana", "+ Sports Drink"],
    allergens: ["Gluten", "Peanut"], excludes: ["gluten_free", "keto", "low_carb", "paleo"] },
  { id: "b-cereal-milk", name: "Cereal + Milk", category: "Cereal",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 25, protein: 6, fat: 3, sodium: 200, fluid: 120 },
    components: ["1 cup cereal", "1 cup milk"],
    servings: [0.5, 2], allergens: ["Dairy", "Gluten"],
    excludes: ["gluten_free", "keto", "low_carb", "paleo", "vegan"] },
  { id: "b-oatmeal-raisins", name: "Oatmeal + Raisins", category: "Oats / Granola",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 35, protein: 3.5, fat: 1.5, sodium: 5, fluid: 0 },
    components: ["1 cup oatmeal", "2 tbsp raisins"],
    servings: [0.5, 2], addOns: ["+ Honey"],
    allergens: [], excludes: ["gluten_free", "keto", "low_carb"] },
  { id: "b-fruit-bowl", name: "Fruit Bowl", category: "Fruit Mix",
    sub_phase: "meal", digestion: "Fast", type: "food",
    macros: { carbs: 90, protein: 2, fat: 1, sodium: 5, fluid: 0 },
    components: ["1 banana", "4 dates", "1/2 cup mixed berries"],
    servings: [0.5, 1.5], allergens: [], excludes: ["keto"] },
  { id: "b-potato-salt", name: "Potato + Salt", category: "Potato",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 37, protein: 2, fat: 0, sodium: 300, fluid: 0 },
    components: ["1 baked potato", "pinch of salt"],
    servings: [0.5, 2], allergens: [], excludes: [] },
  { id: "b-rice-honey", name: "Rice Cakes + Honey", category: "Rice Cakes",
    sub_phase: "meal", digestion: "Fast", type: "food",
    macros: { carbs: 42, protein: 2, fat: 0, sodium: 95, fluid: 0 },
    components: ["3 rice cakes", "1 tbsp honey"],
    servings: [1, 2], allergens: [], excludes: ["keto", "low_carb"] },
  { id: "b-toast-jam", name: "Toast + Jam", category: "Bread",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 30, protein: 4, fat: 1, sodium: 240, fluid: 0 },
    components: ["2 slices white toast", "2 tbsp jam"],
    servings: [0.5, 2], allergens: ["Gluten"],
    excludes: ["gluten_free", "keto", "low_carb"] },
  { id: "b-pancakes", name: "Pancakes + Syrup", category: "Bread",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 55, protein: 6, fat: 7, sodium: 480, fluid: 0 },
    components: ["3 small pancakes", "2 tbsp syrup"],
    servings: [0.5, 1.5], allergens: ["Gluten", "Dairy", "Egg"],
    excludes: ["gluten_free", "vegan", "keto"] },
  { id: "b-yogurt-granola", name: "Yogurt + Granola", category: "Yogurt",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 32, protein: 12, fat: 5, sodium: 90, fluid: 0 },
    components: ["1 cup Greek yogurt", "1/4 cup granola"],
    servings: [0.5, 1.5], allergens: ["Dairy", "Gluten"],
    excludes: ["vegan", "gluten_free", "keto"] },
  { id: "b-smoothie", name: "Smoothie Bowl", category: "Fruit Mix",
    sub_phase: "meal", digestion: "Fast", type: "food",
    macros: { carbs: 48, protein: 6, fat: 4, sodium: 60, fluid: 200 },
    components: ["1 banana", "1 cup berries", "1/2 cup oat milk"],
    servings: [0.5, 1.5], allergens: [], excludes: ["keto"] },
  { id: "b-pb-toast", name: "PB Toast + Banana", category: "Bread",
    sub_phase: "meal", digestion: "Medium", type: "food",
    macros: { carbs: 38, protein: 8, fat: 9, sodium: 260, fluid: 0 },
    components: ["1 slice toast", "2 tbsp peanut butter", "1 banana"],
    servings: [0.5, 1.5], allergens: ["Gluten", "Peanut"],
    excludes: ["gluten_free", "keto", "low_carb"] },

  // ===== SNACK (30–90 min) — 11 templates =====
  { id: "b-banana-pb", name: "Banana + PB", category: "Fruit Mix",
    sub_phase: "snack", digestion: "Medium", type: "food",
    macros: { carbs: 28, protein: 5, fat: 8, sodium: 75, fluid: 0 },
    components: ["1 banana", "1 tbsp peanut butter"],
    servings: [0.5, 2], allergens: ["Peanut"], excludes: ["keto"] },
  { id: "b-trail-mix", name: "Trail Mix", category: "Quick Grab",
    sub_phase: "snack", digestion: "Medium", type: "food",
    macros: { carbs: 22, protein: 6, fat: 14, sodium: 95, fluid: 0 },
    components: ["1/4 cup trail mix"],
    servings: [0.5, 2], allergens: ["Tree Nut"], excludes: ["paleo"] },
  { id: "b-applesauce", name: "Applesauce Pouch", category: "Fruit Mix",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 22, protein: 0, fat: 0, sodium: 5, fluid: 90 },
    components: ["1 applesauce pouch"],
    servings: [1, 2], allergens: [], excludes: ["keto"] },
  { id: "b-dates", name: "Medjool Dates", category: "Fruit Mix",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 36, protein: 1, fat: 0, sodium: 1, fluid: 0 },
    components: ["3 medjool dates"],
    servings: [0.5, 2], allergens: [], excludes: ["keto", "low_carb"] },
  { id: "b-granola-bar", name: "Granola Bar", category: "Bar",
    sub_phase: "snack", digestion: "Medium", type: "food",
    macros: { carbs: 28, protein: 4, fat: 6, sodium: 130, fluid: 0 },
    components: ["1 granola bar"],
    servings: [1, 2], allergens: ["Gluten"],
    excludes: ["gluten_free", "keto", "low_carb"] },
  { id: "b-fig-bars", name: "Fig Bars", category: "Bar",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 30, protein: 2, fat: 2, sodium: 120, fluid: 0 },
    components: ["2 fig bars"],
    servings: [1, 2], allergens: ["Gluten"], excludes: ["gluten_free", "keto"] },
  { id: "b-toast-honey", name: "Toast + Honey", category: "Bread",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 30, protein: 3, fat: 1, sodium: 180, fluid: 0 },
    components: ["1 slice toast", "1 tbsp honey"],
    servings: [0.5, 2], allergens: ["Gluten"],
    excludes: ["gluten_free", "keto", "low_carb", "vegan"] },
  { id: "b-rice-jam", name: "Rice Cake + Jam", category: "Rice Cakes",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 24, protein: 1, fat: 0, sodium: 70, fluid: 0 },
    components: ["2 rice cakes", "1 tbsp jam"],
    servings: [1, 2], allergens: [], excludes: ["keto", "low_carb"] },
  { id: "b-pretzels", name: "Pretzels + Sports Drink", category: "Quick Grab",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 36, protein: 3, fat: 1, sodium: 420, fluid: 240 },
    components: ["1 oz pretzels", "8 oz sports drink"],
    servings: [0.5, 1.5], allergens: ["Gluten"], excludes: ["gluten_free", "keto"] },
  { id: "b-banana", name: "Banana", category: "Fruit Mix",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 27, protein: 1, fat: 0, sodium: 1, fluid: 0 },
    components: ["1 medium banana"],
    servings: [1, 2], addOns: ["+ Sports Drink"],
    allergens: [], excludes: ["keto"] },
  { id: "b-graham", name: "Graham Crackers", category: "Quick Grab",
    sub_phase: "snack", digestion: "Fast", type: "food",
    macros: { carbs: 24, protein: 2, fat: 3, sodium: 170, fluid: 0 },
    components: ["4 graham cracker squares"],
    servings: [1, 2], allergens: ["Gluten"], excludes: ["gluten_free", "keto"] },

  // ===== TOP-UP (< 30 min) — 7 templates =====
  { id: "b-energy-gel", name: "Energy Gel", category: "Quick Grab",
    sub_phase: "top_up", digestion: "Fast", type: "food",
    macros: { carbs: 25, protein: 0, fat: 0, sodium: 50, fluid: 0 },
    components: ["1 energy gel"],
    servings: [1, 2], addOns: ["+ Banana", "+ Sports Drink"],
    allergens: [], excludes: ["keto", "low_carb", "paleo"] },
  { id: "b-sports-drink", name: "Sports Drink", category: "Hydration",
    sub_phase: "top_up", digestion: "Fast", type: "drink",
    macros: { carbs: 14, protein: 0, fat: 0, sodium: 110, fluid: 237 },
    components: ["8 oz sports drink"],
    servings: [1, 2], allergens: [], excludes: ["keto"] },
  { id: "b-coconut-water", name: "Coconut Water", category: "Hydration",
    sub_phase: "top_up", digestion: "Fast", type: "drink",
    macros: { carbs: 9, protein: 0, fat: 0, sodium: 252, fluid: 240 },
    components: ["8 oz coconut water"],
    servings: [1, 2], allergens: [], excludes: [] },
  { id: "b-electrolyte-tab", name: "Electrolyte Tablet", category: "Electrolyte",
    sub_phase: "top_up", digestion: "Fast", type: "electrolyte",
    macros: { carbs: 2, protein: 0, fat: 0, sodium: 300, fluid: 0 },
    components: ["1 electrolyte tablet"],
    servings: [1, 2], allergens: [], excludes: [] },
  { id: "b-energy-chew", name: "Energy Chews", category: "Quick Grab",
    sub_phase: "top_up", digestion: "Fast", type: "food",
    macros: { carbs: 24, protein: 0, fat: 0, sodium: 60, fluid: 0 },
    components: ["1 packet energy chews"],
    servings: [1, 2], allergens: [], excludes: ["keto", "low_carb", "paleo"] },
  { id: "b-honey-stinger", name: "Honey Packet", category: "Quick Grab",
    sub_phase: "top_up", digestion: "Fast", type: "food",
    macros: { carbs: 17, protein: 0, fat: 0, sodium: 1, fluid: 0 },
    components: ["1 honey packet"],
    servings: [1, 2], allergens: [], excludes: ["vegan", "keto", "low_carb"] },
  { id: "b-juice-box", name: "Juice Box", category: "Hydration",
    sub_phase: "top_up", digestion: "Fast", type: "drink",
    macros: { carbs: 22, protein: 0, fat: 0, sodium: 15, fluid: 200 },
    components: ["1 juice box (200ml)"],
    servings: [1, 2], allergens: [], excludes: ["keto", "low_carb"] },
];

const DURING_FORMULAS = [
  { id: "d-gel-water", name: "Gel + Water",
    formula: "Gel + Water",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Triathlon — Run Leg"],
    durations: ["90-150"],
    gut: ["Low", "Moderate", "High"],
    components: ["Energy gel", "Water"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-banana-sd-water", name: "Banana + Sports Drink + Water",
    formula: "Banana + Sports Drink + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["90-150"],
    gut: ["Low", "Moderate", "High"],
    components: ["Banana", "Sports drink", "Water"],
    ratio: null, allergens: [], excludes: ["keto"] },
  { id: "d-sd-only", name: "Sports Drink Only",
    formula: "Sports Drink",
    foodForm: "Liquid Only",
    activities: ["Running", "Cycling", "Triathlon — Bike Leg", "Triathlon — Run Leg"],
    durations: ["<90"],
    gut: ["Low", "Moderate", "High"],
    components: ["Sports drink"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-stroopwafel", name: "Stroopwafel + Sports Drink + Water",
    formula: "Stroopwafel + Sports Drink + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["90-150"],
    gut: ["Low", "Moderate", "High"],
    components: ["Stroopwafel", "Sports drink", "Water"],
    ratio: null, allergens: ["Gluten", "Dairy"], excludes: ["vegan", "gluten_free"] },
  { id: "d-banana-gelwater-sd", name: "Banana + (Gel + Water) + Sports Drink",
    formula: "Banana + (Gel + Water) + Sports Drink",
    foodForm: "Mixed (Solid + Gel + Liquid)",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["150-240"],
    gut: ["Moderate", "High"],
    components: ["Banana", "Energy gel", "Water", "Sports drink"],
    ratio: "1:1", allergens: [], excludes: [] },
  { id: "d-hcdm-water", name: "High Carb Drink Mix + Water",
    formula: "High Carb Drink Mix + Water",
    foodForm: "Liquid Only",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["90-150", "150-240"],
    gut: ["High"],
    components: ["High carb drink mix", "Water"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-chews-water", name: "Energy Chews + Water",
    formula: "Energy Chews + Water",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Triathlon — Run Leg"],
    durations: ["<90", "90-150"],
    gut: ["Low", "Moderate", "High"],
    components: ["Energy chews", "Water"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-gel-sd", name: "Gel + Sports Drink",
    formula: "Gel + Sports Drink",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Cycling", "Triathlon — Run Leg", "Triathlon — Bike Leg"],
    durations: ["90-150"],
    gut: ["Moderate", "High"],
    components: ["Energy gel", "Sports drink"],
    ratio: "2:1", allergens: [], excludes: [] },
  { id: "d-banana-water", name: "Banana + Water",
    formula: "Banana + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["<90", "90-150"],
    gut: ["Low", "Moderate", "High"],
    components: ["Banana", "Water"],
    ratio: null, allergens: [], excludes: ["keto"] },
  { id: "d-rice-cake-sd", name: "Rice Cake + Sports Drink + Water",
    formula: "Rice Cake + Sports Drink + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["150-240", ">240"],
    gut: ["High"],
    components: ["Rice cake", "Sports drink", "Water"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-dates-sd", name: "Dates + Sports Drink",
    formula: "Dates + Sports Drink",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Running", "Triathlon — Bike Leg"],
    durations: ["90-150", "150-240"],
    gut: ["Moderate", "High"],
    components: ["Medjool dates", "Sports drink"],
    ratio: "2:1", allergens: [], excludes: ["keto"] },
  { id: "d-pbj-water", name: "PB&J + Water",
    formula: "PB&J + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling"],
    durations: [">240"],
    gut: ["High"],
    components: ["PB&J quarter", "Water"],
    ratio: null, allergens: ["Gluten", "Peanut"],
    excludes: ["gluten_free", "keto"] },
  { id: "d-bar-sd-water", name: "Energy Bar + Sports Drink + Water",
    formula: "Energy Bar + Sports Drink + Water",
    foodForm: "Mixed (Solid + Gel + Liquid)",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["150-240", ">240"],
    gut: ["Moderate", "High"],
    components: ["Energy bar", "Sports drink", "Water"],
    ratio: "1:1", allergens: [], excludes: [] },
  { id: "d-gel-sd-water", name: "Gel + Sports Drink + Water",
    formula: "Gel + Sports Drink + Water",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Triathlon — Run Leg"],
    durations: ["150-240"],
    gut: ["Moderate", "High"],
    components: ["Energy gel", "Sports drink", "Water"],
    ratio: "2:1", allergens: [], excludes: [] },
  { id: "d-water-tab", name: "Water + Salt Tab",
    formula: "Water + Salt Tab",
    foodForm: "Liquid Only",
    activities: ["Running", "Cycling", "Triathlon — Bike Leg", "Triathlon — Run Leg"],
    durations: ["<90"],
    gut: ["Low", "Moderate", "High"],
    components: ["Water", "Salt tablet"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-tri-transition", name: "Gel + Coconut Water",
    formula: "Gel + Coconut Water",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Triathlon — Transition"],
    durations: ["<90"],
    gut: ["Low", "Moderate", "High"],
    components: ["Energy gel", "Coconut water"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-2gel-sd", name: "2× Gel + Sports Drink",
    formula: "Gel + Gel + Sports Drink",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Cycling", "Triathlon — Run Leg"],
    durations: ["150-240"],
    gut: ["High"],
    components: ["Energy gel", "Energy gel", "Sports drink"],
    ratio: "2:1", allergens: [], excludes: [] },
  { id: "d-real-food-mix", name: "Rice Cake + Dates + Sports Drink",
    formula: "Rice Cake + Dates + Sports Drink",
    foodForm: "Liquid + Solid",
    activities: ["Cycling"],
    durations: [">240"],
    gut: ["High"],
    components: ["Savory rice cake", "Medjool dates", "Sports drink"],
    ratio: "1:1", allergens: [], excludes: [] },
  { id: "d-hcdm-water-tab", name: "High Carb Mix + Water + Salt Tab",
    formula: "High Carb Drink Mix + Water + Salt Tab",
    foodForm: "Liquid Only",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: [">240"],
    gut: ["High"],
    components: ["High carb drink mix", "Water", "Salt tablet"],
    ratio: null, allergens: [], excludes: [] },
  { id: "d-honey-water", name: "Honey + Water",
    formula: "Honey Packet + Water",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Triathlon — Run Leg"],
    durations: ["<90", "90-150"],
    gut: ["Moderate", "High"],
    components: ["Honey packet", "Water"],
    ratio: null, allergens: [], excludes: ["vegan", "keto"] },
  { id: "d-banana-honey-water", name: "Banana + Honey + Water",
    formula: "Banana + Honey Packet + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Running"],
    durations: ["90-150"],
    gut: ["Moderate", "High"],
    components: ["Banana", "Honey packet", "Water"],
    ratio: null, allergens: [], excludes: ["vegan", "keto"] },
  { id: "d-bonk-bar", name: "Bonk Bar + Water",
    formula: "Bonk Bar + Water",
    foodForm: "Liquid + Solid",
    activities: ["Cycling", "Triathlon — Bike Leg"],
    durations: ["150-240"],
    gut: ["High"],
    components: ["Bonk bar", "Water"],
    ratio: null, allergens: ["Gluten"], excludes: ["gluten_free"] },
  { id: "d-chews-sd", name: "Chews + Sports Drink",
    formula: "Energy Chews + Sports Drink",
    foodForm: "Liquid + Gel/Chew",
    activities: ["Running", "Triathlon — Run Leg"],
    durations: ["90-150"],
    gut: ["Moderate", "High"],
    components: ["Energy chews", "Sports drink"],
    ratio: "1:1", allergens: [], excludes: [] },
  { id: "d-juice-water", name: "Juice + Water",
    formula: "Juice + Water",
    foodForm: "Liquid Only",
    activities: ["Running", "Cycling"],
    durations: ["<90"],
    gut: ["Low", "Moderate", "High"],
    components: ["Juice", "Water"],
    ratio: null, allergens: [], excludes: ["keto"] },
  { id: "d-sd-tab-water", name: "Sports Drink + Salt Tab + Water",
    formula: "Sports Drink + Salt Tab + Water",
    foodForm: "Liquid Only",
    activities: ["Running", "Cycling", "Triathlon — Bike Leg", "Triathlon — Run Leg"],
    durations: ["90-150"],
    gut: ["Low", "Moderate", "High"],
    components: ["Sports drink", "Salt tablet", "Water"],
    ratio: null, allergens: [], excludes: [] },
];

window.BEFORE_FORMULAS = BEFORE_FORMULAS;
window.DURING_FORMULAS = DURING_FORMULAS;
window.DIET_LABELS = DIET_LABELS;

window.PHASE_OPTS = [
  { id: "before", label: "Before" },
  { id: "during", label: "During" },
];
window.SUB_PHASE_OPTS = [
  { id: "meal",   label: "Meal",   sub: "1.5–3 h before" },
  { id: "snack",  label: "Snack",  sub: "30–90 min before" },
  { id: "top_up", label: "Top-Up", sub: "< 30 min before" },
];
window.ACTIVITY_OPTS = [
  { id: "Running",                 label: "Running" },
  { id: "Cycling",                 label: "Cycling" },
  { id: "Triathlon — Bike Leg",    label: "Tri — Bike" },
  { id: "Triathlon — Run Leg",     label: "Tri — Run" },
  { id: "Triathlon — Transition",  label: "Tri — Transition" },
];
window.DURING_DURATION_OPTS = [
  { id: "<90",     label: "< 90 min" },
  { id: "90-150",  label: "90–150 min" },
  { id: "150-240", label: "150–240 min" },
  { id: ">240",    label: "> 240 min" },
];
window.FOOD_FORM_OPTS = [
  { id: "Liquid Only",                      label: "Liquid Only" },
  { id: "Liquid + Gel/Chew",                label: "Liquid + Gel/Chew" },
  { id: "Liquid + Solid",                   label: "Liquid + Solid" },
  { id: "Mixed (Solid + Gel + Liquid)",     label: "Mixed" },
];
window.GUT_LEVEL_OPTS = [
  { id: "Low",      label: "Low" },
  { id: "Moderate", label: "Moderate" },
  { id: "High",     label: "High" },
];
window.DIGESTION_OPTS = [
  { id: "Fast",   label: "Fast" },
  { id: "Medium", label: "Medium" },
];
window.TYPE_OPTS = [
  { id: "food",        label: "Food" },
  { id: "drink",       label: "Drink" },
  { id: "electrolyte", label: "Electrolyte" },
];
