import 'dart:async';
import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../shared/database/app_database.dart';
import '../../../shared/database/database_provider.dart';
import '../../../shared/services/logging_service.dart';
import '../../../shared/domain/activity_type.dart';
import '../domain/activity.dart' as domain;

part 'activities_repository.g.dart';

@riverpod
ActivitiesRepository activitiesRepository(Ref ref) {
  return ActivitiesRepository(
    supabase: Supabase.instance.client,
    database: ref.read(appDatabaseProvider),
    logger: ref.read(appLoggerProvider),
  );
}

/// Repository for managing activities following FOA pattern
/// Prepares for server-authoritative sync with edge functions
class ActivitiesRepository {
  const ActivitiesRepository({
    required SupabaseClient supabase,
    required AppDatabase database,
    required AppLogger logger,
  })  : _supabase = supabase,
        _database = database,
        _logger = logger;

  final SupabaseClient _supabase;
  final AppDatabase _database;
  final AppLogger _logger;

  /// Create a new activity (save to Drift first, then sync to Supabase for final ID)
  ///
  /// IMPORTANT: This method now waits for Supabase upload to complete before returning,
  /// ensuring the returned activity has the server-assigned ID. This prevents race
  /// conditions where the UI navigates with the local ID but the database gets rekeyed.
  Future<domain.Activity> createActivity({
    required String deviceId,
    required domain.Activity activity,
  }) async {
    try {
      // STEP 1: Save to Drift IMMEDIATELY with dirty flag
      // Note: ID will be auto-generated by database if not provided
      final generatedId = await _saveToDrift(activity.copyWith(
        needsUpload: true,
        localUpdatedAt: DateTime.now(),
      ));

      //get all Activities
      final activities = await _database.select(_database.activitiesTable).get();

      // Get the activity back from the database with the generated ID
      final savedActivity = await (_database.select(_database.activitiesTable)
            ..where((tbl) => tbl.id.equals(generatedId)))
          .getSingle();

      var activityWithId = _mapToActivityDomain(savedActivity);

      // STEP 2: Upload to Supabase SYNCHRONOUSLY
      // This ensures sync completes before returning, preventing race conditions
      _logger.info(
        'Uploading new activity to Supabase (sync)',
        context: 'ACTIVITIES_REPOSITORY',
        data: {
          'activityId': activityWithId.id,
          'hasNutritionPlan': activityWithId.nutritionPlanData != null,
        },
      );

      try {
        await _uploadActivityToSupabaseSync(deviceId, activityWithId);
      } catch (uploadError) {
        // Upload failed but local save succeeded - activity will sync later
        _logger.warning(
          'Supabase upload failed during create, activity will sync later',
          context: 'ACTIVITIES_REPOSITORY',
          data: {'activityId': activityWithId.id, 'error': uploadError.toString()},
        );
      }

      return activityWithId;
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to create activity',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Update an existing activity (offline-first: save to Drift first, background upload)
  Future<domain.Activity> updateActivity({
    required String deviceId,
    required domain.Activity activity,
  }) async {
    try {
      // OFFLINE-FIRST: Save to Drift IMMEDIATELY with dirty flag
      final activityWithDirtyFlag = activity.copyWith(
        needsUpload: true,
        localUpdatedAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await _saveToDrift(activityWithDirtyFlag);

      // Attempt background upload (non-blocking)
      unawaited(_uploadActivityToSupabase(deviceId, activity, 'update'));

      return activityWithDirtyFlag;
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to update activity',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Delete an activity (offline-first: mark deleted in Drift first, background upload)
  Future<void> deleteActivity({
    required String deviceId,
    required String activityId,
  }) async {
    try {
      // OFFLINE-FIRST: Mark as deleted in Drift IMMEDIATELY with dirty flag
      await (_database.update(_database.activitiesTable)
            ..where((tbl) => tbl.id.equals(activityId)))
          .write(ActivitiesTableCompanion(
        deletedAt: Value(DateTime.now()),
        needsUpload: const Value(true),
        localUpdatedAt: Value(DateTime.now()),
      ));

      // Attempt background upload (non-blocking)
      unawaited(_uploadActivityDeletion(deviceId, activityId));
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to delete activity',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Get all activities for a device (local-first, returns cached data)
  Future<List<domain.Activity>> getActivities(String userId) async {
    try {
      _logger.info(
        '🔍 QUERYING activities',
        context: 'ACTIVITIES_REPOSITORY',
        data: {'userId': userId},
      );

      // CRITICAL FIX: Use case-insensitive comparison for userId
      final query = _database.select(_database.activitiesTable)
        ..where((tbl) => tbl.userId.lower().equals(userId.toLowerCase()) & tbl.deletedAt.isNull())
        ..orderBy([(tbl) => OrderingTerm.desc(tbl.scheduledDateTime)]);

      final activities = await query.get();

      _logger.info(
        '🔍 QUERY RESULT',
        context: 'ACTIVITIES_REPOSITORY',
        data: {
          'userId': userId,
          'activitiesFound': activities.length,
          'allActivitiesInDB': await _database.select(_database.activitiesTable).get().then((a) => a.length),
        },
      );

      return activities.map(_mapToActivityDomain).toList();
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to get activities',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Get a specific activity by ID
  Future<domain.Activity?> getActivityById(String userId, String activityId) async {
    try {
      // CRITICAL FIX: Use case-insensitive comparison for userId
      final query = _database.select(_database.activitiesTable)
        ..where((tbl) =>
            tbl.userId.lower().equals(userId.toLowerCase()) &
            tbl.id.equals(activityId) &
            tbl.deletedAt.isNull());

      final activity = await query.getSingleOrNull();
      return activity != null ? _mapToActivityDomain(activity) : null;
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to get activity by ID',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Get activities for a specific date range
  Future<List<domain.Activity>> getActivitiesForDateRange(
    String userId,
    DateTime startDate,
    DateTime endDate,
  ) async {
    try {
      // CRITICAL FIX: Use case-insensitive comparison for userId
      final query = _database.select(_database.activitiesTable)
        ..where((tbl) =>
            tbl.userId.lower().equals(userId.toLowerCase()) &
            tbl.scheduledDateTime.isBetweenValues(startDate, endDate) &
            tbl.deletedAt.isNull())
        ..orderBy([(tbl) => OrderingTerm.asc(tbl.scheduledDateTime)]);

      final activities = await query.get();
      return activities.map(_mapToActivityDomain).toList();
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to get activities for date range',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Find activity by external provider workout ID
  ///
  /// Used to check if a workout has already been imported from Final Surge, etc.
  Future<domain.Activity?> findByProviderWorkoutId(
    String provider,
    String providerWorkoutId,
  ) async {
    try {
      final query = _database.select(_database.activitiesTable)
        ..where((tbl) =>
            tbl.syncedFromProvider.equals(provider) &
            tbl.providerWorkoutId.equals(providerWorkoutId) &
            tbl.deletedAt.isNull());

      final activity = await query.getSingleOrNull();
      return activity != null ? _mapToActivityDomain(activity) : null;
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to find activity by provider workout ID',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
        data: {'provider': provider, 'providerWorkoutId': providerWorkoutId},
      );
      return null; // Return null on error to allow sync to continue
    }
  }

  /// Insert a new activity directly (used by sync services)
  ///
  /// Unlike createActivity, this method doesn't immediately upload to Supabase.
  /// Used for batch imports from external providers.
  ///
  /// IMPORTANT: Always clears the activity ID to ensure a new row is created.
  /// The transformer may provide a pre-generated UUID, but we want the database
  /// to generate the actual ID to ensure proper INSERT behavior.
  Future<domain.Activity> insertActivity(domain.Activity activity) async {
    try {
      // Clear the ID to force INSERT path in _saveToDrift
      // This ensures we always create a new row, not update a non-existent one
      final activityWithFlags = activity.copyWith(
        id: '', // Force INSERT by clearing ID
        needsUpload: true,
        localUpdatedAt: DateTime.now(),
      );

      final generatedId = await _saveToDrift(activityWithFlags);

      final savedActivity = await (_database.select(_database.activitiesTable)
            ..where((tbl) => tbl.id.equals(generatedId)))
          .getSingle();

      _logger.info(
        'Inserted activity from sync',
        context: 'ACTIVITIES_REPOSITORY',
        data: {
          'activityId': generatedId,
          'provider': activity.syncedFromProvider,
          'providerWorkoutId': activity.providerWorkoutId,
        },
      );

      return _mapToActivityDomain(savedActivity);
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to insert activity',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        stackTrace: stackTrace,
      );
      rethrow;
    }
  }

  /// Save activity to Drift database (offline-first pattern)
  /// Returns the ID of the saved activity (auto-generated if creating new)
  Future<String> _saveToDrift(domain.Activity activity) async {
    // Log nutrition plan data presence for debugging
    if (activity.nutritionPlanData != null) {
      final jsonString = jsonEncode(activity.nutritionPlanData);
      _logger.info(
        'Saving activity with nutrition plan data',
        context: 'ACTIVITIES_REPOSITORY',
        data: {
          'activityId': activity.id,
          'hasNutritionPlan': true,
          'nutritionPlanDataSize': jsonString.length,
        },
      );
    } else {
      _logger.debug(
        'Saving activity without nutrition plan data',
        context: 'ACTIVITIES_REPOSITORY',
        data: {'activityId': activity.id, 'hasNutritionPlan': false},
      );
    }

    if (activity.id.isEmpty) {
      // CREATE: New activity - let database generate UUID
      final companion = ActivitiesTableCompanion.insert(
        id: const Value.absent(), // Trigger auto-generation
        userId: activity.userId,
        activityType: activity.activityType.name,
        title: activity.title,
        scheduledDateTime: activity.scheduledDateTime,
        status: Value(activity.status.name),
        distanceMiles: Value(activity.distanceMiles),
        durationMinutes: Value(activity.durationMinutes),
        paceTargetMinutesPerMile: Value(activity.paceTargetMinutesPerMile),
        intensityLevel: Value(activity.intensityLevel?.name),
        notes: Value(activity.notes),
        // Cycling-specific fields
        cyclingSpeedMph: Value(activity.cyclingSpeedMph),
        cyclingTerrain: Value(activity.cyclingTerrain),
        cyclingIndoorOutdoor: Value(activity.cyclingIndoorOutdoor),
        cyclingElevationGainFt: Value(activity.cyclingElevationGainFt),
        cyclingSessionGoal: Value(activity.cyclingSessionGoal),
        // Swimming-specific fields
        swimmingPacePer100mSeconds: Value(activity.swimmingPacePer100mSeconds),
        swimmingPoolOrOpenWater: Value(activity.swimmingPoolOrOpenWater),
        swimmingWaterTempC: Value(activity.swimmingWaterTempC),
        // Shared fields
        intensityTarget: Value(activity.intensityTarget),
        timeBeforeMinutes: Value(activity.timeBeforeMinutes),
        // Completion data
        completedAt: Value(activity.completedAt),
        actualDistanceMiles: Value(activity.actualDistanceMiles),
        actualDurationMinutes: Value(activity.actualDurationMinutes),
        completionRating: Value(activity.completionRating),
        completionNotes: Value(activity.completionNotes),
        // Nutrition plan data (embedded JSON)
        nutritionPlanData: Value(
          activity.nutritionPlanData != null
              ? jsonEncode(activity.nutritionPlanData)
              : null,
        ),
        // Reminder fields
        reminderEnabled: Value(activity.reminderEnabled),
        reminderDaysBefore: Value(activity.reminderDaysBefore),
        reminderTimeOfDay: Value(activity.reminderTimeOfDay),
        reminderRecurring: Value(activity.reminderRecurring),
        // Sync tracking
        needsUpload: Value(activity.needsUpload ?? false),
        localUpdatedAt: Value(activity.localUpdatedAt ?? DateTime.now()),
        deletedAt: const Value.absent(), // Soft delete support
        // External provider sync fields
        syncedFromProvider: Value(activity.syncedFromProvider),
        providerWorkoutId: Value(activity.providerWorkoutId),
        providerWorkoutUrl: Value(activity.providerWorkoutUrl),
        lastSyncedAt: Value(activity.lastSyncedAt),
        workoutSubtype: Value(activity.workoutSubtype),
        paceMinMinutesPerMile: Value(activity.paceMinMinutesPerMile),
        paceMaxMinutesPerMile: Value(activity.paceMaxMinutesPerMile),
        distanceMeters: const Value.absent(), // Calculated from distanceMiles if needed
        // Metadata
        createdAt: activity.createdAt,
        updatedAt: activity.updatedAt,
      );

      final insertedRow = await _database
          .into(_database.activitiesTable)
          .insertReturning(companion);

      _logger.debug(
        'Created new activity',
        context: 'ACTIVITIES_REPOSITORY',
        data: {'activityId': insertedRow.id},
      );

      return insertedRow.id;
    } else {
      // UPDATE: Existing activity - update by ID
      final companion = ActivitiesTableCompanion(
        id: Value(activity.id), // Preserve existing ID
        userId: Value(activity.userId),
        activityType: Value(activity.activityType.name),
        title: Value(activity.title),
        scheduledDateTime: Value(activity.scheduledDateTime),
        status: Value(activity.status.name),
        distanceMiles: Value(activity.distanceMiles),
        durationMinutes: Value(activity.durationMinutes),
        paceTargetMinutesPerMile: Value(activity.paceTargetMinutesPerMile),
        intensityLevel: Value(activity.intensityLevel?.name),
        notes: Value(activity.notes),
        // Cycling-specific fields
        cyclingSpeedMph: Value(activity.cyclingSpeedMph),
        cyclingTerrain: Value(activity.cyclingTerrain),
        cyclingIndoorOutdoor: Value(activity.cyclingIndoorOutdoor),
        cyclingElevationGainFt: Value(activity.cyclingElevationGainFt),
        cyclingSessionGoal: Value(activity.cyclingSessionGoal),
        // Swimming-specific fields
        swimmingPacePer100mSeconds: Value(activity.swimmingPacePer100mSeconds),
        swimmingPoolOrOpenWater: Value(activity.swimmingPoolOrOpenWater),
        swimmingWaterTempC: Value(activity.swimmingWaterTempC),
        // Shared fields
        intensityTarget: Value(activity.intensityTarget),
        timeBeforeMinutes: Value(activity.timeBeforeMinutes),
        // Completion data
        completedAt: Value(activity.completedAt),
        actualDistanceMiles: Value(activity.actualDistanceMiles),
        actualDurationMinutes: Value(activity.actualDurationMinutes),
        completionRating: Value(activity.completionRating),
        completionNotes: Value(activity.completionNotes),
        // Nutrition plan data (embedded JSON)
        nutritionPlanData: Value(
          activity.nutritionPlanData != null
              ? jsonEncode(activity.nutritionPlanData)
              : null,
        ),
        // Reminder fields
        reminderEnabled: Value(activity.reminderEnabled),
        reminderDaysBefore: Value(activity.reminderDaysBefore),
        reminderTimeOfDay: Value(activity.reminderTimeOfDay),
        reminderRecurring: Value(activity.reminderRecurring),
        // Sync tracking
        needsUpload: Value(activity.needsUpload ?? false),
        localUpdatedAt: Value(activity.localUpdatedAt ?? DateTime.now()),
        deletedAt: Value(activity.deletedAt), // Soft delete support
        // External provider sync fields
        syncedFromProvider: Value(activity.syncedFromProvider),
        providerWorkoutId: Value(activity.providerWorkoutId),
        providerWorkoutUrl: Value(activity.providerWorkoutUrl),
        lastSyncedAt: Value(activity.lastSyncedAt),
        workoutSubtype: Value(activity.workoutSubtype),
        paceMinMinutesPerMile: Value(activity.paceMinMinutesPerMile),
        paceMaxMinutesPerMile: Value(activity.paceMaxMinutesPerMile),
        // Metadata
        createdAt: Value(activity.createdAt),
        updatedAt: Value(activity.updatedAt),
      );

      await (_database.update(_database.activitiesTable)
            ..where((tbl) => tbl.id.equals(activity.id)))
          .write(companion);

      _logger.debug(
        'Updated existing activity',
        context: 'ACTIVITIES_REPOSITORY',
        data: {'activityId': activity.id},
      );

      return activity.id;
    }
  }

  /// Upload activity to Supabase in background (non-blocking)
  /// Uses direct Supabase upsert instead of edge function for better reliability
  Future<void> _uploadActivityToSupabase(
    String deviceId, // Kept for signature compatibility, but effectively unused for ID lookup
    domain.Activity activity,
    String operation,
  ) async {
    try {
      // Use userId from activity directly
      final userId = activity.userId;

      final payload = {
        'id': activity.id, // Use same UUID from Drift
        'user_id': userId,
        'activity_type': activity.activityType.name,
        'title': activity.title,
        'scheduled_date_time': activity.scheduledDateTime.toIso8601String(),
        'status': activity.status.name,
        'distance_miles': activity.distanceMiles,
        'duration_minutes': activity.durationMinutes,
        'pace_target_minutes_per_mile': activity.paceTargetMinutesPerMile,
        'intensity_level': activity.intensityLevel?.name,
        'intensity_target': activity.intensityTarget,
        'time_before_minutes': activity.timeBeforeMinutes,
        'notes': activity.notes,
        // Cycling fields
        'cycling_speed_mph': activity.cyclingSpeedMph,
        'cycling_terrain': activity.cyclingTerrain,
        'cycling_indoor_outdoor': activity.cyclingIndoorOutdoor,
        'cycling_elevation_gain_ft': activity.cyclingElevationGainFt,
        'cycling_session_goal': activity.cyclingSessionGoal,
        // Swimming fields
        'swimming_pace_per_100m_seconds': activity.swimmingPacePer100mSeconds,
        'swimming_pool_or_open_water': activity.swimmingPoolOrOpenWater,
        'swimming_water_temp_c': activity.swimmingWaterTempC,
        // Completion data (if provided)
        'completed_at': activity.completedAt?.toIso8601String(),
        'actual_distance_miles': activity.actualDistanceMiles,
        'actual_duration_minutes': activity.actualDurationMinutes,
        'completion_rating': activity.completionRating,
        'completion_notes': activity.completionNotes,
        // Nutrition plan data (embedded JSON)
        'nutrition_plan_data': activity.nutritionPlanData != null
            ? jsonEncode(activity.nutritionPlanData)
            : null,
        // Timestamps
        'created_at': activity.createdAt.toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      };

      if (operation == 'create') {
        // Insert with explicit UUID from Drift
        await _supabase
            .from('activities')
            .insert(payload);

        _logger.info(
          'Activity uploaded to Supabase with UUID',
          context: 'ACTIVITIES_REPOSITORY',
          data: {'activityId': activity.id},
        );

        await _clearDirtyFlag(activity.id);
      } else {
        // Update existing record by UUID
        await _supabase
            .from('activities')
            .upsert(payload);

        await _clearDirtyFlag(activity.id);
      }
    } catch (e) {
      _logger.warning(
        'Failed to upload activity (will retry on next sync)',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        data: {'activityId': activity.id},
      );
      // Don't rethrow - keep dirty flag, will retry on next sync
    }
  }

  /// Upload activity to Supabase SYNCHRONOUSLY
  /// Used during activity creation to ensure upload completes before returning
  Future<void> _uploadActivityToSupabaseSync(
    String deviceId,
    domain.Activity activity,
  ) async {
    // Use userId from activity directly
    final userId = activity.userId;

    final payload = {
      'id': activity.id, // Use same UUID from Drift
      'user_id': userId,
      'activity_type': activity.activityType.name,
      'title': activity.title,
      'scheduled_date_time': activity.scheduledDateTime.toIso8601String(),
      'status': activity.status.name,
      'distance_miles': activity.distanceMiles,
      'duration_minutes': activity.durationMinutes,
      'pace_target_minutes_per_mile': activity.paceTargetMinutesPerMile,
      'intensity_level': activity.intensityLevel?.name,
      'intensity_target': activity.intensityTarget,
      'time_before_minutes': activity.timeBeforeMinutes,
      'notes': activity.notes,
      // Cycling fields
      'cycling_speed_mph': activity.cyclingSpeedMph,
      'cycling_terrain': activity.cyclingTerrain,
      'cycling_indoor_outdoor': activity.cyclingIndoorOutdoor,
      'cycling_elevation_gain_ft': activity.cyclingElevationGainFt,
      'cycling_session_goal': activity.cyclingSessionGoal,
      // Swimming fields
      'swimming_pace_per_100m_seconds': activity.swimmingPacePer100mSeconds,
      'swimming_pool_or_open_water': activity.swimmingPoolOrOpenWater,
      'swimming_water_temp_c': activity.swimmingWaterTempC,
      // Completion data (if provided)
      'completed_at': activity.completedAt?.toIso8601String(),
      'actual_distance_miles': activity.actualDistanceMiles,
      'actual_duration_minutes': activity.actualDurationMinutes,
      'completion_rating': activity.completionRating,
      'completion_notes': activity.completionNotes,
      // Nutrition plan data (embedded JSON)
      'nutrition_plan_data': activity.nutritionPlanData != null
          ? jsonEncode(activity.nutritionPlanData)
          : null,
      // Timestamps
      'created_at': activity.createdAt.toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    };

    // Insert with explicit UUID from Drift
    await _supabase
        .from('activities')
        .insert(payload);

    _logger.info(
      'Activity uploaded to Supabase with UUID (sync)',
      context: 'ACTIVITIES_REPOSITORY',
      data: {'activityId': activity.id},
    );

    await _clearDirtyFlag(activity.id);
  }

  /// Upload activity deletion to Supabase in background (non-blocking)
  /// Uses direct Supabase delete instead of edge function for better reliability
  Future<void> _uploadActivityDeletion(
    String deviceId, // acts as userId in new architecture
    String activityId,
  ) async {
    try {
      // DIRECT FIX: Use deviceId as userId directly
      // The app architecture has unified deviceId and userId
      final userId = deviceId;

      // Use direct Supabase delete
      await _supabase
          .from('activities')
          .delete()
          .eq('id', activityId)
          .eq('user_id', userId);

      // Upload successful - hard delete from local database
      await (_database.delete(_database.activitiesTable)
            ..where((tbl) => tbl.id.equals(activityId)))
          .go();
    } catch (e) {
      _logger.warning(
        'Failed to upload activity deletion (will retry on next sync)',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
        data: {'activityId': activityId},
      );
      // Don't rethrow - keep dirty flag, will retry on next sync
    }
  }

  /// Clear dirty flag after successful upload
  Future<void> _clearDirtyFlag(String activityId) async {
    await (_database.update(_database.activitiesTable)
          ..where((tbl) => tbl.id.equals(activityId)))
        .write(const ActivitiesTableCompanion(needsUpload: Value(false)));
  }

  /// Map database Activity to domain Activity
  domain.Activity _mapToActivityDomain(Activity activity) {
    return domain.Activity(
      id: activity.id,
      userId: activity.userId,
      activityType: ActivityType.values.firstWhere(
        (type) => type.name == activity.activityType,
        orElse: () => ActivityType.running,
      ),
      title: activity.title,
      scheduledDateTime: activity.scheduledDateTime,
      status: domain.ActivityStatus.values.firstWhere(
        (status) => status.name == activity.status,
        orElse: () => domain.ActivityStatus.planned,
      ),
      distanceMiles: activity.distanceMiles,
      durationMinutes: activity.durationMinutes,
      paceTargetMinutesPerMile: activity.paceTargetMinutesPerMile,
      intensityLevel: activity.intensityLevel != null
          ? domain.IntensityLevel.values.firstWhere(
              (level) => level.name == activity.intensityLevel,
              orElse: () => domain.IntensityLevel.moderate,
            )
          : null,
      // Cycling-specific fields
      cyclingSpeedMph: activity.cyclingSpeedMph,
      cyclingTerrain: activity.cyclingTerrain,
      cyclingIndoorOutdoor: activity.cyclingIndoorOutdoor,
      cyclingElevationGainFt: activity.cyclingElevationGainFt,
      cyclingSessionGoal: activity.cyclingSessionGoal,
      // Swimming-specific fields
      swimmingPacePer100mSeconds: activity.swimmingPacePer100mSeconds,
      swimmingPoolOrOpenWater: activity.swimmingPoolOrOpenWater,
      swimmingWaterTempC: activity.swimmingWaterTempC,
      // Shared fields
      intensityTarget: activity.intensityTarget,
      timeBeforeMinutes: activity.timeBeforeMinutes,
      // Completion data
      completedAt: activity.completedAt,
      completionRating: activity.completionRating,
      completionNotes: activity.completionNotes,
      actualDistanceMiles: activity.actualDistanceMiles,
      actualDurationMinutes: activity.actualDurationMinutes,
      // Nutrition plan data (parse JSON string from database)
      nutritionPlanData: activity.nutritionPlanData != null
          ? _parseNutritionPlanData(activity.nutritionPlanData!)
          : null,
      notes: activity.notes,
      createdAt: activity.createdAt,
      updatedAt: activity.updatedAt,
      deletedAt: activity.deletedAt,
      // Reminder fields
      reminderEnabled: activity.reminderEnabled,
      reminderDaysBefore: activity.reminderDaysBefore,
      reminderTimeOfDay: activity.reminderTimeOfDay,
      reminderRecurring: activity.reminderRecurring,
      // Sync fields
      needsUpload: activity.needsUpload,
      localUpdatedAt: activity.localUpdatedAt,
      // External provider sync fields
      syncedFromProvider: activity.syncedFromProvider,
      providerWorkoutId: activity.providerWorkoutId,
      providerWorkoutUrl: activity.providerWorkoutUrl,
      lastSyncedAt: activity.lastSyncedAt,
      workoutSubtype: activity.workoutSubtype,
      paceMinMinutesPerMile: activity.paceMinMinutesPerMile,
      paceMaxMinutesPerMile: activity.paceMaxMinutesPerMile,
    );
  }

  /// Parse nutrition plan data JSON string from database
  Map<String, dynamic>? _parseNutritionPlanData(String jsonString) {
    try {
      return jsonDecode(jsonString) as Map<String, dynamic>;
    } catch (e) {
      _logger.error(
        'Failed to parse nutrition plan data',
        context: 'ACTIVITIES_REPOSITORY',
        error: e,
      );
      return null;
    }
  }
}
